### PR TITLE
Fix window resizing problems

### LINKED ISSUE #4151: The new resizing feature breaks default window resolution
I usually play in windowed mode at 1024×768. Ubuntu MATE automatically maximizes new windows. With other programs, I can do this:
- Start the program in windowed mode. It is automatically maximized.
- Click-and-drag the titlebar. The window is returned to its normal window size.

With Widelands, this works the first time after I start it. But when I do this:
- Start WL. It is automatically maximized.
- Hit Escape to exit.
- Start again. The window is maximized again, but now I *can't* restore it to my preferred windowed resolution because on exiting the new (maximized) resolution was saved to the config file.

This is extremely annoying for me because I need to be able to see the terminal output in the background when debugging stuff, and I'm not going to change this very useful window manager setting because one program does not integrate properly with it.

Solution: The ability to resize is a very nice feature, but to keep it from annoying people, Widelands must not save the new window resolution to the config file if the window is maximized.

### LINKED ISSUE #4160: Game interface is drawn in a wrong place
Reported by @frankystone. I can't reproduce so far but I've seen this problem before. It happens when the surface the game draws on is different size than the window. Normally they should stay synchronized but apparently they do not in some cases. One case I know was problematic was when the game tried to resize a maximized window, but I thought I took care of it (by forcibly unmaximizing it before resize).

@frankystone On what OS does it happen? Is the window maximized at any point? Is the window being resized by any other means than the options screen? If you can reproduce it again can you post a screenshot of the entire window (and the exact steps that led there)?

Note: If the "Use system mouse cursor" option is disabled, then the cursor will also be drawn in a wrong position, but in sync with the interface, so the bug will be harder to notice.

**Version:** happens on #4080 and on master

**Original report:**

I used to start at resolution 1920x1080. If i set the resolution to 800x600 and reset it to 1920x1080 back, the mouse pointer do not 'grab' the buttons and the entries in the dropdowns correctly: I have to click at the bottom or below the buttons/dropdown-entries to trigger a click. Best noticeable in conjunction with the tooltips: They appear also at the bottom or below the button/dropdown-entries.

Hm, difficult to explain and difficult to reproduce. Try following:

1. Set 800x600 resolution in options and click Apply
2. Open Options again and set resolution back, but click on Cancel
3. Open Options again and set your preferred resolution and click on apply

Then hover over the buttons. The corresponding tooltip does not appear if the mouse pointer is on the top of the button. It appears only if the mouse pointer is on half height of the button. You can't make a click at the top of the buttons, only there where the tooltip appears. It feels like the button is moved down, like shown here:

screenshot

The position of the mouse pointer shows no tooltip. Only if i move the mouse a bit down (into the red marked area). And clicking do also only work in this red area. In this state the buttons of submenus are also not clickable, one has to click on the bottom window border to trigger the click.

The mouse pointer is below the button and one can trigger a click here:

screenshot

### PR DESCRIPTION
**Pull request by Niektory**
- Do not save window size on every resize event to avoid saving a maximized size. Instead save it only on application shutdown and in the options screen, and only if not maximized or fullscreen. (Fix #4151)
- Track the maximized state separately so we can save and restore it.
- Temporarily set the window as not resizable whenever we resize it ourselves. SDL can lose track of the real window size if we don't do this. See SDL bugs [2452](https://bugzilla.libsdl.org/show_bug.cgi?id=2452), [4574](https://bugzilla.libsdl.org/show_bug.cgi?id=4574). (Fix #4160)
- Remove some unnecessary window resizes.
- Add *Maximized* and *Fullscreen* to the *Window Size* dropdown; remove the *Fullscreen* checkbox.

### CODE REVIEW

**Comment by Noordfrees** [comment]
Yay, works for me :) 
Only one nit: When I resize the window while the options screen is open (e.g. using Ctrl+Super+Up to maximize), the resolution dropdown isn't updated. Pressing OK then results in this:
resolution

**Comment by gunchleoc** [comment]
This bug happens to me too when a resolution is selected from the dropdown and I click "Apply".

**Comment by Niektory** [comment]
Please reproduce again and post the log output and full window screenshots before and after the bug occurs.

**Comment by Noordfrees** [comment]
1. Widelands starts with the windowed resolution and is immediately maximized:


2. Resize with Ctrl-Super-Down:


3. Opening the Options screen, then resize with Ctrl-Super-Up:


4. Press OK → see bug (note also the mousecursor and tooltip positions)


Complete log:
```
This is Widelands Version 1.0~git24834[65cd844@HEAD] (Release)
INFO: Set home directory: /home/benedikt/.widelands
INFO: Set configuration file: /home/benedikt/.widelands/config
INFO: Widelands executable directory: /home/benedikt/wl/widelands/
INFO: Adding directory: /home/benedikt/wl/widelands/data
INFO: selected language: (system language)
INFO: using locale nds_DE.UTF-8
DEBUG: Byte order: little-endian
DEBUG: Graphics: Try to set Videomode 1024x768
DEBUG: Graphics: OpenGL: Version "4.6 (Compatibility Profile) Mesa 20.0.8"
DEBUG: Graphics: SDL_GL_RED_SIZE is 8
DEBUG: Graphics: SDL_GL_GREEN_SIZE is 8
DEBUG: Graphics: SDL_GL_BLUE_SIZE is 8
DEBUG: Graphics: SDL_GL_ALPHA_SIZE is 0
DEBUG: Graphics: SDL_GL_BUFFER_SIZE is 24
DEBUG: Graphics: SDL_GL_DOUBLEBUFFER is 1
DEBUG: Graphics: SDL_GL_DEPTH_SIZE is 24
DEBUG: Graphics: SDL_GL_STENCIL_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_RED_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0
DEBUG: Graphics: SDL_GL_STEREO is 0
DEBUG: Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
DEBUG: Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
DEBUG: Graphics: SDL_GL_ACCELERATED_VISUAL is 1
DEBUG: Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
DEBUG: Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
DEBUG: Graphics: SDL_GL_CONTEXT_FLAGS is 0
DEBUG: Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
DEBUG: Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
DEBUG: Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
DEBUG: Graphics: OpenGL: Double buffering enabled
DEBUG: Graphics: OpenGL: Max texture size: 16384
DEBUG: Graphics: OpenGL: ShadingLanguage: "4.60"
DEBUG: ++ maximized() = false
DEBUG: ++ set_maximized(true)
DEBUG: ++ resolution_changed(): 0x0 to 1024x768
DEBUG: **** GRAPHICS REPORT ****
DEBUG: VIDEO DRIVER x11
DEBUG: Display #0: 1920x1080 @ 60hz SDL_PIXELFORMAT_RGB888
DEBUG: **** END GRAPHICS REPORT ****
INFO: Style Manager: Reading style templates took 10ms
DEBUG: **** SOUND REPORT ****
DEBUG: SDL version: 2.0.10
DEBUG: SDL_mixer version: 2.0.4
DEBUG: **** END SOUND REPORT ****
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1920x986
DEBUG: ++ SDL_WINDOWEVENT_RESIZED: 1920x986
DEBUG: ++ change_resolution(): 1024x768 to 1920x986; resize_window=false
DEBUG: ++ resolution_changed(): 1024x768 to 1920x986
DEBUG: ++ refresh(): window size 1920x986 resizable
DEBUG: Initializing economy serial
DEBUG: lastserial: 0
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1024x768
DEBUG: ++ SDL_WINDOWEVENT_RESIZED: 1024x768
DEBUG: ++ change_resolution(): 1920x986 to 1024x768; resize_window=false
DEBUG: ++ resolution_changed(): 1920x986 to 1024x768
DEBUG: ++ SDL_WINDOWEVENT_RESTORED
DEBUG: ++ maximized() = false
DEBUG: ++ refresh(): window size 1024x768 resizable
DEBUG: ++ maximized() = false
DEBUG: ++ FullscreenMenuOptions(): cur_win_res=1024x768; opt.fullscreen=false; opt.maximized=false; g_gr->fullscreen()=false; g_gr->maximized()=false
DEBUG: ++ handle_menu(): begin
DEBUG: ++ SDL_WINDOWEVENT_MAXIMIZED
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1920x986
DEBUG: ++ SDL_WINDOWEVENT_RESIZED: 1920x986
DEBUG: ++ change_resolution(): 1024x768 to 1920x986; resize_window=false
DEBUG: ++ resolution_changed(): 1024x768 to 1920x986
DEBUG: ++ refresh(): window size 1920x986 resizable
DEBUG: ++ handle_menu(): 1
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ save_options(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
INFO: selected language: (system language)
INFO: using locale nds_DE.UTF-8
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ change_resolution(): 1920x986 to 1024x768; resize_window=true
DEBUG: ++ set_window_size(): (not) restoring window from 1920x986
DEBUG: ++ set_window_size(): attempting resize 1920x986 to 1024x768
DEBUG: ++ set_window_size(): not resizable
DEBUG: ++ set_window_size(): resized to 1024x768
DEBUG: ++ set_window_size(): resizable
DEBUG: ++ resolution_changed(): 1920x986 to 1024x768
DEBUG: ++ handle_menu(): middle
DEBUG: ++ handle_menu(): end
DEBUG: Initializing economy serial
DEBUG: lastserial: 0
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1024x768
DEBUG: ++ refresh(): window size 1024x768 resizable
DEBUG: ++ SDL_WINDOWEVENT_MAXIMIZED
DEBUG: ++ SDL_WINDOWEVENT_RESTORED
DEBUG: ++ maximized() = true
DEBUG: ++ SDL_WINDOWEVENT_MAXIMIZED
DEBUG: ++ SDL_WINDOWEVENT_MAXIMIZED
DEBUG: ++ SDL_WINDOWEVENT_RESTORED
DEBUG: ++ maximized() = true
DEBUG: ++ SDL_WINDOWEVENT_MAXIMIZED
DEBUG: ++ maximized() = true
DEBUG: ++ maximized() = true
DEBUG: SoundHandler: Closing 1 time, 22050 Hz, format 32784, 2 channels
DEBUG: SoundHandler: SDL_AUDIODRIVER pulseaudio
```

**Comment by Niektory** [comment]
Does it work better now?

**Comment by Noordfrees** [comment]
Now switching from fullscreen to windowed via the options menu doesn't work. And after a while of trying to switch between windowed and fullscreen I ended up with the same bug as before but this time in fullscreen mode.
```
This is Widelands Version 1.0~git24837[01f837e@HEAD] (Release)
INFO: Set home directory: /home/benedikt/.widelands
INFO: Set configuration file: /home/benedikt/.widelands/config
INFO: Widelands executable directory: /home/benedikt/wl/widelands/
INFO: Adding directory: /home/benedikt/wl/widelands/data
INFO: selected language: (system language)
INFO: using locale nds_DE.UTF-8
DEBUG: Byte order: little-endian
DEBUG: Graphics: Try to set Videomode 1024x768
DEBUG: Graphics: OpenGL: Version "4.6 (Compatibility Profile) Mesa 20.0.8"
DEBUG: Graphics: SDL_GL_RED_SIZE is 8
DEBUG: Graphics: SDL_GL_GREEN_SIZE is 8
DEBUG: Graphics: SDL_GL_BLUE_SIZE is 8
DEBUG: Graphics: SDL_GL_ALPHA_SIZE is 0
DEBUG: Graphics: SDL_GL_BUFFER_SIZE is 24
DEBUG: Graphics: SDL_GL_DOUBLEBUFFER is 1
DEBUG: Graphics: SDL_GL_DEPTH_SIZE is 24
DEBUG: Graphics: SDL_GL_STENCIL_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_RED_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0
DEBUG: Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0
DEBUG: Graphics: SDL_GL_STEREO is 0
DEBUG: Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
DEBUG: Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
DEBUG: Graphics: SDL_GL_ACCELERATED_VISUAL is 1
DEBUG: Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
DEBUG: Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
DEBUG: Graphics: SDL_GL_CONTEXT_FLAGS is 0
DEBUG: Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
DEBUG: Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
DEBUG: Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
DEBUG: Graphics: OpenGL: Double buffering enabled
DEBUG: Graphics: OpenGL: Max texture size: 16384
DEBUG: Graphics: OpenGL: ShadingLanguage: "4.60"
DEBUG: ++ resolution_changed(): 0x0 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: **** GRAPHICS REPORT ****
DEBUG: VIDEO DRIVER x11
DEBUG: Display #0: 1920x1080 @ 60hz SDL_PIXELFORMAT_RGB888
DEBUG: **** END GRAPHICS REPORT ****
INFO: Style Manager: Reading style templates took 8ms
DEBUG: **** SOUND REPORT ****
DEBUG: SDL version: 2.0.10
DEBUG: SDL_mixer version: 2.0.4
DEBUG: **** END SOUND REPORT ****
DEBUG: ++ SDL_WINDOWEVENT_MAXIMIZED
DEBUG: ++ maximized() = true
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1920x986
DEBUG: ++ maximized() = true
DEBUG: ++ SDL_WINDOWEVENT_RESIZED: 1920x986
DEBUG: ++ maximized() = true
DEBUG: ++ change_resolution(): 1024x768 to 1920x986; resize_window=false
DEBUG: ++ resolution_changed(): 1024x768 to 1920x986
DEBUG: ++ maximized() = true
DEBUG: ++ refresh(): window size 1920x986 resizable
DEBUG: ++ maximized() = true
DEBUG: Initializing economy serial
DEBUG: lastserial: 0
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ SDL_WINDOWEVENT_RESIZED: 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ change_resolution(): 1920x986 to 1024x768; resize_window=false
DEBUG: ++ resolution_changed(): 1920x986 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ SDL_WINDOWEVENT_RESTORED
DEBUG: ++ maximized() = false
DEBUG: ++ maximized() = false
DEBUG: ++ refresh(): window size 1024x768 resizable
DEBUG: ++ maximized() = false
DEBUG: ++ maximized() = false
DEBUG: ++ FullscreenMenuOptions(): cur_win_res=1024x768; opt.fullscreen=false; opt.maximized=false; g_gr->fullscreen()=false; g_gr->maximized()=false
DEBUG: ++ handle_menu(): begin
DEBUG: ++ SDL_WINDOWEVENT_MAXIMIZED
DEBUG: ++ maximized() = true
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1920x986
DEBUG: ++ maximized() = true
DEBUG: ++ SDL_WINDOWEVENT_RESIZED: 1920x986
DEBUG: ++ maximized() = true
DEBUG: ++ change_resolution(): 1024x768 to 1920x986; resize_window=false
DEBUG: ++ resolution_changed(): 1024x768 to 1920x986
DEBUG: ++ maximized() = true
DEBUG: ++ refresh(): window size 1920x986 resizable
DEBUG: ++ maximized() = true
DEBUG: ++ handle_menu(): 1
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ save_options(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
INFO: selected language: (system language)
INFO: using locale nds_DE.UTF-8
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ change_resolution(): 1920x986 to 1024x768; resize_window=true
DEBUG: ++ set_window_size(): not resizable
DEBUG: ++ maximized() = true
DEBUG: ++ set_window_size(): restoring window from 1920x986
DEBUG: ++ set_window_size(): restored window to 1920x986
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): attempting resize 1920x986 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resized to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resizable
DEBUG: ++ maximized() = false
DEBUG: ++ resolution_changed(): 1920x986 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ handle_menu(): middle
DEBUG: ++ handle_menu(): end
DEBUG: Initializing economy serial
DEBUG: lastserial: 0
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ refresh(): window size 1024x768 resizable
DEBUG: ++ maximized() = false
DEBUG: ++ set_fullscreen(): true
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): not resizable
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): attempting resize 1024x768 to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resized to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resizable
DEBUG: ++ maximized() = false
DEBUG: ++ resolution_changed(): 1024x768 to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ maximized() = false
DEBUG: ++ FullscreenMenuOptions(): cur_win_res=1024x768; opt.fullscreen=true; opt.maximized=false; g_gr->fullscreen()=true; g_gr->maximized()=false
DEBUG: ++ handle_menu(): begin
DEBUG: ++ handle_menu(): 1
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ save_options(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
INFO: selected language: (system language)
INFO: using locale nds_DE.UTF-8
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ set_fullscreen(): false
DEBUG: ++ set_window_size(): not resizable
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): attempting resize 1920x1080 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resized to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resizable
DEBUG: ++ maximized() = false
DEBUG: ++ set_maximized(false)
DEBUG: ++ maximized() = false
DEBUG: ++ maximized() = false
DEBUG: ++ resolution_changed(): 1920x1080 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ change_resolution(): 1024x768 to 1024x768; resize_window=true
DEBUG: ++ set_window_size(): not resizable
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): attempting resize 1024x768 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resized to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resizable
DEBUG: ++ maximized() = false
DEBUG: ++ resolution_changed(): 1024x768 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ handle_menu(): middle
DEBUG: ++ handle_menu(): end
DEBUG: Initializing economy serial
DEBUG: lastserial: 0
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ SDL_WINDOWEVENT_RESIZED: 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ change_resolution(): 1024x768 to 1920x1080; resize_window=false
DEBUG: ++ resolution_changed(): 1024x768 to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ refresh(): window size 1920x1080 resizable
DEBUG: ++ maximized() = false
DEBUG: ++ maximized() = false
DEBUG: ++ FullscreenMenuOptions(): cur_win_res=1920x1080; opt.fullscreen=false; opt.maximized=false; g_gr->fullscreen()=false; g_gr->maximized()=false
DEBUG: ++ handle_menu(): begin
DEBUG: ++ handle_menu(): middle
DEBUG: ++ handle_menu(): end
DEBUG: Initializing economy serial
DEBUG: lastserial: 0
DEBUG: ++ maximized() = false
DEBUG: ++ FullscreenMenuOptions(): cur_win_res=1920x1080; opt.fullscreen=false; opt.maximized=false; g_gr->fullscreen()=false; g_gr->maximized()=false
DEBUG: ++ handle_menu(): begin
DEBUG: ++ handle_menu(): 1
DEBUG: ++ get_values(): res_index=-2
DEBUG: ++ save_options(): 1024x768 fullscreen
DEBUG: ++ get_values(): res_index=-2
INFO: selected language: (system language)
INFO: using locale nds_DE.UTF-8
DEBUG: ++ get_values(): res_index=-2
DEBUG: ++ set_fullscreen(): true
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): not resizable
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): attempting resize 1920x1080 to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resized to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resizable
DEBUG: ++ maximized() = false
DEBUG: ++ resolution_changed(): 1920x1080 to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ get_values(): res_index=-2
DEBUG: ++ get_values(): res_index=-2
DEBUG: ++ handle_menu(): middle
DEBUG: ++ handle_menu(): end
DEBUG: Initializing economy serial
DEBUG: lastserial: 0
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ maximized() = false
DEBUG: ++ FullscreenMenuOptions(): cur_win_res=1920x1080; opt.fullscreen=true; opt.maximized=false; g_gr->fullscreen()=true; g_gr->maximized()=false
DEBUG: ++ handle_menu(): begin
DEBUG: ++ handle_menu(): 1
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ save_options(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
INFO: selected language: (system language)
INFO: using locale nds_DE.UTF-8
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ set_fullscreen(): false
DEBUG: ++ set_window_size(): not resizable
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): attempting resize 1920x1080 to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resized to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resizable
DEBUG: ++ maximized() = false
DEBUG: ++ set_maximized(false)
DEBUG: ++ maximized() = false
DEBUG: ++ maximized() = false
DEBUG: ++ resolution_changed(): 1920x1080 to 1920x1080
DEBUG: ++ maximized() = false
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ get_values(): res_index=6
DEBUG: ++ get_values(): 1024x768
DEBUG: ++ change_resolution(): 1920x1080 to 1024x768; resize_window=true
DEBUG: ++ set_window_size(): not resizable
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): attempting resize 1920x1080 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resized to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ set_window_size(): resizable
DEBUG: ++ maximized() = false
DEBUG: ++ resolution_changed(): 1920x1080 to 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ handle_menu(): middle
DEBUG: ++ handle_menu(): end
DEBUG: Initializing economy serial
DEBUG: lastserial: 0
DEBUG: ++ SDL_WINDOWEVENT_SIZE_CHANGED: 1024x768
DEBUG: ++ maximized() = false
DEBUG: ++ refresh(): window size 1024x768 resizable
DEBUG: ++ maximized() = false
DEBUG: ++ maximized() = false
DEBUG: ++ maximized() = false
DEBUG: SoundHandler: Closing 1 time, 22050 Hz, format 32784, 2 channels
DEBUG: SoundHandler: SDL_AUDIODRIVER pulseaudio
```

**Comment by Niektory** [comment]
> Now switching from fullscreen to windowed via the options menu doesn't work. And after a while of trying to switch between windowed and fullscreen I ended up with the same bug as before but this time in fullscreen mode.

I've installed MATE and have auto-maximize on startup enabled but I still can't reproduce your problems. I wonder what's different... (well, I'm using Manjaro, so a bunch of things I'm sure)

So, back to trial and error fixing. Please test again.

> When I resize the window while the options screen is open (e.g. using Ctrl+Super+Up to maximize), the resolution dropdown isn't updated.

I'm not sure if this needs to be changed. It's not the cause of the other problems.

**Comment by Noordfrees** [comment]
Now it always behaves as expected. Great work :) 

> > When I resize the window while the options screen is open (e.g. using Ctrl+Super+Up to maximize), the resolution dropdown isn't updated.
>
> I'm not sure if this needs to be changed. It's not the cause of the other problems.

OK. Now the selected item is always applied when clicking the OK button so it's not really a problem.

**Comment by Niektory** [comment]
If this also works for @gunchleoc and @frankystone I'll remove the debug spam. Others are also welcome to test of course as this behaves differently on different systems.

**Comment by gunchleoc** [comment]
It's working fine for me now :)

**Comment by frankystone** [comment]
Made a short test -> all fine :-)

**Review by gunchleoc — APPROVED** [review]

**Comment by gunchleoc** [comment]
Clang5 doesn't like - the problem should go away if you include `<SDL_video.h>` in `graphic.cc`.

**Comment by Niektory** [comment]
Clang 5 fails because it uses SDL2 version 2.0.2. We need at least 2.0.5.

**Comment by Niektory** [comment]
Should I disable the #4160 fix (or window resizing) when compiled with SDL2<2.0.5 to make it compile?

**Comment by gunchleoc** [comment]
We could simply require SDL >= 2.0.5. We're already dropping clang5 support as soon as https://github.com/widelands/widelands/pull/4199 goes green.

**Comment by gunchleoc** [comment]
Ubuntu Xenial comes with SDL 2.0.4 according to the Travis logs, so we'll need to support that.

**Review by gunchleoc — APPROVED** [review]

**Pull request merged**
