### PR TITLE
New reedfield graphics

### PR DESCRIPTION
**Pull request by fraang**
This puts in new reedfield graphics and adjusts the hot spots accordingly.

### CODE REVIEW

**Review by gunchleoc — APPROVED** [review]
Excellent :)

Can you add the blend file to the media repo too?

**Comment by fraang** [comment]
I have created a merge request on launchpad.net.

https://code.launchpad.net/~florian-angermeier/widelands-media/widelands-media/+merge/374544

**Comment by stonerl** [comment]
Please open it here. We don't use Launchpad anymore.

**Comment by stonerl** [comment]
Stupid me....

**Comment by gunchleoc** [comment]
@fraang Thanks for linking up the merge request, it's now merged in the media repo too :)

**Pull request merged**
