### PR TITLE
Refactor get_all_tribeinfos()

### LINKED ISSUE #4413: Nightly builds on Mac OS broken due to tests failing
Starting today (2020-10-26) nightlies fail to build due to test failures in test_economy:

```
Test project /Users/sirver/Desktop/Programming/cpp/widelands/widelands.build
    Start 1: test_ai
1/5 Test #1: test_ai ..........................   Passed    0.69 sec
    Start 2: test_economy
2/5 Test #2: test_economy .....................***Failed    0.27 sec
Running 21 test cases...
unknown location:0: fatal error: in "Road/PassabilityTest": FileNotFoundError: FileSystem::create: could not find file or directory: /Users/sirver/Desktop/Programming/cpp/widelands/data
/Users/sirver/Desktop/Programming/cpp/widelands/git_repo/src/economy/test/test_road.cc:93: last checkpoint: "PassabilityTest" fixture ctor
unknown location:0: fatal error: in "Road/CorrectSizeTest": FileNotFoundError: FileSystem::create: could not find file or directory: /Users/sirver/Desktop/Programming/cpp/widelands/data
/Users/sirver/Desktop/Programming/cpp/widelands/git_repo/src/economy/test/test_road.cc:96: last checkpoint: "CorrectSizeTest" fixture ctor
unknown location:0: fatal error: in "Road/InstantiateEditorGameBase": FileNotFoundError: FileSystem::create: could not find file or directory: /Users/sirver/Desktop/Programming/cpp/widelands/data
/Users/sirver/Desktop/Programming/cpp/widelands/git_repo/src/economy/test/test_road.cc:99: last checkpoint: "InstantiateEditorGameBase" fixture ctor

*** 3 failures are detected in the test module "Economy"


    Start 3: test_io_filesystem
3/5 Test #3: test_io_filesystem ...............   Passed    0.24 sec
    Start 4: notifications_test
4/5 Test #4: notifications_test ...............   Passed    0.19 sec
    Start 5: test_scripting
5/5 Test #5: test_scripting ...................   Passed    0.03 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) =   1.42 sec

The following tests FAILED:
	  2 - test_economy (Failed)
```

The current sha is d79d65d7e6e8fa3d80315c1ef0d36b555745a31b. 

I have not investigated, I hope somebody has an idea what that could be about. @gunchleoc maybe?

### PR DESCRIPTION
**Pull request by gunchleoc**
Replace exception with error log and show message boxes to player if no tribes are found.

Fixes https://github.com/widelands/widelands/issues/4413

### CODE REVIEW

**Comment by SirVer** [comment]
I tested this, and unfortunately it does not work for my needs, since I have the repo and the build directory not within each other, but parallel. i.e. 
- `/Users/sirver/Desktop/Programming/cpp/widelands/git_repo` is the repo
- `/Users/sirver/Desktop/Programming/cpp/widelands/build` is the build directory

How about keeping the old code, but allowing overwrites through an environment variable?

**Comment by gunchleoc** [comment]
> How about keeping the old code, but allowing overwrites through an environment variable?

I have never worked with Boost test cases before, so no clue how to do that right now.

Another option would be to refactor the engine agaiin in such a way that the test case no longer triggers calls to `Widelands::TribeBasicInfo::get_all_tribeinfos()`

**Comment by SirVer** [comment]
@gunchleoc I just realized that I can use this branch together with a symlink to make things work. For me that is a fine solution. Let's merge this!

**Comment by gunchleoc** [comment]
I have found a better solution which will also prevent Widelands from crashing if the player messes about with the `data/tribes/initializations` directory.

**Comment by SirVer** [comment]
The latest commit in this PR works for me, all CTESTs run again and pass. Thanks, @gunchleoc!

**Review by hessenfarmer — APPROVED** [review]
tested this. fixes my setup as well without any further action. 
Nice job!

**Pull request merged**
