### PR TITLE
Fix savegame compatibility #4482

### LINKED ISSUE #4482: Amazons branch broke map_buildingdata_packet
The attached savegame doesn't load any more, because its former immovable string is empty.

[expedition.wgf.zip](https://github.com/widelands/widelands/files/5503036/expedition.wgf.zip)

### PR DESCRIPTION
**Pull request by Noordfrees**
Fixes #4482
Unless we should hold a democratic forum debate about the pros and cons of this change with a majority voting first? (yes sorry but I could not resist)

### CODE REVIEW

**Comment by gunchleoc** [comment]
Hmm... maybe I should just have pushed everything to trunk without code review all those years we were short-handed on code reviews, that was so frustrating...

Sometimes, it is important to discuss things on the forum to get some more ideas. A feature idea can be shot down for a good reason and I have had ideas rejected too.

**Review by gunchleoc — CHANGES_REQUESTED** [review]
I get broken Barbarian sentries:

barbarian tree sentries


When I click on one of them, I get this:

widelands: ../src/logic/map_objects/tribes/dismantlesite.cc:162: static const Widelands::Buildcost Widelands::DismantleSite::count_returned_wares(Widelands::Building*): Assertion `first_idx != INVALID_INDEX' failed.

**Comment by Noordfrees** [comment]
Do you have a savegame?

**Comment by gunchleoc** [comment]
Yes, it's attached to the issue.

**Review by gunchleoc — APPROVED** [review]
That fixes it, thanks!

**Pull request merged**
