### PR TITLE
Get rid of duplicate translation fetching for tribes

### PR DESCRIPTION
**Pull request by gunchleoc**

### CODE REVIEW

**Review by hessenfarmer — COMMENTED** [review]
Changes look good.
Not tested.
Shouldn't we explain the necessity to Push and pop the textdomain and which textdomain to be used in the RST for each category?

**Comment by gunchleoc** [comment]
> Shouldn't we explain the necessity to Push and pop the textdomain and which textdomain to be used in the RST for each category?

Yes, will do.

**Comment by gunchleoc** [comment]
Documentation update is done. I have documented the world in this branch too - this is easier for me than splitting the documentation work over 2 branches.

**Review by hessenfarmer — APPROVED** [review]
Lgtm

**Comment by gunchleoc** [comment]
xgettext is picking up on the translatable strings in the RST documentation, so we have to fix that before merging.

**Pull request merged**
