### PR TITLE
Allow leaving game per keyboard shortcuts

### PR DESCRIPTION
**Pull request by ghost**
PR according to #1073

### CODE REVIEW

**Comment by gunchleoc** [comment]
The diff is huge and full of things that have nothing to do with your changes. Can you please merge master into your branch?

**Comment by ghost** [comment]
@gunchleoc I think this diff is so big because I merged master into windows-esc. Pulling all new changes from master in causes many conflicts.

**Comment by stonerl** [comment]
Rebased it with master and changed the push branch to master as well. @gunchleoc & @nifker please have a look at the diff.

**Comment by gunchleoc** [comment]
That is still huge, so I created a patch off the Launchpad branches and made a new branch with it, which will give us a clean diff https://github.com/widelands/widelands/tree/windows-escape

I have also cherry-picked Antonino's changes made in Git, so it should all be there. Please use the new branch from now on. I have added a small patch there myself to update the hotkey information.

The Esc key doesn't work for spectators. You can fix that by shifting the key handling code from `interactive_player.cc` to `interactive_gamebase.cc`. This was already a bug in the old code to do it in the wrong file.

**Comment by ghost** [comment]
There are some compilation errors remainings.

**Comment by gunchleoc** [comment]
@nifker I have created a clean branch at https://github.com/widelands/widelands/tree/windows-escape, see my post above. Please use that and make a new pull request -  it compiles on my machine and contains some additional changes that I made to update the hotkey information.

If you really don't want to try the other branch, please look at the diff in this pull request so that you know which unrelated changes to revert. f you are still having problems compiling afterwards, please post the errors here.

**Comment by ghost** [comment]
Should be ready now. I guess I need to create a new PR for that one?

**Comment by stonerl** [comment]
You should be able to use this PR and just change the branches.

**Comment by ghost** [comment]
@stonerl it seems like I cant change both selected branches.

**Comment by stonerl** [comment]
Right. I'm closing this one and you're gonna open a new one.

**Pull request closed without merging**
