### PR TITLE
Amazons

### PR DESCRIPTION
**Pull request by hessenfarmer**

### CODE REVIEW

**Comment by klaus-halfmann** [comment]
Hmm, 
* the Help for the "Gold Digger Dwelling", "Youth Gathering" and "Tapir Farm" give me a Lua Error.
* I would call the Stonecarvery "Toolmaker"

**Comment by hessenfarmer** [comment]
> Hmm,
> 
>     * the Help for the "Gold Digger Dwelling", "Youth Gathering" and "Tapir Farm" give me a Lua Error.

have fixed them and other issues.   

> 
>     * I would call the Stonecarvery "Toolmaker"   
  
-1 as it produces weapons as well

**Comment by stonerl** [comment]
Something is wrong here... Where are the travis-builds?

**Comment by klaus-halfmann** [comment]
I pullead and played this again today.
For the "Gold Digger Dwelling" In only get some lua exception ... more perhaps tomorrow

**Comment by klaus-halfmann** [comment]
I played the Amazones now for some hours and found that I could not build
a storage house, even though it is shown in the building statistics.
Balancing the diffeent types of normale/rare wood is a challenge, well.

Whats the current plan for this branch?

**Comment by hessenfarmer** [comment]
> 
> 
> I played the Amazones now for some hours and found that I could not build
> a storage house, even though it is shown in the building statistics.

thanks for testing. However I couldn't confirm that. Just tried with the latest build and could build a warehouse quite normal.     
 
> Balancing the diffeent types of normale/rare wood is a challenge, well.
> 
> Whats the current plan for this branch?     
   
Basically this Pull request is existing to generate build if I push a new revioson to my own fork. Furthermore it prevents Nordfriese and me pushing to the same repo which is easier to handle.  
Plan is to have this in the game sometime. However Nordfriese needs time for all the graphics. So we wait until he is finished and try to playtest and balance the amazons as good as could be done in the meantime. I'll try to keep this PR up to date with all discussions on the forum and Nordfrieses graphics work.

**Comment by stonerl** [comment]
@hessenfarmer I updated the base branch to the latest master. Would you be so kind and resolve the merge conflicts?

**Pull request merged**
