### PR TITLE
Adding a UI with a player list

### LINKED ISSUE #3236: Net relay should measure ping to players and Widelands should show it in the UI
Pulled out from https://code.launchpad.net/~widelands-dev/widelands/net-relay/+merge/332386

Since the net relay can measure ping to all players, it can identify "black sheeps" that lack the game. The host (or even better all players) of the game should be able to see this information somewhere in-game and the host can decide to kick a player/observer because of this.

The natural place for this would be in the chat window - e.g. we could add a list of participants in the chat window in game and add ping times as green/yellow/red indicators next to it.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2017-11-27T11:58:26Z
 * owner: sirver
 * the launchpad url was https://bugs.launchpad.net/bugs/1734673

### PR DESCRIPTION
**Pull request by Notabilis**
Adding a UI with a player list. The UI displays the RTT (time between host and client or relay and player) for all players. Participant names can be clicked for a whisper message and the host is able to kick participants from the game.
Also, some other minor changes.

The commits are created for reviewing and some will not compile.

Closes #3236

### CODE REVIEW

**Comment by klaus-halfmann** [comment]
Wow, this sound interesting. 
Is this itended for 1.0?
What do you itend to do about the failing tests?
Will try to compile thies for macOS now.

**Comment by Notabilis** [comment]
I am not sure about this in version 1.0. It probably would be nice to have, but it is okay for me if it doesn't make it.
The tests are hopefully fixed now, thanks for the pointer.

**Comment by frankystone** [comment]
@Notabilis : Can you resolve the conflicts and make it compile?

**Comment by hessenfarmer** [comment]
as there was no update for over a year now I think we could close this 
@Noordfrees

**Pull request closed without merging**
