### PR TITLE
Replace boost::regex with std::regex

### PR DESCRIPTION
**Pull request by gunchleoc**

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
Code LGTM. Could you deprecate boost::regex via a codecheck rule?

**Comment by gunchleoc** [comment]
> Code LGTM. Could you deprecate boost::regex via a codecheck rule?

No need, as it won't compile without adding the regex module to CMake again.

**Review by Noordfrees — APPROVED** [review]

**Comment by hessenfarmer** [comment]
this fails with clang 5

**Comment by gunchleoc** [comment]
It does. I have done some testing and we need to shift the minimum compiler version to Clang 6. I'll take care of the Travis setup in another branch.

**Pull request merged**
