### PR TITLE
Speed up Economy::find_best_supply()

### PR DESCRIPTION
**Pull request by Niektory**
Experimental. Cut searches earlier and cache the calculated costs to better sort future searches.

### CODE REVIEW

**Comment by tibor95** [comment]
Those cached_costs are tied to request or ware? Because everytime you are pairing request and supply it is something different.

**Comment by Niektory** [comment]
> Those cached_costs are tied to request or ware? Because everytime you are pairing request and supply it is something different.

I'm not sure I understand the question. Each cached cost is tied to:
- the economy
- the destination flag
- the source flag
If these match, the cached cost is used instead of air distance to sort the searches. This hopefully lets us more often search the least costly ones first so the longer ones are cancelled early.

**Comment by tibor95** [comment]
Yes, this was my question. Is there any lifetime on this cached costs? Removal of target flags removes cached entry for that flag - ok. But how it copes with other changes in road network?

**Comment by Niektory** [comment]
The cached costs are currently only removed when flags are removed or when the game is exited (they are not saveloaded which might or might not be a problem). Changes in the road network don't trigger any immediate changes to the cached costs, but they are updated whenever a search between the associated flags is run. If the search completes the new cost is cached. If it's cancelled because the cost_cutoff was reached then it's increased to cost_cutoff+1 if a lower cost was previously cached.

**Comment by tibor95** [comment]
Did you consider memory consumption on big maps?

**Comment by Niektory** [comment]
It's hard to estimate. It would have to be measured. I didn't do it yet.

**Comment by hessenfarmer** [comment]
@widelands/elders 
This one is stale as well I am afraid

**Pull request closed without merging**
