### PR TITLE
update_appdata.py reports validation failure for all files

### PR DESCRIPTION
**Pull request by SimonHeimberg**
Please fill out the relevant sections below and delete the rest.

**Type of change**
Enhancement
**Issue(s) closed**
Fixes -

**Old behavior**
update_appdata.py reports validation failure only for `desktop-file-validate`

**New behavior**
update_appdata.py reports validation failure for all files (by return code)

### CODE REVIEW

**Comment by tothxa** [comment]
Uh-oh… I so knew one day this would come bite me. :) While perfectly correct behaviour, this would make the flatpak beta builds fail.

Could you please add this option to allow fixing them:
https://github.com/SimonHeimberg/widelands/pull/2

(feel free to correct my python :) … except I deliberately didn't use `argparse`, because it would be too heavy for this simple task)

**Comment by SimonHeimberg** [comment]
I am fine to add this option. (only one suggestion about a command in the pr)

I partially remembered to have seen the manifest and found it again. I see the call on [github.com/flathub/.../org.widelands.Widelands.yaml#L63](https://github.com/flathub/org.widelands.Widelands/blob/fa06bd147923841352d906ddcea36130f99ebe40/org.widelands.Widelands.yaml#L63)
A thought: What about modifying xdg/org.widelands.Widelands.appdata.xml instead of the stub (in the manifest)? This file is validated already. If you want to be sure it is still valid after, you can run `appstreamcli  validate --no-net xdg/...appdata.xml`

**Comment by tothxa** [comment]
> A thought: What about modifying xdg/org.widelands.Widelands.appdata.xml instead of the stub (in the manifest)?

I don't want them to be out of sync, so I think it's best to use the "official" script for changes. Validation is a bonus.

**Review by tothxa — APPROVED** [review]
Thank you. :)

**Pull request merged**
