### PR TITLE
Keyboard handling for the Escape key

### PR DESCRIPTION
**Pull request by gunchleoc**
Close more windows and leave the game/editor with the Esc key

@nifker Proposed this for you. Code looks good, will do some final testing. How do you wish to be credited, nickname or real name of both?

### CODE REVIEW

**Comment by ghost** [comment]
Both seems to be fine.

**Comment by gunchleoc** [comment]
Excellent! I have added you and have also done the final testing, so it's good to go now.

Thanks for sticking with it!

**Comment by ghost** [comment]
Looks like the chat cant be exited using ESC - should it be added too?

**Comment by gunchleoc** [comment]
That would be good. Also, the load map and save game/save map screens. I haven't tested the sound options.

**Comment by gunchleoc** [comment]
The build went through, so I am merging this. Please feel free to create a new branch to implement this for more windows :)

**Pull request merged**
