### PR TITLE
fixed representative images of ports, scout's houses, and headquarters

### LINKED ISSUE #4278: helptexts for ports and scouts houses not shown
in current trunk the purpose helptexts for ports and scouts houses are not shown correctly although correctly defined in units.lua

### PR DESCRIPTION
**Pull request by hessenfarmer**
fixes #4278

### CODE REVIEW

**Comment by Noordfrees** [comment]
LGTM, tested and working.
For construction- and dismantlesites the helptexts are also missing, do you want to fix this here as well?

**Comment by hessenfarmer** [comment]
ok will do so

**Review by Noordfrees — COMMENTED** [review]
Good :)  

When selecting the hunter's house, warnings are printed to console:
```
WARNING: help item without icon_name: badger
WARNING: help item without icon_name: brownbear
WARNING: help item without icon_name: bunny
WARNING: help item without icon_name: chamois
WARNING: help item without icon_name: deer
WARNING: help item without icon_name: fox
WARNING: help item without icon_name: lynx
WARNING: help item without icon_name: marten
WARNING: help item without icon_name: moose
WARNING: help item without icon_name: reindeer
WARNING: help item without icon_name: sheep
WARNING: help item without icon_name: stag
WARNING: help item without icon_name: wildboar
WARNING: help item without icon_name: wisent
WARNING: help item without icon_name: wolf
```
Not sure if this is related to this branch?

**Comment by hessenfarmer** [comment]
I believe it is not related but a good possibility to fix this. Will do so tonight

**Review by Noordfrees — APPROVED** [review]
LGTM :)

**Pull request merged**
