### PR TITLE
Fix S2 map loader to load stones correctly

### PR DESCRIPTION
**Pull request by hessenfarmer**
I belive this was just a small typo that prevented Stones being present in S2 maps
probably fixes the issue reported on the forum
https://www.widelands.org/forum/topic/5100/

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
Could you also add another two `case` clauses for water and fish? According to the comments above those are also available in s2 maps but we don't seem to load them

**Comment by hessenfarmer** [comment]
> 
> 
> Could you also add another two `case` clauses for water and fish? According to the comments above those are also available in s2 maps but we don't seem to load them

I was thinking about this. However from the documentation I found for the s2 maps (link inside a comment of s2map.cc) fish and water are infinite in s2, so we would need to add default values for the amount. But this is what our map loader in the game does anyway so this info is only missing in the editor not in the map itself. If we set them to one default value this would override our terrain dependent default values in the game. So I am undecided about this. 
Furthermore I need to think about scaling the amopunt of ressources avaiulable in s2 (1-7) to our max ressopurce value, but there I am undecided as well. 
This would need some testing which I am planning to do tonight.

**Comment by Noordfrees** [comment]
> > Could you also add another two `case` clauses for water and fish? According to the comments above those are also available in s2 maps but we don't seem to load them
> 
> I was thinking about this. However from the documentation I found for the s2 maps (link inside a comment of s2map.cc) fish and water are infinite in s2, so we would need to add default values for the amount. But this is what our map loader in the game does anyway so this info is only missing in the editor not in the map itself. If we set them to one default value this would override our terrain dependent default values in the game. So I am undecided about this.

Good point, let's keep it as it is then. Please add a comment why we can ignore this info on loading though

> Furthermore I need to think about scaling the amopunt of ressources avaiulable in s2 (1-7) to our max ressopurce value, but there I am undecided as well.

That's already done below in line 747f (though it uses a hardcoded scaling factor instead of the ResourceDescr's max amount)

**Review by Noordfrees — APPROVED** [review]
LGTM (don't have an s2 map to test with)

**Comment by hessenfarmer** [comment]
tested it successfully so merging thanks for the review

**Pull request merged**
