### PR TITLE
Run vcpkg update step on ubuntu

### PR DESCRIPTION
**Pull request by matthiakl**
**Type of change**
Bugfix 

**Issue(s) closed**
Re #6184

**How it works**
Line ending issus with git on Windows, but this step does not depends on Window, so run it on Ubuntu

Test run here: https://github.com/widelands/widelands/actions/runs/6507596511

### CODE REVIEW

**Comment by matthiakl** [comment]
Well, actually I am not sure, whether this the line ending is the real problem. There was no change in the vcpkg version, so it was correct to not push it. It only rebuild the cache, which for some reason did not exist.

**Comment by tothxa** [comment]
> Well, actually I am not sure, whether this the line ending is the real problem. There was no change in the vcpkg version, so it was correct to not push it.

To me it looks like it's the problem for the failure instead of a clean exit with no commit. Without the `git` warning the push would have been skipped cleanly.

> It only rebuild the cache, which for some reason did not exist.

Indeed, that's strange. I haven't thought of that.

**Comment by matthiakl** [comment]
> Maybe this is another line ending issue?

I don't see it. The cache key creation in the vcpkg update workflow did not change and yet it decided to be different from the previous one.

**Comment by tothxa** [comment]
caches

I even copy-pasted the keys from the page to files and compared them, but they were identical. That's why I think there may be a line ending in one but not in the other, or something like that. But that's only a guess of course.

**Comment by tothxa** [comment]
I've also tried to look for the difference between the 2 workflows' definition of the cache key, and couldn't find how they could differ.

Also the github docs explicitly say that caches can be shared between workflows.

It's really strange.

**Comment by matthiakl** [comment]
This week the update was committed successfully, so I guess it was a runner issue…

**Comment by tothxa** [comment]
> This week the update was committed successfully, so I guess it was a runner issue…

It succeeded because there was a change to commit. The failure happens when there's nothing to commit.

**Comment by tothxa** [comment]
And the `build` workflow still doesn't find the saved cache:
https://github.com/widelands/widelands/actions/runs/6604457798/job/17938623222?pr=6197

**Comment by tothxa** [comment]
Seems to be a problem with the path? From the output of post-restore from the last run (https://github.com/widelands/widelands/actions/runs/6604717119/job/17939157181?pr=6197):

> Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.

**Comment by tothxa** [comment]
Sorry for messing with your branch, but it was easier this way.

**Comment by tothxa** [comment]
OK, I get it now. So we don't need ubuntu after all, because that step should be skipped completely when there are no changes. So all it takes is that backslash.

**Comment by matthiakl** [comment]
In the meantime, I updated my testing repo and it looks like switching to ubuntu indeed resolves not only the warning but also the cache key issue. Take a look at the runs at https://github.com/matthiakl/actions/actions

- The cache is not found: https://github.com/matthiakl/actions/actions/runs/6605503589/job/17940732697#step:4:13
- The ref file is committed from ubuntu: https://github.com/matthiakl/actions/actions/runs/6605539662/job/17940807024#step:3:15
- The cache is now found: https://github.com/matthiakl/actions/actions/runs/6605550557/job/17940824411#step:4:17

**Comment by matthiakl** [comment]
> OK, I get it now. So we don't need ubuntu after all, because that step should be skipped completely when there are no changes. So all it takes is that backslash.

But this does not resolve the issue, that subsequent builds do not find the cache, or does it?

**Pull request closed without merging**
