### PR TITLE
Fix snprintf error for Windows build

### PR DESCRIPTION
**Pull request by Adriankhl**
Related to https://github.com/widelands/widelands/issues/3372

Previously, the workaround is to patch the `libintl.h`. While it works, I think this could be dangerous to my local development environment since it could break other softwares.

Here, I propose that undefining `snprintf` is a better fix for the issue since it limits the modification to widelands only.

### CODE REVIEW

**Comment by hessenfarmer** [comment]
Did you check whether this does no harm to the usage of snprintf in other parts of the code? 
As the patch does not completely undefine snprintf but prefents redefinition to libintl_snprintf.

**Comment by Adriankhl** [comment]
@hessenfarmer As far as I know, without the `undef`, all `snprintf` in `src`  become `libintl_snprintf`, so basically the changes here are identical to the previous workaround.

**Comment by hessenfarmer** [comment]
the quetion was if the undef without redefinition of the normal snprintf would do any harm? But as it compiles properly and runs suficiently (although I did not test that much) this might be good to go. However it is the decision of Nordfrees whether this will be part of b21 or later

**Comment by Noordfrees** [comment]
Hi @Adriankhl and thank you for this fix :)

Since we can't be 100% sure that this has no side effects we should merge this after b21.

@hessenfarmer how much did you test this? `snprintf` is used by our code only in saving the MapPlayersViewPacket, can you please check whether this is working correctly?

**Comment by hessenfarmer** [comment]
ok played a while now and saved and reloaded as well. nothing happened so seems to work well

**Review by hessenfarmer — APPROVED** [review]

**Comment by gunchleoc** [comment]
>  `snprintf` is used by our code only in saving the MapPlayersViewPacket, can you please check whether this is working correctly?

I also found occurrences in

`std::string Md5Checksum::str()`

and in

`third_party/eris/luaconf.h`

**Pull request merged**
