### PR TITLE
quick fix for current appveyor problem

### PR DESCRIPTION
**Pull request by hessenfarmer**
commented broken repo out in mirrorlists

### CODE REVIEW

**Review by gunchleoc — DISMISSED** [review]
Let's have this as soon as AppVeyor goes green

**Comment by hessenfarmer** [comment]
first attempt on appveyor was not succesful. I can't test this previously. I always need to assume from my own msys2 installation. 
Is there a way to hold all other branches till we have this one ready? otherwise each other build takes six hours to fail, which means this would be ready probaly monday evening.

**Comment by Noordfrees** [comment]
You can login to appveyor with your github account and enable appveyor builds for your fork. Then you only need to copy this branch to your fork and edit the appveyor.yml to always build the branch on your personal contingent of free builds.

**Comment by hessenfarmer** [comment]
Thanks Nordfriese,
it seems to work properly see https://ci.appveyor.com/project/hessenfarmer/widelands/builds/31323893 so I'll PM @gunchleoc probably if the debug build succeeds

**Comment by TinoM** [comment]
@hessenfarmer i've cancelled all other builds in the queue...

**Review by gunchleoc — APPROVED** [review]
First 2 jobs are green, so feel free to merge without merging master into this branch once the build has finished :)

I have also cancelled some Travis builds to give this branch priority.

**Comment by hessenfarmer** [comment]
ok fix is working and in needs to be reverted when the msys2.org repo is online again.

**Comment by gunchleoc** [comment]
When we revert it, we should comment it out rather than delete the lines, so that we know what the fix is if this happens again in the future.

**Pull request merged**
