### PR TITLE
Update Asio to version 1.24.0 in download_asio.sh

### PR DESCRIPTION
**Pull request by tothxa**

### CODE REVIEW

**Comment by Noordfrees** [comment]
Has it been tested that multiplayer works fine with this version?
When yes we should have it for the release

**Comment by tothxa** [comment]
So far I only did a minimal test locally between a native build with asio-1.22.2 and flatpak build with asio-1.24.0. The latest package on flathub-beta is built with asio-1.24.0, so hopefully it will get some testing.

**Comment by hessenfarmer** [comment]
if required I would be available for a quick test tonight.

**Comment by tothxa** [comment]
I've just had a 2.5 hour long game with @hessenfarmer using a build with asio 1.24.0 without any problem. So I guess we can merge this?

**Review by Noordfrees — APPROVED** [review]

**Pull request merged**
