### PR TITLE
Send localized cheating messages

### PR DESCRIPTION
**Pull request by Noordfrees**
When one player plays in german and another in chinese they will probably appreciate seeing these messages in english as well

### CODE REVIEW

**Comment by gunchleoc** [comment]
How about sending it in English and translating on the client side?

**Comment by Noordfrees** [comment]
Do we already have any chat messages that behave like this? If not we'd have to implement this into the protocol to send the info that the message needs to be translated along with the message. Bit overkill IMHO, not to mention I'd have no idea where to program this.

**Comment by gunchleoc** [comment]
Take a look at `InternetGamingMessages` in networking.

**Comment by Noordfrees** [comment]
Done :)

**Comment by gunchleoc** [comment]
Error on server:

`[00:00:59.761 real] ERROR: GenericSaveHandler::save_file: data could not be written to file replays/2020-11-15T13.14.56_nethost.wrpl.wgf: basic_string::substr: __pos (which is 8) > this->size() (which is 2)
`

On client:

`[00:00:32.870 real] ERROR: GenericSaveHandler::save_file: data could not be written to file replays/2020-11-15T13.14.56_netclient_1.wrpl.wgf: basic_string::substr: __pos (which is 13) > this->size() (which is 6)`

**Comment by Noordfrees** [comment]
I cannot reproduce this. What did you do exactly?

**Comment by gunchleoc** [comment]
1. Compile debug build
2. create LAN game from map
3. run second Widelands instance from same directory
4. change language
5. join game on "localhost" start game

**Comment by Noordfrees** [comment]
No luck reproducing, and the resulting replays also load and run fine. Did you check that this does not happen for you on other branches?

**Comment by frankystone** [comment]
Forgot it, this was on master... :-D

**Comment by Niektory** [comment]
I also can't reproduce.

**Comment by matthiakl** [comment]
Is there an easy way to test the translation? I added the string to po/widelands/de.po and rebuild the locale dir, but it only shows the English version.

**Comment by Noordfrees** [comment]
You need to add it to `po/widelands/widelands.pot` as well, then it should work

**Review by matthiakl — APPROVED** [review]
> You need to add it to `po/widelands/widelands.pot` as well, then it should work

It does :). No complaints here.

**Comment by Noordfrees** [comment]
Thanks for the review :)

**Pull request merged**
