### PR TITLE
5485 alternate fix

### LINKED ISSUE #5485: Master fails to save File in multiplayer mode with unclear focus
**To Reproduce**

* Open attached File from the Muliplayer Menu and try to save it, after playing a few seconds.
* Notice: that it still still possible to select something during the attempted save.
* Notice that Network connection is lost after a while.
* After pressing Escape Game seems to continue in the Background
* Debug Output does not indicate any real attempt to save.
* Notice that Autosave works as expected.

**Expected behavior**

* Game is stopped during the save.
* No interaction with background possible during save.
* Game is saved in the End.

**Attachements**

[Save File and debug log](https://github.com/widelands/widelands/files/9248779/SaveGameBug.zip)
A Screencast can be found here: https://magentacloud.de/s/e7BHdHH2tgNLXLJ 

**Version:**
 - OS: macOS Monterey 12.5 (21G72)
 - CPU:  M1 ARM
 - Widelands Version: 1.1~git25829 (c58a8c6@master)

**Additional context**

* Is this a focus issue from the GUI? or is this just some side effect?
* I this a racecondition related to Multithreading?
* I case I should debug something please give me a hint where to start

### PR DESCRIPTION
**Pull request by hessenfarmer**
fixes #5485 
fix inspired by #5454

### CODE REVIEW

**Comment by Noordfrees** [comment]
The problem with this would be that the save dialog is kept open in case saving fails, and then it would no longer be modal. A modal panel is not meant to stay around after it stops being modal so this could cause lots of "fun" downstream.

**Comment by hessenfarmer** [comment]
I understand, but there are 3 things I don't understand: 
1. Why is the bug only limited to Multiplayer?
2. Why was it made modal in #5421? Wasn't this just a workaround? Can't this be solved alternativly. 
3. Why is the save in MP working if it is not modal and not working if it is modal?

**Comment by Noordfrees** [comment]
1. In MP, the logic thread sends a blocking `NoteThreadSafeFunction` to the main thread during *every* think() cycle. In SP, `NoteThreadSafeFunction`s (especially blocking ones) are used much more sparingly. Since saving is only possible between think cycles to ensure the saved game will be in a well-defined state, the current think cycle (if any) must complete before we can perform the save.
2. It was **not** made modal. It was made to *pretend* to be modal without *actually* being modal. That's what caused both #5453 and #5485.  
  The bug could probably have been solved without making this panel modal in any way; however a modal save dialog has other advantageous side effects; many games make their save dialogs modal, and it makes sense for us to do so too.
3. The reason why Widelands hangs is that we need to wait for the logic thread's `NoteThreadSafeFunction` to be processed before the save can take place. When the save game dialog is not modal, then the InteractiveBase (being the topmost modal panel) is responsible for that and does it just fine within a few milliseconds. When the save game dialog is fake-modal like in master, it and the IBase both think the other is responsible so neither ever actually does it.

**Comment by hessenfarmer** [comment]
Many thanks for the explanantions. that explains the fix in your branch as well.  I am still and ever will be learning.
In any case I agree about the advantages of having the save dialog modal.

**Pull request closed without merging**
