### PR TITLE
remove leftover individual animation frames of buildings

### PR DESCRIPTION
**Pull request by tothxa**

### CODE REVIEW

**Review by hessenfarmer — COMMENTED** [review]
these leftovers were left there intentionally as they are needed to solve #4985 

Edit: so we need to postpone this to after 1.1

**Comment by tothxa** [comment]
OK, sorry. I kind of remembered this, but couldn't locate the users.

**Comment by Noordfrees** [comment]
Is this ready for merging now?

**Comment by tothxa** [comment]
Yes, it was only left as draft until 1.1.

**Review by Noordfrees — APPROVED** [review]

**Pull request merged**
