### PR TITLE
Allow ware preciousness of 50 in AI hints.

### PR DESCRIPTION
**Pull request by gunchleoc**
Get rid of an warning we won't want to see in the release.

C.F: https://www.widelands.org/forum/topic/4232/?page=23#post-31779

### CODE REVIEW

**Comment by tibor95** [comment]
You should change also the text of log

**Comment by gunchleoc** [comment]
> You should change also the text of log

Oops - done!

**Review by Noordfrees — APPROVED** [review]

**Review by stonerl — APPROVED** [review]
LGTM :-)

**Comment by gunchleoc** [comment]
Can you guys stop merging master into this branch? It doesn't need it to be safe for merging, and it keeps cancelling the AppVeyor builds ;)

**Comment by hessenfarmer** [comment]
@gunchleoc for Nordfriese and me and maybe others all branches need to be safe for merging. So if we try to help getting things merged we need to merge master every time a commit happened there. This increased our Ci builds enormously of course. And doing the merge as soon as possible seemed to be the right strategy to skip useless (at least for us) builds as soon as possible

**Comment by gunchleoc** [comment]
AppVeyor failure is a timeout, so I'll merge this now.

**Comment by gunchleoc** [comment]
For me, it depends on what the changes are. For example, if there was just a translations update on master, there's no need to merge that in. Also, of the changes are very local as in this branch and other recent merges are also small and in a different area of the code. So, merging master 3x delayed merging this branch by a day or 2 rather than making it faster.

**Comment by hessenfarmer** [comment]
> For me, it depends on what the changes are. For example, if there was just a translations update on master, there's no need to merge that in. Also, of the changes are very local as in this branch and other recent merges are also small and in a different area of the code. So, merging master 3x delayed merging this branch by a day or 2 rather than making it faster.

I fully agree, however the project rights currently don't allow it otherwise for me or Nordfriese. So either we discuss the rights or we stop trying to merge anything and wait for you or stonerl.

**Comment by gunchleoc** [comment]
I'll be happy to make you guys admins if you want.

**Comment by hessenfarmer** [comment]
I would be ok with that but relaxing the rules to just have one succesful pair of builds if branch is still without conflicts could be a solution as well.

**Comment by gunchleoc** [comment]
Well, there is no such setting available, so I have made you admins. I think we're fine with 4 active admins.

One setting that I could change was not to automatically dismiss approvals when changes are pushed.

**Pull request merged**
