### PR TITLE
Add high resolution images for Atlantean buildings

### PR DESCRIPTION
**Pull request by tothxa**
See https://www.widelands.org/forum/topic/5485/
(pair of #5376)

Increased size of:
- castle and port
- guardhouse slightly

Rest is mostly kept the same, only unified the ones with the same base.

### CODE REVIEW

**Comment by tothxa** [comment]
Flag and frontier are coming soon.

@hessenfarmer Atl02 buildings will need to be updated when both PRs are merged.

**Comment by tothxa** [comment]
I created a new branch in my repo where I'll keep track of all hi-res PR branches for testing them together:
https://github.com/tothxa/widelands/tree/all_hi-res

**Comment by tothxa** [comment]
I've just re-checked these with the latest Empire adjustments in mind, but I think they're fine as they are. They are consistent with each other (comparing the small building parts) and with the other tribes as far as that's possible. So I don't plan any updates of my own.

**Comment by hessenfarmer** [comment]
will review them tonight

**Review by hessenfarmer — APPROVED** [review]
In the folder of the atlanteans tower there are some leftover images which don't belong there. Please cleanup.
Rest LGTM.

**Comment by hessenfarmer** [comment]
> @hessenfarmer Atl02 buildings will need to be updated when both PRs are merged.

I am aware however some of my images were fabricated by gimp and not by blender so it will be hard for me to make them scaled (namely atlanteans trading post and atlanteans_temple_of Satul)

**Comment by tothxa** [comment]
Clean up is done.

> > @hessenfarmer Atl02 buildings will need to be updated when both PRs are merged.
> 
> I am aware however some of my images were fabricated by gimp and not by blender so it will be hard for me to make them scaled (namely atlanteans trading post and atlanteans_temple_of Satul)

Temple is simple, it can be done with the high resolution renders too. Trading post should be done in blender to look good in high resolution though. I may give it a try.

**Comment by hessenfarmer** [comment]
> 
> Temple is simple, it can be done with the high resolution renders too. Trading post should be done in blender to look good in high resolution though. I may give it a try.         

@tothxa    
well, we need to have the same hotspot and proportions for all scales. Doing this manually is hard. Only Idea I have for a gimp workflow is to redo them with the 4 scale and after finishing this scale them down by 50 % 3 times.      
However if you couild mange to fabricate them in blender It would be easier to export all scales and change them if necesary. So any help would be very much appreciated. 
the temple is made of a guardhall in  front of the dungeon.  the trading post is made from a mine but ideally we would simply add the mine fence ad the higher mine tower to the scouts house keeping the position and hotspot of the house itself.

**Pull request merged**
