### PR TITLE
Improving building and dismantling mil. sites

### PR DESCRIPTION
**Pull request by tibor95**
Improving building and dismantling military sites
- creating future_military_loneliness
- modification of can_be_dismantled variable

For discussion, pls check if the behavior is improved. I can train again a bit and than we might merge

re #1083

### CODE REVIEW

**Comment by hessenfarmer** [comment]
Code looks reasonable. will test tomorrow.

**Comment by tibor95** [comment]
I will do some more training than and push results shortly after lunchtime

**Comment by tibor95** [comment]
OK. I pushed results of some training

**Review by hessenfarmer — APPROVED** [review]
this is definitly a big improvement.   
to see the effect I use a 4 AI, peaceful, endless game on full moon and watch the "clash zone".    
In master the AI is dismantling much to much buildings. While here it only happens in rare occasions (building finished but not manned), which leads to less territory losses.    
@Noordfrees may we have this although we already had feature freeze.

**Comment by hessenfarmer** [comment]
@tothxa as you reported the same bug recently I would like to hear your opinion as well wether this is an improvement as big as I believe it is

**Comment by tibor95** [comment]
I am still doing some training, for case it will be merged...

**Comment by hessenfarmer** [comment]
> I am still doing some training, for case it will be merged...

As @Noordfrees agreed to merge in v1.1 it we will merge when training is finished and @tothxa gave us his opinion. 
I would prefer this to be at the earliest opportunity as we should play all campaigns after AI code is finished.

**Comment by tothxa** [comment]
edit: Sorry, my mistake. I used `--datadir` forgetting about the `.wai` files.

edit2: Do I need to start a new game to get a clean AI state? Using my previous save ([atl02_map0608_see_all.wgf.zip](https://github.com/widelands/widelands/files/8874496/atl02_map0608_see_all.wgf.zip)) I still see strange dismantling and rebuilding behaviour.

~Running this with atl02 (taking advantage of #5447) I still see this:~

shot0003
shot0004

~Dangerous behaviour from the Empire too later, though not losing land this time:~

shot0006

~Then some spurious building and dismantling:~

shot0008

~In the first test the Empire also lost land when it dismantled its fortress, but I hadn't made screenshots of that one.~

**Comment by tibor95** [comment]
content of wai is stored in savegame, so no point changing them. And they themselves are not cardinal now.
New build of widelands should be enough to see the difference.

I can test your savegame, but just confirm you have new build...

**Comment by tothxa** [comment]
Yes, I tested with a release build of 1.1~git25780 (1bc8a10@ms_fix). For the second test I checked out `data/campaigns/atl02.wmf` from atlantean02 over it to be able to load the savegame.

**Comment by tothxa** [comment]
I re-ran the test, but this time there was less spurious dismantle and rebuild. The barbarians still dismantle the citadel and fortresses, losing much territory and several production sites, but this time the empire only built some medium sites to replace the fortress, and left it alone for a while. (Yesterday it kept building and dismantling fortresses.)  Later it expanded with a new fortress, then dismantled it when the military strength of the barbarians surpassed them. So the worse dismantles only happened when the respective player was weaker overall, so they can be interpreted as strategical retreat.

**Comment by hessenfarmer** [comment]
Well from what I saw in my usual test scenarios, the behaviour is not perfect but much better. First of all the AI does not dismantle due to constructionsites anymore, which caused much of the territory losses.     
 I will check atlantean 2 but this isn't a perfect example as there are many military sites in one region which still might be cosidered to be superfluous and dismanteled. we should probably extent the size bonus of big military buildings to the buildings at the front line as well, as it is currently only regarded in inner land decisions, to prevent more territory losses. 
In the current state dismantleing will stop after there are only a few buildings left at the border resulting in high enough military loneliness. 
From my perspective we should have this improvement now and keep the bug open to work on the issue a bit further in 1.2 
Still this is much better then current master I beleive

**Comment by tibor95** [comment]
I would also vote for merging this - AI improvement is endless task anyway... But I would still run some training. How much time can I have for it?

**Comment by tibor95** [comment]
So I would say that should_be_dismantled should be more sensitive to  enemy_owned_land_nearby, not only yes/no, but how many fields...
and unowned_land_nearby as well....

**Comment by tothxa** [comment]
I started a game of atl02 (with the `destruction_blocked` lines removed) with this branch and this time the Barbarians too kept one fortress at the border with the Empire. I didn't watch them closely this time, because I also tried to expand towards the Barbarians to see what they'd do at the border with me, but I didn't get to watch them much because their western border was soon cut off from the main territory by the Empire. But at least in this time they didn't dismantle the military sites near my border. So there is some improvement, but the test I tried to do was inconclusive.

**Comment by tibor95** [comment]
I just pushed some training.
I would make some further changes, but probably it is too late for the release. So it is up to you. To merge or not.

**Comment by hessenfarmer** [comment]
> I just pushed some training. I would make some further changes, but probably it is too late for the release. So it is up to you. To merge or not.

if you already have an idea what to change feel free to do so.

**Comment by tibor95** [comment]
I have an idea, and can prepare something in a week, but I would prefer to have this in master. If you think this change is improvement.

**Comment by hessenfarmer** [comment]
as this is definitly an improvement I'll merge this now.

**Pull request merged**
