### PR TITLE
Skip CI workflows where nothing changed

### LINKED ISSUE #6020: only trigger tests in workflow if something relevant has changed
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
Tests are also run if only a file changed which has nothing to do with the code
example: https://github.com/widelands/widelands/pull/6019

**Expected behavior**
I suggest to skip tests on obvious cases by using ...

either `paths` or `paths-ignore` for the entire workflow ([workflow-syntax-... on docs.github](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore))
or conditions for some jobs ([using-conditions-... on docs.github](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution))

**some (include) paths for ...**
compile and tests: src/, data/ (should we exclude some content?), test/, cmake/ (?), regression_test.py, (probably some more)
documentation: (is fast anyway) doc/, src/, data/scripting/, data/tribes/, data/world/, data/txts/

### PR DESCRIPTION
**Pull request by Noordfrees**
**Type of change**
CI enhancement

**Issue(s) closed**
Fixes #6020 & re #5880

**New behavior**
Skip CI checks where nothing relevant has been changed

**Additional context**
Patch by @SimonHeimberg at https://github.com/widelands/widelands/discussions/5880#discussioncomment-6476511

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
CI fails to start:
```
 Invalid workflow file: .github/workflows/build.yaml#L1
The workflow is not valid. .github/workflows/build.yaml: Anchors are not currently supported. Remove the anchor 'run_clang_tidy'
```

**Comment by SimonHeimberg** [comment]
> CI fails to start:
> ~~~
> The workflow is not valid. .github/workflows/build.yaml: Anchors are not currently supported.

Good to know that anchors are not supported. Yaml is not the same as Yaml...

**Comment by SimonHeimberg** [comment]
pr #6029 is on this pr. A pr to a pr is strange, but I can not push to this pr

**Comment by Noordfrees** [comment]
There are a few other paths that are relevant to some installers: `utils/macos/**` for MacOS builds and `utils/win32/**` for Windows builds. I don't know if anything else is also relevant, maybe `xdg` and `doc` are included in AppImages? This will need checking, or we could just include those just in case.

**Comment by Noordfrees** [comment]
I also wonder how this will integrate with our branch protection rules. We currently require all workflows to succeed (except for MSVC which breaks so often that I don't even bother re-adding it to the list anymore 😁), and if workflows are not started then the PR can only be completed via a force-merge by an administrator. But dropping the requirements isn't an option as that makes it far too easy to accidentally merge something that contains a critical regression mistaken for a transient error.

In the future all this will be handled more elegantly by [a new merge bot](https://codeberg.org/wl/GithubCodebergMirror) programmed by us, but that's still in alpha testing and deployment for the main repo is still some months off.

**Comment by SimonHeimberg** [comment]
> I also wonder how this will integrate with our branch protection rules. We currently require all workflows to succeed (except for MSVC which breaks so often that I don't even bother re-adding it to the list anymore grin), and if workflows are not started then the PR can only be completed via a force-merge by an administrator. But dropping the requirements isn't an option as that makes it far too easy to accidentally merge something that contains a critical regression mistaken for a transient error.
>
I have no idea how branch protection rules work. It depends what is checked exactly. The jobs do not fail, they are skipped, so it could work.
If it makes a mess like with the check results here, then it will be a problem.

Mess of check results:
- "Build / testsuite (pull_request)" Skipped reported as skipped
    but "testsuite (Debug, ubuntu-22.04, clang-14) " as expected
- "Build / Windows ${{ matrix.config }} ${{ matrix.arch }} Build (MSVC) (pull_request)" as skipped
    but "Windows Debug x64 Build (MinGW) " as expected
- ...

**Comment by SimonHeimberg** [comment]
> > I also wonder how this will integrate with our branch protection rules. We currently require all workflows to succeed ...
> > ...
> 
> I have no idea how branch protection rules work. It depends what is checked exactly. The jobs do not fail, they are skipped, so it could work. If it makes a mess like with the check results here, then it will be a problem.
> 
> Mess of check results:
> ...

This seems to be a known problem:
https://github.com/actions/runner/issues/952 => https://github.com/orgs/community/discussions/9141
listed work arounds are :grimacing:
- skipping each step of a matrix job
- dummy collector job (only depending on the matrix results, works because skipping normal jobs is considered as passed)

**Comment by SimonHeimberg** [comment]
Does the summary job do what it should? I am not sure and [asked in the discussion](https://github.com/orgs/community/discussions/9141#discussioncomment-6503352)

Cases I see:
- all jobs pass -> summary job passes :heavy_check_mark: 
- one job is skipped -> summary job is skipped :heavy_check_mark: 
- one test fails -> summary job is skipped :x: :question:

I might be wrong.

In case I am not, maybe like this:

```diff
   summary:
     name: CI Results Summary
     needs: [testsuite, windows, macos, appimage]  # We do not require MSVC due to frequent unrelated runner failures
+    if: always() # to check if dependencies have failed or passed
     runs-on: "ubuntu-latest"
     steps:
-    - name: Empty step
-      run: 'true'
+    - name: check job result
+      if: ! contains(needs.*.result, 'skipped') }}" = 'true' || contains(needs.*.result, 'failure') }}" = 'true' || contains(needs.*.result, 'cancelled') }}" = 'true')
+      run: |
+        if [ "${{ contains(needs.*.result, 'success') }}" <> 'true' ]
+        then
+          echo a job failed or was cancelled
+          exit 5
+        fi
```

idea: job summary fails if a job failed or was cancelled, skips if a job skipped => passes if all pass

**Comment by SimonHeimberg** [comment]
> > There are a few other paths that are relevant to some installers: `utils/macos/**` for MacOS builds and `utils/win32/**` for Windows builds. I don't know if anything else is also relevant, maybe `xdg` and `doc` are included in AppImages? This will need checking, or we could just include those just in case.
> 
> Checked and added those files in my pr smile

Maybe you could cherry pick my change 8f20e74f1d1abb93d929fc28f6f3b35bf07a638b from [my branch](SimonHeimberg/widelands/commits/5880-less-ci-noise)

Or shall I create another pr onto this pr? Or ...

**Comment by Noordfrees** [comment]
> Maybe you could cherry pick my change https://github.com/widelands/widelands/commit/8f20e74f1d1abb93d929fc28f6f3b35bf07a638b from [my branch](https://github.com/SimonHeimberg/widelands/commits/5880-less-ci-noise)

Already done :)

---

Would you mind if we skip the whole problem with GitHub's protection rules and instead just put this PR on hold until the new mergebot is ready for deployment? It's my firm intention to have it ready this year, ideally in autumn shortly after the v1.2 release. Even in its current state the bot should have no trouble with some checks being skipped. Adding fragile wrapping around something that is scheduled for replacement in a few months anyway seems unnecessary if it causes too much trouble.

**Comment by Noordfrees** [comment]
Now that the merge bot is in place (although not 100% there yet) and we no longer require specific status checks, this PR is ready for continuing

**Comment by hessenfarmer** [comment]
it seems like  the filter does not detect any changed files

**Comment by tothxa** [comment]
> it seems like the filter does not detect any changed files

I think the reason for that is what @matthiakl or @Noordfrees told me once: workflow runs for PRs don't actually use the PR branch directly, but merge it with master in a temporary branch instead, and use that. So there's indeed nothing to do here, because only the workflow yaml file is changed.

OTOH, the workflow file itself should also be watched, and if it changes, then all of its dependencies should be considered changed. So this PR should also split up build.yaml (long overdue anyway ;), so that future changes to a job would only require re-running that job, and the others could be skipped. The "root" yaml should only check changes and call the appropriate sub-workflows (each current job should become one). That way `codecheck` and `clang-tidy` wouldn't need the repeated conditions in every step either.

**Comment by SimonHeimberg** [comment]
> Does the summary job do what it should? I am not sure and [asked in the discussion](https://github.com/orgs/community/discussions/9141#discussioncomment-6503352)

There is an answer to the question I have asked. It links to https://github.com/orgs/community/discussions/26822#discussioncomment-3305794
It only depends on a single matrix job, so it does not match 1:1. But as I understand it, it confirms that on failure of a dependent job, the current code would skip the job.

**Comment by SimonHeimberg** [comment]
> > it seems like the filter does not detect any changed files
> 
> I think the reason for that is what @matthiakl or @Noordfrees told me once: workflow runs for PRs don't actually use the PR branch directly, but merge it with master in a temporary branch instead, and use that. So there's indeed nothing to do here, because only the workflow yaml file is changed.

It looks like you are right. The build output only reports one file as changed: https://github.com/widelands/widelands/actions/runs/6905988972/job/18789980447?pr=6028#step:3:19 , which must be the workflow yaml.

> 
> OTOH, the workflow file itself should also be watched, and if it changes, then everything should be considered changed. So this PR should also split up build.yaml (long overdue anyway ;), so that future changes to a job would only require re-running that job, and the others could be skipped. The "root" yaml should only check changes and call the appropriate sub-workflows (each current job should become one). That way `codecheck` and `clang-tidy` wouldn't need the repeated conditions in every step either.

Some splitting sounds sensible.

**Comment by SimonHeimberg** [comment]
Improved patch, following up https://github.com/widelands/widelands/pull/6028#issuecomment-1826412250

```patch
   summary:
     name: CI Results Summary
     needs: [testsuite, windows, macos, appimage]  # We do not require MSVC due to frequent unrelated runner failures
+    if: always() # to check if dependencies have failed or passed
     runs-on: "ubuntu-latest"
     steps:
-    - name: Empty step
-      run: 'true'
+    - name: check if any job failed
+      if: >-
+        contains(needs.*.result, 'failure') ||
+        contains(needs.*.result, 'cancelled')
+      run: |
+        echo a job failed or was cancelled
+        exit 5
+    - name: no step skipped # optional, just gives info
+      if: ! contains(needs.*.result, 'skipped')
+      run: true

**Comment by tothxa** [comment]
> I have added two commits to my branch [5880-less-ci-noise](https://github.com/SimonHeimberg/widelands/tree/5880-less-ci-noise) which split up some parts of build.yaml and reruns those jobs if the defining file changed. Is this like you suggested, @tothxa ?

Well, it's the beginning. :) (I haven't checked the changes logic, only what got split out)

w*ndows and mac builds should also get their own yaml file as well as all the quick checks, that can go together. (clang-tidy should be on its own IMO, like you already have it in your branch)

> Shall I create a new pr on this pr?

I think you should create a whole new PR, so that you can do your changes on your own.

**Comment by SimonHeimberg** [comment]
> > I have added two commits to my branch [5880-less-ci-noise](https://github.com/SimonHeimberg/widelands/tree/5880-less-ci-noise) which split up some parts of build.yaml and reruns those jobs if the defining file changed. Is this like you suggested, @tothxa ?
> 
> Well, it's the beginning. :) (I haven't checked the changes logic, only what got split out)
> 
I wanted to write it is a beginning. But "some parts" does not really tell this.
I wanted to know if I am going in the right direction before doing much. Now I do.

> w*ndows and mac builds should also get their own yaml file as well as all the quick checks, that can go together. (clang-tidy should be on its own IMO, like you already have it in your branch)
> 
> _edit: msvc and mingw should also be in separate yaml files, so e.g. after vcpkg updates only the msvc job would run, nothing else._
> 
vcpkg is not yet listed. Thanks for the hint.

> > Shall I create a new pr on this pr?
> 
> I think you should create a whole new PR, so that you can do your changes on your own.

I started one (https://github.com/widelands/widelands/pull/6257)  and will set its target branch correctly soon.

**Comment by SimonHeimberg** [comment]
> w*ndows and mac builds should also get their own yaml file as well as all the quick checks, that can go together. (clang-tidy should be on its own IMO, like you already have it in your branch)
> 
Having several jobs in a reusable workflow seems not to work (I reported it at https://github.com/github/docs/issues/30296 , find a link to my try there.)

**Comment by SimonHeimberg** [comment]
You can see several runs of build.yaml with the results:
- https://github.com/widelands/widelands/actions/runs/7063942797
- https://github.com/SimonHeimberg/widelands/actions/runs/7068833567
- https://github.com/SimonHeimberg/widelands/actions/runs/7069358998

(I made some pr to my branch to trigger partial runs. I wanted to see skipping, and it should finish quicker.)

**Comment by tothxa** [comment]
@cb/Nordfriese Can we close this as superseded by #6257 or will that confuse bunnybot even more? I see it wanted to close #6257 a second time...

**Pull request closed without merging**
