### PR TITLE
Ferry

### PR DESCRIPTION
**Pull request by Noordfrees**

### CODE REVIEW

**Comment by stonerl** [comment]
@klaus-halfmann why are you closing this PR?

**Comment by klaus-halfmann** [comment]
I did no intent to close this one, I pushed some branch `refactor_gamehost` with
`git push origin` and to my suprise this affected other branches. Sorry this was my first
push using git.

**Comment by stonerl** [comment]
@Noordfrees could you rebase to master? There are some conflicts and I don't want to tinker with your code.

**Comment by stonerl** [comment]
@Noordfrees what is the status here? Are done? Do you we need packages so people can test play and report possible bugs? BTW I ran fix_formatting.py so you should pull the branch.

**Comment by stonerl** [comment]
Fails to build with the follwoing error:
```bash
[ 95%] Building CXX object src/economy/CMakeFiles/economy.dir/ware_instance.cc.o

/Users/travis/build/widelands/widelands/src/economy/ship_

:6: error: use of undeclared identifier 'Fleet'

bool Fleet::penalize_route(Game& game, PortDock& p, const Ship& s, uint32_t* route_length) {

     ^

/Users/travis/build/widelands/widelands/src/economy/ship_

:25: error: 'destination_dock_' is a private member of 'Widelands::ShippingItem'

                if (PortDock* pd = it.destination_dock_.get(game)) {

                                      ^

/Users/travis/build/widelands/widelands/src/economy/shippingitem.h:86:17: note: declared private here

        OPtr<PortDock> destination_dock_;

                       ^

2 errors generated.

make[2]: *** [src/economy/CMakeFiles/economy.dir/ship_fleet.cc.o] Error 1

[ 95%] Building CXX object src/economy/CMakeFiles/economy.dir/input_queue.cc.o

[ 95%] Building CXX object src/economy/CMakeFiles/economy.dir/wares_queue.cc.o

[ 95%] Building CXX object src/economy/CMakeFiles/economy.dir/waterway.cc.o

[ 95%] Building CXX object src/economy/CMakeFiles/economy.dir/workers_queue.cc.o

make[2]: Target `src/economy/CMakeFiles/economy.dir/build' not remade because of errors.

make[1]: *** [src/economy/CMakeFiles/economy.dir/all] Error 2

make[1]: Target `all' not remade because of errors.

make: *** [all] Error 2

make: Target `default_target' not remade because of errors
```

**Comment by Noordfrees** [comment]
Thanks for the sphinx fix. compile error should be fixed now.
This branch was already tested quite extensively so there are most likely no more critical bugs. IMHO it can be merged as soon as travis is happy.

**Comment by Noordfrees** [comment]
This is really quite ready for merging now ;)

**Review by stonerl — CHANGES_REQUESTED** [review]
Found a bug. When a Ferry Yard is placed on land without any contact to water the Ferry Yard consumes log without actually producing ferries.

**Comment by stonerl** [comment]
3 more quirks:
* When the Ferry Yard isn't placed close to water, the tooltip says **"Can't find anymore Resources"**. This is misleading since it isn't explained what Resources are needed. A Player could assume logs are meant. The Shipyard on the other hand doesn't show a message in this case. I'd say we handle it like we do with the Shipyard and don't show a tooltip, since it is imperative to place the Ferry Yard next to water.

* The red ❌ for **"Destroy a Waterway"** looks completely different, from the **"Destroy a road"** please harmonize it to make it look like the one on the road button.

* **"Destroy a Waterway"** is written with a capital **W** should be a lowercase **w** though.

**Comment by stonerl** [comment]
Oh, and please have a look at PR #3566. I think we should move all buildings, that are only displayed when seafaring and/or ferries are allowed, to the end of the building list. Otherwise, the buildings that follow such buildings are always in a different spot.

**Comment by Noordfrees** [comment]
Implemented your comments.
> When the Ferry Yard isn't placed close to water, the tooltip says "Can't find anymore Resources".

I don´t know how to fix this one though. The shipyard has a specialized C++ function for the special "object-or-coords" program that seems to circumvent the tooltip but is not applicable here. The out-of-resources-tooltip is created automatically by C++, I don´t see how it could be suppressed…

**Comment by stonerl** [comment]
Found another glitch, when auto-roadbuild-mode is enabled. Instead of starting road building, the Action Windows for Flags is opened, when the building's flag is on an intersection were also a waterway could be built.

**Comment by Noordfrees** [comment]
> Found another glitch, when auto-roadbuild-mode is enabled. Instead of starting road building, the Action Windows for Flags is opened, when the building's flag is on an intersection were also a waterway could be built.

That´s intentional, because there is no telling whether you want to build a road or a waterway now, so you´re given a one-click choice. If you´d be set into roadbuild mode it would take you four clicks to start building a waterway, which can be annoying.

**Comment by stonerl** [comment]
> > Found another glitch, when auto-roadbuild-mode is enabled. Instead of starting road building, the Action Windows for Flags is opened, when the building's flag is on an intersection were also a waterway could be built.
> 
> That´s intentional, because there is no telling whether you want to build a road or a waterway now, so you´re given a one-click choice. If you´d be set into roadbuild mode it would take you four clicks to start building a waterway, which can be annoying.

Hmm, I do have to object here. This totally changes the auto-roadbuild behavior. When this is enabled, expected behavior is to automatically start the road building. Making this dependent on the ground it is built on is quite inconsistent UI design.

I could understand giving a choice when only a flag is placed, but when a building is placed instead, it needs to be connected via a normal road. If not, no worker will be able to erect it. So, I see no real value in giving the user a choice her (besides the fact, that is inconsistent UI design).

**Comment by frankystone** [comment]
> > > Found another glitch, when auto-roadbuild-mode is enabled. Instead of starting road building, the Action Windows for Flags is opened, when the building's flag is on an intersection were also a waterway could be built.
> > 
> > 
> > That´s intentional, because there is no telling whether you want to build a road or a waterway now, so you´re given a one-click choice. If you´d be set into roadbuild mode it would take you four clicks to start building a waterway, which can be annoying.
> 
> Hmm, I do have to object here. This totally changes the auto-roadbuild behavior. When this is enabled, expected behavior is to automatically start the road building. Making this dependent on the ground it is built on is quite inconsistent UI design.
> 
> I could understand giving a choice when only a flag is placed, but when a building is placed instead, it needs to be connected via a normal road. If not, no worker will be able to erect it. So, I see no real value in giving the user a choice her (besides the fact, that is inconsistent UI design).

I think this is not a matter of UI design, it's a matter of habit. Forcing a user to make four clicks to start building a waterway is not user friendly.

But i have to admit that i didn't have  a branch to test, so i want to ask: If Autoroadbuilding is enabled and one places a building whose flag is at NOT at the coastline, does auto roadbuilding work?

If yes i think its very unlikely that this happens (placing a building whose flag is at a coastline).

**Comment by stonerl** [comment]
> > > > Found another glitch, when auto-roadbuild-mode is enabled. Instead of starting road building, the Action Windows for Flags is opened, when the building's flag is on an intersection were also a waterway could be built.
> > > 
> > > 
> > > That´s intentional, because there is no telling whether you want to build a road or a waterway now, so you´re given a one-click choice. If you´d be set into roadbuild mode it would take you four clicks to start building a waterway, which can be annoying.
> > 
> > 
> > Hmm, I do have to object here. This totally changes the auto-roadbuild behavior. When this is enabled, expected behavior is to automatically start the road building. Making this dependent on the ground it is built on is quite inconsistent UI design.
> > I could understand giving a choice when only a flag is placed, but when a building is placed instead, it needs to be connected via a normal road. If not, no worker will be able to erect it. So, I see no real value in giving the user a choice her (besides the fact, that is inconsistent UI design).
> 
> I think this is not a matter of UI design, it's a matter of habit. Forcing a user to make four clicks to start building a waterway is not user friendly.
> 

As I said, for flags only I don't see a problem. But for buildings it is imperative to connect via a road to the economy, otherwise no workers will arrive. I, don't play with auto-roadbuild enabled. So for me it doesn't matter. But we change the auto-roadbuild mode in way the user doesn't expect. Also, I'd argue that roads are more important than waterways. G

> But i have to admit that i didn't have a branch to test, so i want to ask: If Autoroadbuilding is enabled and one places a building whose flag is at NOT at the coastline, does auto roadbuilding work?
> 

Yes, it does.

> If yes i think its very unlikely that this happens (placing a building whose flag is at a coastline).

It is very likely for example on the map Fellowships on the blue starting position.

**Comment by stonerl** [comment]
@Noordfrees would it be possible to add the build waterway button to the aboard window?

Here is how I would imagine it.

1. Build a building on the coastline.
2. Auto-roadbuild mode starts.
3. Clicking on the flag starts the Action window.
4. The Action Windows does Contain the "Cancel road" button & Build waterway.
5. Clicking on Build waterway stops road build and starts waterway building.

We now would have the old behavior and only 2 clicks are needed.

**Comment by frankystone** [comment]
> As I said, for flags only I don't see a problem. But for buildings it is imperative to connect via a road to the economy, otherwise no workers will arrive. 

One has to make one more click to build a road then.

> I, don't play with auto-roadbuild enabled. So for me it doesn't matter. But we change the auto-roadbuild mode in way the user doesn't expect.

This is only true for the case 'place building whose flag is at coast'

> Also, I'd argue that roads are more important than waterways. G

Yes, that's true.

I would say: lets leave it as is and wait for some players response :-)

Edit: Also to just have this branch in. Nordfrees had worked so much on this feature, and he is waiting for month for review and merging.

**Comment by stonerl** [comment]
Here are some mock ups:

Normal Window:
normal

Clicking on the Flag when in road build to change to waterway build:
road-to-water

Clicking on the Flag when in waterway build to change to road build:
water-to-road

**Comment by hessenfarmer** [comment]
ok just my 2 cents.
tested it with default target quantity and a return=skipped command in the ferry yard.  
with any value higher than 0 it will produce endlessly. If there would be a way to count the idle ferries and add them to users economy one could control the number of ferries as we could control second carriers.  if they get removed after 10 min another ferry will be produced. But if they can be controlled via economy setings I don't see the need for them to rot down.
For the road building mode this is very annoying especially on archipielago sea, cause you can't adapt to the different behaviours. For years I have adapted the clicking pattern place building, press control, build road. Now this works and sometimes not. So i tried to adapt to the new interface and place building, move mouse right to hit road button, press STRg and build road. but this also didn't work and confused me totally. I even didN't notice the reason for that.    
Conclusion I'd vote for consitent behaviour in place building mode either way round so as waterways are only available we should keep the legacy behaviour.    
@ nordfrees: is there a way to get the old behaviour in with low effort? and is there a way to count unused ferries in users fleets to add them to stocklevel
Edit: I agree to have this branch asap as Nordfrees put so much work in it.

**Comment by Noordfrees** [comment]
There is no way of adding ferries to economies. If you build two waterways between unconnected flags on an ocean, you´ll get two economies that are served by the same ferry fleet. 

I´ll reimplement the old behaviour that placing a flag if autoroadbuild is enabled directly starts building a road, and if a waterway can be built from the start flag a "cancel and build waterway" button is added to the cancel-roadbuilding window. (and for consistency the cancel-buildwaterway window will contain a cancel-and-start-roadbuilding button)

**Comment by stonerl** [comment]
@Nordfrees thanks allot for your work

**Review by stonerl — APPROVED** [review]
Perfect. 
BTW. I ran fix_formatting.py and pushed it to this branch.

**Comment by hessenfarmer** [comment]
Thanks Nordfrees for this great work.
However; if we have this now without all the proper graphics we shoulod open a bug to provide all of them before r21 otherwise we would have to revert all these changes before releasing.    
for the style I still would prefer rowboats with the typical ship hull of the tribe in small scale.

**Comment by stonerl** [comment]
@hessenfarmer I'll second this. Let's have this branch and open a new bug report for the missing graphics, targeted for build 21.

**Comment by stonerl** [comment]
I opened a followup issue #3608. So, if nobody objects I'd merge this branch.

**Comment by hessenfarmer** [comment]
from my point of view all issues have been adressed sufficiently for the moment being so if you want to merge feel free.

**Comment by Noordfrees** [comment]
Thanks :)

**Comment by gunchleoc** [comment]
Thank you for this big feature :)

**Pull request merged**
