### PR TITLE
Spritesheets fixes and cleanups

### LINKED ISSUE #3581: improve installing and loading of the game
**Is your feature request related to a problem? Please describe.**
On my old machine i still have a mechanical HDD during install and loading the tribes this consumes a lot of time to load or save the thousands of tribes graphic files. 

**Describe the solution you'd like**
The install and loading time should be improved by just saving compressed folders to the HDD and decompress them at loadtime. should be combined with the feature to only load the tribes needed.

### LINKED ISSUE #4985: #4935 broke savegame compatibility for sceanrios using scenario specific buildings
As the Lua files in the savegame are still refering to animations that aren't there anymore (they used the animation files of the normal buildings) of the   savegame compatibility is broken for Empire 4, Frisians 2 and 3

### PR DESCRIPTION
**Pull request by hessenfarmer**
fixes #4985
fixes #3581

- converted remaining file animations to spritesheets
- added spritesheet graphics to scenario specific buildings
- readded file animation graphics to the buildings where V1.0 scenario buildings had a link to for savegame compatibility

### CODE REVIEW

**Comment by Noordfrees** [comment]
In the RST comments ideally both `animations` and `spritesheets` should be mentioned. perhaps with a link to https://www.widelands.org/documentation/animations/ to explain.

---

Loading an existing savegame fails in b109a35933ca38ccd3a7b0c7dfd54560aff02df9(Release):
```
[00:00:09.611 real] ERROR: ##############################
[00:00:09.611 real] ERROR:   FATAL EXCEPTION: player info: Error while loading tribe 'barbarians': [../src/scripting/lua_errors.cc:22] tribe barbarians: Failed adding worker 'barbarians_soldier': [../src/scripting/lua_errors.cc:22] Error loading animation 'atk_fail_1_e' for map object 'barbarians_soldier': Animation in directory 'tribes/workers/barbarians/soldier/' with basename 'atk_fail_1_e' has no images for mandatory scale '1' in mipmap - supported scales are: 0.5, 1, 2, 4
[00:00:09.611 real] ERROR: stack traceback:
[00:00:09.611 real] ERROR: 	[string "tribes/workers/barbarians/soldier/init.lua"]:104
[00:00:09.611 real] ERROR: ##############################
```

EDIT: There are leftover references to `animations = animations` in files that no longer define this variable. In this case `animations` is some random global variable that may corrupt the unit definition with random garbage from a previously loaded unit.

**Comment by hessenfarmer** [comment]
hope I found all instances of the documentation
I just realized I need to do the second part of the #4985 fix

**Comment by hessenfarmer** [comment]
ok should be good to go now. I fixed an error in textdomain pushing in  fri 03 as well.

**Comment by hessenfarmer** [comment]
for whatever reason the testsuite is stalling. I believe after the last round the loading is much quicker and this affects somehow the testsuite. I am not sure whether the safeguard in stable_save.lua regarding the fps is not working anymore after the multithread incorporation. Anyhow I don't know how to fix this.

**Comment by hessenfarmer** [comment]
@Noordfrees
I believe I had changed all file animations to spritesheets where applicable, except frisian soldiers. reason for sparing them is that I hoped you still have the blender for them and you could make them in the different scales rather then having only scale 1 spritesheets. If this is the case please feel free to commit them to this branch or add a new one.

**Comment by Noordfrees** [comment]
Unfortunately I don't have the blender files. I might redo them some time in the future but currently I have little time for blender work :(

**Comment by hessenfarmer** [comment]
in this case I will convert the exisitng files

**Comment by tothxa** [comment]
> Unfortunately I don't have the blender files. I might redo them some time in the future but currently I have little time for blender work :(

What's the status of the models in https://bazaar.launchpad.net/~widelands-media-dev/widelands-media/widelands-media/files?

**Comment by Noordfrees** [comment]
> > Unfortunately I don't have the blender files. I might redo them some time in the future but currently I have little time for blender work :(
> 
> What's the status of the models in [bazaar.launchpad.net/~widelands-media-dev/widelands-media/widelands-media/files](https://bazaar.launchpad.net/~widelands-media-dev/widelands-media/widelands-media/files)?

That's an outdated version of the soldier. I redid them later with four sets of level-specific animations and forgot to commit the new blender sources. Later I reinstalled the operating system, no backups since surely everything is on Launchpad…

**Comment by hessenfarmer** [comment]
ok finished the task. This shopuld give us a big improvement in loading times.

**Comment by Noordfrees** [comment]
Thanks for doing this huge task :)

**Pull request merged**
