### PR TITLE
Add proper menu icons

### PR DESCRIPTION
**Pull request by stonerl**
Proper menu icons for:
* Sound Options
* Zoom Increase
* Zoom Decrease
* Gamespeed

### CODE REVIEW

**Comment by stonerl** [comment]
Here are some images:
shot0000
shot0001
shot0002
shot0003

**Comment by stonerl** [comment]
Some new images:
shot0014
shot0017
shot0015
shot0016

**Review by Noordfrees — COMMENTED** [review]
The zoom icons and the clock look nice.
The '>' and sound buttons have pretty harsh pixelated black lines, please try to blur them a bit.
For the '||', '>>' and '<<' buttons, could you make the yellow a bit darker near the edges?

**Comment by stonerl** [comment]
I added a tint of dark yellow to the edges and blurred it. @Noordfrees could you have a look, again?

**Review by Noordfrees — APPROVED** [review]
Beautiful :)

**Pull request merged**
