### PR TITLE
Norwegian Bokmål translation

### PR DESCRIPTION
**Pull request by perhenk**
Hi, I have done some Norwegian translation when complling and playing the game. I think the translation will be more accurate then. If its ok to translate trough git and po files I can do some more. 

I love the old Settlers II game and hope I can contribute some more on the code in the future.  :)

### CODE REVIEW

**Review by klaus-halfmann — COMMENTED** [review]
Hello Per-Henrik,

thanks for your contribution. You can find our translation guide here:
https://www.widelands.org/wiki/TranslatingWidelands/  

We normally do our translation via transifex and @gunchleoc  will , 
after a code freeze, ask our translators to add the missing translations.
Then they are mreged into the main code base.

Of course its a very good idea to check the translations _in game_.
However we may get git conflicts when Gun will do her next merge.

Please wait until she arrives back and can tell us how to proceed.
Meanwhile you may take a look at transifex and find more hints there.

Until then feel free to continue your work and have fun playing and contributing to widelands.

**Comment by gunchleoc** [comment]
@perhenrik90 Our translation setup will overwrite anything translated on GitHub with the Transifex version.

I have manually uploaded your file to Transifex so we don't lose your work. I recommend translating via Transifex in the future.

How do you wish to be credited: real name /nick name or both?

**Comment by perhenk** [comment]
Thank you! Then I will use the Transifex service in the future. 

I think the nick perhenrik90 would be fine!

**Comment by gunchleoc** [comment]
Done!

You'll appear on the list the next time that I pull the translations fro Transifex.

**Pull request closed without merging**
