### PR TITLE
Regression test reports clearer (part1)

### PR DESCRIPTION
**Pull request by SimonHeimberg**
**Type of change**
Enhancement of test suite

**Issue(s) closed**
Fixes -

**Old behavior**
The test suite runs regression_test.py, which prints a lot on failure.

**New behavior**
regression_test.py marks some output to make it easier to find important information.
It reports some problems clearer.

**How it works**
Lines of the output are marked on github with `::warning file=xxx ...::` and similar github commands. This highlights them in the log and marks them in the diff of the file.
Lines of the output are marked with colour in terminal. (This you can try out locally.)

**Possible regressions**
No known

**Screenshots**
The results of the test run with some marks are visible soon. (After the tests have run.) -- My bad, there are only marks on failure. And there is none, as expected. -- preparing a demo, see in comments

### CODE REVIEW

**Comment by SimonHeimberg** [comment]
The results of this test run shows nothing special because there are only marks on failure. And there is none, as expected. a demo with one failure (is running currently):
https://github.com/SimonHeimberg/widelands/pull/9

**Comment by tothxa** [comment]
Looks nice. Will the output of each failed test be collapsible separately? (Could you please make a demo run with multiple failuers?)

There's one more thing I miss: Please add to the end of the log a list with only the names of the failed tests if there are any.

**Comment by SimonHeimberg** [comment]
> Looks nice. Will the output of each failed test be collapsible separately? (Could you please make a demo run with multiple failuers?)
> 
Yes, each one is collapsed separately.

> There's one more thing I miss: Please add to the end of the log a list with only the names of the failed tests if there are any.

Interesting idea. Will do.

There is much more I miss. I have two follow up pr prepared. (I planed several pr because else code reiview gets unhandy.) Shall I include your Idea in a later pr?

**Comment by SimonHeimberg** [comment]
> > Looks nice. Will the output of each failed test be collapsible separately? (Could you please make a demo run with multiple failuers?)
> 
> Yes, each one is collapsed separately.
> 
see soon in https://github.com/SimonHeimberg/widelands/actions/runs/7527495787/job/20487833812?pr=9

> > There's one more thing I miss: Please add to the end of the log a list with only the names of the failed tests if there are any.
> 
> Interesting idea. Will do.
> 
> There is much more I miss. I have two follow up pr prepared. (I planed several pr because else code reiview gets unhandy.) Shall I include your Idea in a later pr?

It is in this pr.

**Pull request closed without merging**
