### PR TITLE
Ensure utils directory works with Python3

### PR DESCRIPTION
**Pull request by gunchleoc**
Linux distributions are phasing out Python3, so I have forced it on my system and got the utils running again.

* Linted the updated tools with pylint and flake8.
* Fix repetition of copyright year in license headers
* Update run-clang-tidy.py to version https://github.com/llvm-mirror/clang-tools-extra/commit/1c8cadde7ea4ca20a449edcffe10d23b612fe5d6
* Suppress new/smarter clang-tidy checks that aren't cleared yet
* Glossary checks can handle deleted locales
* Smarter detection of Hunspell locales
* Delete obsolete crop_animation tool

### CODE REVIEW

**Comment by frankystone** [comment]
`run_clang_tidy.py` works here with python 3.9.1. But the result of `utils/check_clang_tidy_results.py clang-tidy.log` is:

~~~~
###   Found 33037 error(s)                               ###
~~~~

where all are of kind: 

~~~~
warning: 'operator()' must resolve to a function declared within the '__llvm_libc' namespace [llvmlibc-callee-namespace]
~~~~

[clang-tidy.log zipped](https://github.com/widelands/widelands/files/6018288/clang-tidy.zip)

**Comment by Noordfrees** [comment]
We probably just need to add `llvmlibc-callee-namespace` to the `SUPPRESSED_CHECKS` list in `utils/check_clang_tidy_results.py` to fix that one.

The GitHub action always fails with 
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../utils/run-clang-tidy.py", line 218, in run_tidy
    '\n' + output.decode('utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 78126: ordinal not in range(128)```
Any idea how to resolve this?

**Comment by frankystone** [comment]
Probably the github action fails because it uses python version 2.7, afaik. The action(s) has to be adjusted to use python 3.x if this get merged.

It would also be good to have a version check inside the `.py` files.

**Comment by frankystone** [comment]
I wonder how long it will take on github server. Here it lasts 2 hrs, i had to restrict the cores to use only two though, otherwise my processor would be too hot.

**Comment by frankystone** [comment]
I can't test the `generate_glossary.py` and `glossary_checks.py` because i have no transifex account. Didn't testet `update_copyright.py` either.

**Comment by Noordfrees** [comment]
Will test that

**Comment by Noordfrees** [comment]
```
$ ./generate_glossary.py ../../widelands-translation-reports/Widelands.csv ../../widelands-translation-reports/glossary
Generating glossary:
Current time: Mon Feb 22 12:12:13 2021
Locale: all
Processing locale: ar
Something went wrong:
Traceback (most recent call last):
  File "./generate_glossary.py", line 313, in main
    po_dir, output_path, input_glossary, output_glossary, locale)
  File "./generate_glossary.py", line 203, in generate_glossary
    poterminology_result = subprocess.run(
AttributeError: 'module' object has no attribute 'run'
```

**Comment by frankystone** [comment]
Are you running the files with python3? The run() function was added in Python 3.5

**Comment by Noordfrees** [comment]
Explicitly using `python3` fixes it, now both glossary utils are running well. The copyright updater also works fine. 

@hessenfarmer FYI the german glossary check gave these 1405 hits: [glossary_check.csv.txt](https://github.com/widelands/widelands/files/6023655/glossary_check.csv.txt)

**Review by frankystone — APPROVED** [review]
I think all is fine here.

I would replace the old style %-formatting for the print function and use the `with-statement` for file handling operations. But this can be done later.

**Pull request merged**
