### PR TITLE
Fix travis MacOS builds

### PR DESCRIPTION
**Pull request by Noordfrees**
On Travis MacOS, gettext needs to be added to the PATH and some CMake CXX and linker flags have to be set because brew force-linking is no longer allowed for whatever reason

### CODE REVIEW

**Comment by Noordfrees** [comment]
This PR seems to fix the travis mac errors. I'd appreciate it if someone could take a quick look at the changes (especially as there are a lot of new (?) compiler warnings in the log), but since it's an urgent travis-only change I'll merge this even without review this evening if all mac checks on travis are green.

**Comment by Noordfrees** [comment]
Travis is green except for the GCC, so this should be merged ASAP.

**Review by tppq — APPROVED** [review]
I do not see any problems here.

**Comment by Noordfrees** [comment]
Thanks for the review :)

**Pull request merged**
