### PR TITLE
Don't add a dismantle button when no wares will be returned

### LINKED ISSUE #3785: Conquered milsites without dismantling returns can be dismantled
**Describe the bug**
When dismantling a militarysite conquered from another tribe, the dismantling returns only the wares used by the own tribe. This can lead to buildings having an empty return-on-dismantle list for the conquering tribe.

**To Reproduce**
1. Play as non-barbarians against a barbarian enemy
2. Conquer a barbarian sentry
3. Dismantle it
4. A builder will come to dismantle the site, and you will gain – zero wares!

**Expected behavior**
If you don't get any (useful) wares back by dismantling, don't show a dismantle button.

### PR DESCRIPTION
**Pull request by Noordfrees**
Fixes #3785

### CODE REVIEW

**Review by gunchleoc — APPROVED** [review]

**Comment by hessenfarmer** [comment]
this change will need a string change in Empire 4 scenario

**Comment by gunchleoc** [comment]
@hessenfarmer Do you want to do that before we merge? The branch is in this repo, so you can work on it without forking.

**Comment by hessenfarmer** [comment]
Okay,
will pull it and do the change. Might take until tomorrow evening though

**Comment by gunchleoc** [comment]
Thanks! There's no rush.

**Comment by hessenfarmer** [comment]
ok done

**Comment by gunchleoc** [comment]
Thanks!

**Pull request merged**
