### PR TITLE
Define enhancement cost in base building

### LINKED ISSUE #2110: Define enhancement costs in the base building
At the moment, which enhanced building a base building can be enhanced to is defined in the base building, and the enhancement cost in the enhanced building.

This should all be consolidated into a single Lua table in the base building including the name of the enhanced building, the enhancement costs and the wares returned when the enhanced building is dismantled.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2018-08-08T10:07:54Z
 * owner: gunchleoc
 * the launchpad url was https://bugs.launchpad.net/bugs/1786010

### PR DESCRIPTION
**Pull request by gunchleoc**
I have playtested the Empire scenario, so that won't need testing again for this review.

Closes #2110

### CODE REVIEW

**Review by hessenfarmer — APPROVED** [review]
Code LGTM.
not tested.

to avoid misunderstandings (distinguish this from the original buildcost) and better readability I would have kept the terms enhancement_cost and return_on_enhanced though

**Comment by gunchleoc** [comment]
@Noordfrees @frankystone  @MarkMcWire Which version would you find more readable inside the `enhancement` table,  `buildcost` and `return_on_dismantle` or `enhancement_cost` and `return_on_enhanced`?

**Comment by frankystone** [comment]
"enhancement_cost and return_on_enhanced" if those identifiers are used in lua, e.g. to get the corresponding costs by scripting.

Outside lua scripting: I have no clue...

**Comment by gunchleoc** [comment]
Good point about the scripting. In master, we have:

| Definition | Scripting |
| --- | --- |
| buildcost | buildcost |
| enhancement_cost | enhancement_cost |
| return_on_dismantle | returned_wares |
| return_on_dismantle_on_enhanced | returned_wares_enhanced |

This branch:

| Definition | Scripting |
| --- | --- |
| buildcost | buildcost |
| enhancement -> buildcost | enhancement_cost |
| return_on_dismantle | returned_wares |
| enhancement -> return_on_dismantle | returned_wares_enhanced |

How about:

| Definition | Scripting |
| --- | --- |
| buildcost | buildcost |
| enhancement -> buildcost | enhancement_buildcost |
| return_on_dismantle | returns_on_dismantle |
| enhancement -> return_on_dismantle | enhancement_returns_on_dismantle |

**Comment by hessenfarmer** [comment]
> 
> 
> Good point about the scripting. In master, we have:
> Definition 	Scripting
> buildcost 	buildcost
> enhancement_cost 	enhancement_cost
> return_on_dismantle 	returned_wares
> return_on_dismantle_on_enhanced 	returned_wares_enhanced
> 
> This branch:
> Definition 	Scripting
> buildcost 	buildcost
> enhancement -> buildcost 	enhancement_cost
> return_on_dismantle 	returned_wares
> enhancement -> return_on_dismantle 	returned_wares_enhanced
> 
> How about:
> Definition 	Scripting
> buildcost 	buildcost
> enhancement -> buildcost 	enhancement_buildcost
> return_on_dismantle 	returns_on_dismantle
> enhancement -> return_on_dismantle 	enhancement_returns_on_dismantle

Well I am not sure but I believe the values in the coumn Scripting are those defined in building.h to be part of the Building Description in C++. I don't see any necessity to change them as this would requirea lot of changes in a lot of files while they are currently clearly telling variables.
I would like to have clearly visible and distinguishable variables to be used to define a building, cause identifying the meaning from recognizing whether we are in a subtable or not is error prone for me. 
so -1 for the last proposition as it would change the wrong side of the interface between lua and our c++ code

**Comment by gunchleoc** [comment]
The "Scripting" column are the Lua access functions defined in `lua_map.cc`, used by the `building_help.lua` script.

The names in C++ are not relevant to this discussion, I can change them to match anything we decide here. The important thing is the Lua interface.

So, the "Definition" column refers to https://www.widelands.org/documentation/autogen_toc_lua_tribes_buildings/ and the "Scripting" column to https://www.widelands.org/documentation/autogen_wl_map/#buildingdescription

**Comment by hessenfarmer** [comment]
Ok understood,
I would prefer to have both of them unique names, as this would make a filesearch over the definitions much easier (searching for buildcost would deliver 2 returns if both are named buildcost) and it would be clear at first glance what the purpose of a value is

**Comment by gunchleoc** [comment]
How about this:

| Definition | Scripting |
| --- | --- |
| buildcost | buildcost |
| enhancement -> enhancement_cost | enhancement_cost |
| return_on_dismantle | returns_on_dismantle |
| enhancement -> enhancement_return_on_dismantle | enhancement_returns_on_dismantle |

Code example for definition:

```
   buildcost = {
      log = 4,
      granite = 2
   },
   return_on_dismantle = {
      log = 2,
      granite = 1
   },

   enhancement = {
      name = "barbarians_goldmine_deep",
      enhancement_cost = {
         log = 4,
         granite = 2
      },
      enhancement_return_on_dismantle = {
         log = 2,
         granite = 1
      }
   },
```

**Comment by hessenfarmer** [comment]
that would fulfil my needs
thanks

**Comment by frankystone** [comment]
Sounds good.

Is the code regarding the websites encyclopdia affected?

**Comment by gunchleoc** [comment]
> Is the code regarding the websites encyclopedia affected

No, the JSON data will remain as it is, since it doesn't show the enhancement cost anyway. It could be added, but then we need to decide whether we want the base cost or the cumulative cost.

**Comment by gunchleoc** [comment]
Changes are done. There is still some programming by exception in this branch for providing compatibility code. I can fix that before merging this branch when https://github.com/widelands/widelands/pull/4153 has hit master.

**Pull request merged**
