### PR TITLE
Tutorial 01 fixes

### LINKED ISSUE #2149: Teach middle-click on Windows in Tutorial
If we taught how to minimize windows in the Basic Tutorial, we will probably get less questions like this one:

https://www.widelands.org/forum/topic/4623/

Alternatively, we could teach accessing the "Controls" section in the Encyclopedia.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2019-09-07T07:12:05Z
 * owner: gunchleoc
 * the launchpad url was https://bugs.launchpad.net/bugs/1843111

### LINKED ISSUE #5899: Buildhelp image names need updating in Tutorial 01
**Describe the bug**
#5868 replaced the buildhelp images with mipmapped ones, but the tutorial referred to them by direct path and filename.

**To reproduce**
1. Start Tutorial 01
2. Get to the "How to Build a Quarry" message which expalins the buildhelp icons
3. See error

**Expected behavior**
The correct buildhelp icons should be shown.

**Screenshots**
tutorial1_buildhelp

**Version:**
 - Widelands Version: [82cf848](https://github.com/widelands/widelands/commit/82cf848537cab6232255c9f4a4b8b9485a725723)

**Additional information**
The easy solution is to update the hardcoded names to the scale 1 names. The correct one would be to allow look-up of mipmapped images from Lua?

### PR DESCRIPTION
**Pull request by tothxa**
**Type of change**
Bugfix

**Issue(s) closed**
Fixes #5899
Fixes #2149

**New behavior**
 - Adjusted window sizes
 - Wording and continuity improvements
 - Teach about touchpad settings
 - Make website link clickable

**Possible regressions**
Tutorial 01

### CODE REVIEW

**Review by hessenfarmer — COMMENTED** [review]
code looks good will test tonight

**Comment by hessenfarmer** [comment]
ok teted it. there is still a continuity error with the tutorial:
- when asked to activate the build spaces overlay the objective (set in line 58 of missionthread.lua) is autofulfilled as the buildhelp was already on at least on my machine (maybe due to saved settings) for the tutorial we should always start with disabled build spaces until the message comes to actiovate it

**Comment by tothxa** [comment]
> ok teted it. there is still a continuity error with the tutorial:
> 
> when asked to activate the build spaces overlay the objective (set in line 58 of missionthread.lua) is autofulfilled as the buildhelp was already on

Oops, indeed, I noticed too, but didn't realise that it could and should also be fixed. Will do it.

**Review by hessenfarmer — APPROVED** [review]
everything fine now. tested and working.
no need to wait for CI as nothing is checked in the tutorials there.   
will merge asap to save some Ci cycles 
thanks for the fixes

**Comment by tothxa** [comment]
Thank you for the review. :)

**Pull request merged**
