### PR TITLE
Flag: fix nr_of_roads()

### PR DESCRIPTION
**Pull request by cake-pie**
**Type of change**
Bugfix

**Issue(s) closed**
`nr_of_roads()` is identical to `nr_of_roadbases()`

https://github.com/widelands/widelands/blob/f915c8c5aab0b44dcc08eeeb5b083d6aff39df76/src/economy/flag.cc#L357-L367

https://github.com/widelands/widelands/blob/f915c8c5aab0b44dcc08eeeb5b083d6aff39df76/src/economy/flag.cc#L369-L379

**New behavior**
`nr_of_roads()` will now return number of roads (excludes waterways)
`nr_of_roadbases()` continues to return the number of roadbases (roads + waterways)

### CODE REVIEW

**Comment by hessenfarmer** [comment]
good catch, however I am not sure, whether this was intentional, to keep some compatibility. Have you checked all of the usages of nr_of_roads for whether this change makes any difference

**Comment by cake-pie** [comment]
> checked all of the usages of nr_of_roads

Three mentions in `defaultai.cc` which predate introduction of ferries and waterways. Looks fine to me but would probably be best if someone with more familiarity with the AI code could check.

**Comment by hessenfarmer** [comment]
I have had a look into this. the conclusion is:   
Although the AI does not know how to handle waterways (yet) all three instances should take them into account if this will be implemented, so please change these instances to nr_of_roadbases() in this PR

**Comment by cake-pie** [comment]
My reasoning was to leave it as is until AI gets waterway/ferry support, but I'll take your word for it.

**Review by hessenfarmer — APPROVED** [review]
LGTM.

**Comment by hessenfarmer** [comment]
@bunnybot update merge

**Pull request closed without merging**
