### PR TITLE
bar02: Adjust check for sentry in 'basic economy' objective

### PR DESCRIPTION
**Pull request by cake-pie**
**Type of change**
Bugfix

**Problem description**
As part of the first objective in barbarian campaign mission 2, the player is asked to:

> Build a sentry on the eastern border

However, the objective can be completed even if the sentry is placed quite far from the border. In this screenshot, it doesn't even push the borders any further forward compared to the existing conquer range from the headquarters:
bar02-obj_build_basic_economy

Reason for this is that the "intended solution" would be to place the sentry at (57,36); the criteria is loosened to check within a size 6 region -- presumably to give the player a bit of leeway; but it seems the criteria got relaxed way too much.

**To reproduce**
Play the scenario, place sentry as shown in screenshot.

**New behavior**
Requires the sentry to be placed close enough to the southeast border so that it gets advanced forward.
Sentry must be occupied by soldiers (previously, criteria fulfilled as soon as construction completed).

**How it works**
Instead of checking for placement of sentry building, test if player has gained ownership of position (60,38). This is one step forward from the midpoint of southeast edge of existing territory at mission start.

In the below screenshot, reed fields have been placed to mark (60,38) and show that it is the midpoint of southeast edge of size 10 hexagon from headquarters (conquer range = 9). Sentry at intended (57,36) easily fulfills this requirement.
bar02-obj_build_basic_economy-f-60-38

With conquer range = 6, there are already three possible locations for the sentry upon game start. A fourth position at (54,38) becomes available by cutting down just one tree.

**Possible regressions**
The northeast side would also technically count as "on the eastern border", but with the rocks and forest in the way, it is hopefully obvious to players that they should expand toward the open ground to southeast. In the worst case, objective text can be changed to be more specific: "southeast border"

### CODE REVIEW

**Review by hessenfarmer — APPROVED** [review]
good catch and nice solution
@cake-pie how would you like to be credited in our credits for your contribution

**Comment by hessenfarmer** [comment]
@bunnybot merge

**Comment by cake-pie** [comment]
I understand that merging is done on codeberg rather than github, but the mirrored commit 66330cc on codeberg does appear to contain authorship info ([see here](https://codeberg.org/wl/widelands/pulls/4844/commits)), so how is it not preserved in the history after merging?

**Comment by hessenfarmer** [comment]
this is because we do a squash merge of each PR in one commit on master.
this is to allow PR with lots of intermediate commits due e.g. due to heavy discussions, while not cluttering the master repository.

**Comment by cake-pie** [comment]
I've seen other projects that use these mechanisms to preserve credit when (squash) merging:
- Set author explicitly `git commit --author`, after `git merge --squash ...` or `git merge --no-commit ...`
- Multiple authors can be credited using `Co-authored-by:` trailers in the commit message<br/> I don't know about codeberg, but github is [capable of picking this info up](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) and will even add it automatically when applying suggested changes in a PR.

Also there is a discrepancy if we compare db5522ec of this PR to the subsequent 0a77b835 (squashed from 14 commits), in which both the author field and co-authorship trailers were set:

```bash
$ git log -n 2
commit 0a77b835f8c742e48c637e5876a1141e621f9e12 (HEAD -> master, origin/master, origin/HEAD)
Author: Benedikt Straub <nordfriese@noreply.codeberg.org>
Date:   Wed Jul 31 21:54:37 2024 +0000

    Make add-on upload more robust against long processing times and show better error messages (CB #4799 / GH #6437)
    Co-authored-by: Benedikt Straub <nordfriese@noreply.codeberg.org>
    Co-committed-by: Benedikt Straub <nordfriese@noreply.codeberg.org>

commit db5522ecfa5b1229aae229110bd361b28cc1cf61
Author: The Widelands Bunny Bot <bunnybot@noreply.codeberg.org>
Date:   Wed Jul 31 10:56:56 2024 +0000

    bar02: Adjust check for sentry in 'basic economy' objective (GH #6482 / CB #4844)
````

**Comment by hessenfarmer** [comment]
nevertheless I still would like to hear how you @cake-pie would like to be credited in our in game credits.  
Possible options are nickname only, realname only or the combination of both like realname (nickname)

**Comment by cake-pie** [comment]
nickname only is fine, thanks

**Comment by cake-pie** [comment]
> I'll look into it the next days.

Thanks @cb/Nordfriese for addressing this. One comment, the bot currently misses any existing co-author trailers -- besides being manually set, these could occur automatically e.g. when applying suggested changes in a github PR. To scoop up the trailers as well:

```bash
$ git log --no-merges --format='Co-authored-by: %an <%ae>%n%(trailers:key=co-authored-by)' 755251e0..396c8768 | sort --unique

Co-authored-by: Benedikt Straub <benedikt-straub@web.de>
Co-authored-by: Benedikt Straub <nordfriese@noreply.codeberg.org>
Co-authored-by: The Widelands Bunny Bot <bunnybot@noreply.codeberg.org>
Co-authored-by: The Widelands Translations Bot <bunnybot@widelands.org>
Co-authored-by: Tóth András <txa-dev@posteo.hu>
Co-authored-by: T��th Andr��s <80712255+tothxa@users.noreply.github.com>
Co-authored-by: T��th Andr��s <tothxa@noreply.codeberg.org>
Co-authored-by: T��th Andr��s <txa-dev@posteo.hu>
Co-authored-by: Widelands Bunnybot <bunnybot@widelands.org>
```

This surfaces the different issue of duplicates of same contributor under varying name/email; probably not helped by having the repo mirrored on two hosting providers where account details could be different. It can be dealt with using gitmailmap, for example the config might look like this:

```
Benedikt Straub <benedikt-straub@web.de> <nordfriese@noreply.codeberg.org>
The Widelands Bunny Bot <bunnybot@widelands.org> Widelands Bunnybot <bunnybot@widelands.org>
The Widelands Bunny Bot <bunnybot@widelands.org> The Widelands Bunny Bot <bunnybot@noreply.codeberg.org>
The Widelands Translations Bot <bunnybot@widelands.org>
Tóth András <txa-dev@posteo.hu>
Tóth András <txa-dev@posteo.hu> <80712255+tothxa@users.noreply.github.com>
Tóth András <txa-dev@posteo.hu> <tothxa@noreply.codeberg.org>
```

Using with `git log` didn't map the trailers for me:

```bash
$ git log --no-merges --mailmap --format='Co-authored-by: %an <%ae>%n%(trailers:key=co-authored-by)' 755251e0..396c8768 | sort --unique
# same result as before
```

But it does work with `git shortlog`:

```bash
$ git shortlog --no-merges --group=author --group=trailer:co-authored-by 755251e0..396c8768 -s -e | awk '{$1=""; print "Co-authored-by:"$0}'
Co-authored-by: Benedikt Straub <benedikt-straub@web.de>
Co-authored-by: The Widelands Bunny Bot <bunnybot@widelands.org>
Co-authored-by: The Widelands Translations Bot <bunnybot@widelands.org>
Co-authored-by: Tóth András <txa-dev@posteo.hu>
```

In this case, the result is coincidentally the same as not having grabbed the co-author trailers, but the outcome could be different, e.g. suppose if you set a different primary email in mailmap, or choose to treat the translation bot and merge bot as the same entity.

**Pull request closed without merging**
