### PR TITLE
New testsuite stage in Travis

### PR DESCRIPTION
**Pull request by gunchleoc**

### CODE REVIEW

**Comment by Noordfrees** [comment]
In times when there are fewer PRs around, having 4 jobs in this stage would be more efficient. So perhaps we could additionally test the two GCC-4.8's in the 3rd stage? (as this is the one that fails most frequently with some shadowed declaration)

**Comment by gunchleoc** [comment]
Good idea - done

**Review by Noordfrees — APPROVED** [review]
LGTM :)

**Comment by gunchleoc** [comment]
Travis has reached the last stage and jobs are going green, so let's have it now.

**Pull request merged**
