### PR TITLE
Updated "Waterway length limit" phrase

### PR DESCRIPTION
**Pull request by ghost**
For issue #5582, I have gone through each of the instances where "Waterway length limit" is displayed and changed the phrasing to "Ferry range" as requested.

### CODE REVIEW

**Review by tothxa — CHANGES_REQUESTED** [review]
Please don't update the `po` and `pot` files directly. They are updated automatically with the translation updates. We don't even edit them directly for typo fixes that only affect English (that would need manual pushing the updated `po` files to transifex), but this one is a major change where the translations will need to change too. Changing the English phrase behind the translations would hide the change from translators.

**Comment by klaus-halfmann** [comment]
@kskretteberg any progress on this one? 
You might want to create a new branch to add only the changes not affected by translations.

**Comment by hessenfarmer** [comment]
As there hasn't been any response for over a month we might close this PR to clean the board.    
@kskretteberg @Noordfrees

**Comment by tothxa** [comment]
+1

I think I'll take this over, and do the other tasks in #5582 as well.

**Pull request closed without merging**
