### PR TITLE
Ai supports seafaring

### PR DESCRIPTION
**Pull request by tibor95**
This introduces new ai_hint "supports_seafaring", that will be used to boost building score for particular building when on seafaring map. Should be followed by some AI training focused on seafaring...

### CODE REVIEW

**Comment by gunchleoc** [comment]
Code LGTM. Should we add this hint to all buildings in the Ship production chain for all tribes?

**Comment by tibor95** [comment]
I dont think it is necessary. But this is good question. Definitely not needed for buildings in basic economy...

**Comment by gunchleoc** [comment]
The Atlanteans won't need it because they build their weaving mill early anyway, but I think that Empire and Frisians could benefit from this.

**Comment by stonerl** [comment]
@tibor95 I ran fix_formatting.py on this branch and rebased it to master. Please pull before you intend to make any changes.

**Review by stonerl — APPROVED** [review]
LGTM :-)

@tibor95 can this go in or do you want to add hints for frisians and empire?

**Comment by tibor95** [comment]
It can go, I dont know which other buildings need such hints, because this is intended for special cases only...

**Comment by stonerl** [comment]
I just realized that the frisians' waving mill also need ```needs_seafaring = true,``` since it is only available on such maps, as it is with the barbarians'.

**Comment by hessenfarmer** [comment]
fixes #1032

**Pull request merged**
