### PR TITLE
Fix for #5501 - add set_soldiers cap

### PR DESCRIPTION
**Pull request by Kotbenek**
As mentioned by @Noordfrees in #5501 - I added a check in `set_soldiers` so the number won't exceed proposed value of 30000.

### CODE REVIEW

**Comment by Noordfrees** [comment]
Hi and thanks for the patch :) 

I tested it and it turns out 30000 is still too much; 15000 also crashes; 10000 seems to work.

Code suggestion: you could make the constant `constexpr` to improve compile-time optimizing.

**Comment by hessenfarmer** [comment]
I would prefer to analyze why it is crashing and fix the root cause rather then using this workaround 
At least we should documetn in a comment that it is a workaround

**Comment by Noordfrees** [comment]
It's not a workaround, it's an inherent limitation. You can't have more than a few thousand seeing objects on a node because their amount will overflow a variable. Making the variable bigger merely increases the maximum (and RAM usage, we can have several millions of instances of it in a big game). It's the same as when you try to add ten billion units of a ware – it overflows and is simply not permissible.

**Comment by Kotbenek** [comment]
Thanks for the quick review and tips :)
I did requested changes in my patch.

**Review by Noordfrees — APPROVED** [review]

**Pull request merged**
