### PR TITLE
Link badges to actions in readme

### PR DESCRIPTION
**Pull request by cxong**

### CODE REVIEW

**Comment by gunchleoc** [comment]
Hi cxong,

what is the motivation for this change? The badges are already linked in master and the only change seems to be some added line breaks in the code.

**Comment by cxong** [comment]
This links the badges to the github actions page; currently the badges just link to the svg images

**Comment by frankystone** [comment]
Yes, there were some brackets and links missing for `CodeQuality` and `Build`:

~~~~
![Code Quality](https://github.com/widelands/widelands/workflows/Formatting%20your%20code/badge.svg) ![Build](https://github.com/widelands/widelands/workflows/Build/badge.svg)
~~~~

**Review by gunchleoc — APPROVED** [review]
I didn't see that. Good catch! :)

**Pull request merged**
