### PR TITLE
Fix UI bugs

### PR DESCRIPTION
**Pull request by gunchleoc**
I went through the UI with a fine-tooth comb to hunt for bugs

* Fix diverse gettext markup bugs where translations weren't being displayed
* Fix textures for stones resources
* Remove pngrewrite from png optimization tools, because it broke the textures
* Deactivate translation catalog updates
* 1 new translatable string in loader UI

Notes:
* I accidentally committed the current gd translation, which I used for testing. Does no harm though.
* Follow-up issue: https://github.com/widelands/widelands/issues/3968
* Once this is merged, I'll use the scenarios in the tribes_filtering branch to see if pngrewrite broke any other textures
* Shall we push the new string and then give translators another week? We can use the validation project to check for any true positive printf and ngettext errors once the deadline has passed. This won't slow down our release schedule.

### CODE REVIEW

**Comment by Noordfrees** [comment]
> Shall we push the new string and then give translators another week? We can use the validation project to check for any true positive printf and ngettext errors once the deadline has passed. This won't slow down our release schedule.

Since you insist we could give translations another week or so, or more if it fits for you. You'll have to take over all the release-related stuff I was intending to do though – I planned to have the release done by the 18th, and I will have not much time from the 23rd on.

**Comment by gunchleoc** [comment]
As I said, this will not delay the release. We can safely pull translations right until we package the release candidate, because we can run the validator to ensure that Widelands won't crash due to translations.

**Review by Noordfrees — COMMENTED** [review]
The RC is scheduled for the day after tomorrow so it is a bit less than a week… but OK fine :)
Code LGTM, not tested yet

**Review by Noordfrees — APPROVED** [review]
Tested. Thanks for fixing :)

**Pull request merged**
