### PR TITLE
Do not layout invisible items

### PR DESCRIPTION
**Pull request by jmoerschbach**
Reverts #4249, including shipwindow fix.
#3847 must be merged first!

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
This does not work for the single player setup screen:
shot0002

**Comment by Noordfrees** [comment]
Shipwindow tested and working

**Comment by jmoerschbach** [comment]
would have been too easy...^^
I'll have a look

**Review by Noordfrees — APPROVED** [review]
Works :) 
Code LGTM

**Pull request merged**
