### PR TITLE
#3471 add clang format hook

### PR DESCRIPTION
**Pull request by stonerl**
Added git sub module for clang format.
Added README.md and description for registering the hooks.

### CODE REVIEW

**Comment by gunchleoc** [comment]
I have done some testing. The problem is that it's interactive, which seems nice on the command line, but it will make GUI clients choke on the commit.

**Comment by stonerl** [comment]
```
git config hooks.clangFormatDiffInteractive false
```
Solves this. I will add it to the Readme.

**Comment by gunchleoc** [comment]
Making it non-interactive breaks committing on the command line (see below).

Maybe it would be easier to use our own algorithm from utils/fix-formatting.py and apply it only on changed files.

```
widelands (3471-add-clang-format-hook)$ git reset --hard origin/3471-add-clang-format-hook 
HEAD is now at 14894dfc7f add clang-format hooks
widelands (3471-add-clang-format-hook)$ git pull
Already up to date.
widelands (3471-add-clang-format-hook)$ ./utils/clang-format-hooks/git-pre-commit-format install
Pre-commit hook installed.
widelands (3471-add-clang-format-hook)$ git config hooks.clangFormatDiffInteractive false
widelands (3471-add-clang-format-hook)$ git diff
diff --git a/src/main.cc b/src/main.cc
index 820f6d2b42..81873deee6 100644
--- a/src/main.cc
+++ b/src/main.cc
@@ -76,5 +76,6 @@ int main(int argc, char* argv[]) {
 
                return 1;
        }
+       // xxxxxxxxxxxxxxxxx // xxxxxxxxxxxxxxxxx // xxxxxxxxxxxxxxxxx // xxxxxxxxxxxxxxxxx // xxxxxxxxxxxxxxxxx // xxxxxxxxxxxxxxxxx
 #endif
 }
widelands (3471-add-clang-format-hook)$ git commit -am test
The staged content is not formatted correctly.
You can fix the formatting with:
    $ ./utils/clang-format-hooks/apply-format --apply-to-staged

You can also make this script interactive (if you use git from a terminal) with:
    $ git config hooks.clangFormatDiffInteractive true
widelands (3471-add-clang-format-hook)$ git status
On branch 3471-add-clang-format-hook
Your branch is up to date with 'origin/3471-add-clang-format-hook'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/main.cc

no changes added to commit (use "git add" and/or "git commit -a")
widelands (3471-add-clang-format-hook)$ 

```

**Comment by stonerl** [comment]
It's not breaking, but one has to choose one or the other. Committing form the command line needs the interactive mode, using a GUI needs it turned off, that's what the documentation says, anyway. I'll add this to our Readme. Since it is optional I'd say we keep it and work on our tools as well. In the end we want contributers to commit clean code, won't we?

**Comment by gunchleoc** [comment]
I will definitely be using both the command line for small commits and a GUI tool for complicated commits, and I don't want to have to continually switch this on and off. -1 on that hassle.

We have a working algorithm in utils/fix-formatting.py that does not have this problem, and we should use that idea as a base. It is possible to get a list of changed files from git and then to run clang-format on those that end in .h or .cc.

**Comment by stonerl** [comment]
That's true. From what I read, a git hook can be a python script as well so maybe we can adapt our script to work as a commit-hook.

**Comment by gunchleoc** [comment]
I wouldn't use it as-is though, because it format everything. We will only want to format the changed C++ files, because:

* The Lua tab fixing produces different results on my machine from what bunnybot did, so I don't want to end up with an edit war on those files blowing up the repository
* People would have to install pyformat before they can commit anything
* Formatting only changed files means less time waiting for the commit to go through
* We will have changes to Lua and Python less often, so my formatting everything once a week when I update the translations should suffice.

**Comment by stonerl** [comment]
Closing this one, for the time being.

**Pull request closed without merging**
