### PR TITLE
Handle missing locale dir on Windows

### PR DESCRIPTION
**Pull request by gunchleoc**
* Canonicalize locale dir
* Show an error message box if locale dir is not a directory
* Support empty locale dir on Options screen.

Re. https://github.com/widelands/widelands/issues/3430

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
Code LGTM. Can a windows user please test this branch?

**Comment by Niektory** [comment]
Tested on Windows 7:
- If `data/locale` doesn't exist or is empty, a warning is printed in `stdout.txt`, the game starts and the options screen works.
- If `data/locale` is a file and not a directory, the game shows an error message and exits.
- Also works with `--datadir`.

**Comment by Noordfrees** [comment]
Thanks for testing :)

Appveyor is the ususal timeout and travis is green except GCC, merging now.

**Comment by hessenfarmer** [comment]
Unfortunately this makes testing with my repos a little bit more complicated as in the repo there is a file instead of a folder.

**Pull request merged**
