### PR TITLE
add ai basic decision algorithm for accepting diplomacy

### PR DESCRIPTION
**Pull request by hessenfarmer**
- don't accept anything in the first 10 + random minutes
- only accept offers from stronger players

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
LGTM, compiling this now.

```
.../src/ai/defaultai.cc:3349: Trailing whitespace at end of line
.../src/ai/defaultai.cc:3358: Trailing whitespace at end of line
```

---

```c++
accept = accept && foo
```
can be better written as
```c++
accept &= foo
```

**Comment by tibor95** [comment]
looks ok. 
So effect of this is that players will become members of the same team?

**Comment by hessenfarmer** [comment]
> looks ok. So effect of this is that players will become members of the same team?

yes, that is the effect of the new diplomacy feature

**Review by tibor95 — APPROVED** [review]
Looks 'safe' from AI's standpoint

**Comment by hessenfarmer** [comment]
@Noordfrees if you are happy as well feel free to merge

**Review by Noordfrees — APPROVED** [review]

**Pull request merged**
