### PR TITLE
ship statistics: change window size and button placement

### LINKED ISSUE #3446: Ship statistics window too narrow
The seafaring stats window is too narrow to display the status text in some languages.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2019-05-30T16:14:59Z
 * owner: nordfriese
 * the launchpad url was https://bugs.launchpad.net/bugs/1831117

### PR DESCRIPTION
**Pull request by stonerl**
The window and the description row are now 20px wider.

Filterbox buttons are now centered.

fixes #3446

### CODE REVIEW

**Comment by stonerl** [comment]
@Noordfrees Could you check if this fixes your problem?

**Comment by Noordfrees** [comment]
It´s still a bit too narrow ("Rüümte für Muden funnen" misses the last letter), could you make it another 10 px wider?
And the table doesn´t fill out the entire width of the window, is this intentional?

**Comment by stonerl** [comment]
>It´s still a bit too narrow ("Rüümte für Muden funnen" misses the last letter), could you make it another 10 px wider?

I minimized the `Name` column by 10 and added it to the `Status`.

> And the table doesn´t fill out the entire width of the window, is this intentional?

I guess so. I didn't change this. That's how it was always.

**Review by Noordfrees — APPROVED** [review]
Looking good :)

**Pull request merged**
