### PR TITLE
fix fishermens resource name

### LINKED ISSUE #4198: Fishers can't find any fish
Fishers don't work at all now. Reported on the forum: https://www.widelands.org/forum/topic/4755/?page=12#post-34372

**To Reproduce**
1. Build a Fisher's House near a shore that should have fish.
2. You'll receive a "No Fish" message immediately.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: 1.0~git24838[0107ae7@master] (Release)

### PR DESCRIPTION
**Pull request by hessenfarmer**
fixes #4198

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
LGTM
The example in workers/atlanteans/armorsmith/init.lua also needs fixing

**Comment by hessenfarmer** [comment]
Done

**Review by gunchleoc — APPROVED** [review]
Thanks for finding these :)

**Comment by Niektory** [comment]
`src/logic/map_objects/tribes/worker_program.cc` seems to have some incorrect examples too.

**Comment by hessenfarmer** [comment]
fixed the worker_program.cc documentation as well 
Thanks for spotting

**Comment by Niektory** [comment]
The AI needs fixing too:

https://github.com/widelands/widelands/blob/a6025002e9c36527275cf56e6b2d6797916b9e86/src/ai/defaultai.cc#L1567

**Comment by hessenfarmer** [comment]
> 
> 
> The AI needs fixing too:
> 

done. Very good catch

**Review by Niektory — APPROVED** [review]
Tested and works for all tribes, both human player and AI.

**Pull request merged**
