### PR TITLE
Decrease training site productivity when no soldier to train

### PR DESCRIPTION
**Pull request by Niektory**
It was erroneously being increased before as a consequence of the changes in #3865

### CODE REVIEW

**Comment by hessenfarmer** [comment]
Thanks for taking care I almost forgot this. Although the result would be the same could you change it to return skipped in this cycle, as I believe (still not sure as the code is complicated) this is called in case it is skipping due to no soldier present. If it fails due to no ressources it should return fail already.

**Comment by Niektory** [comment]
OK, changed to `return=skipped` now. I wasn't sure which one is appropriate.

**Review by hessenfarmer — APPROVED** [review]
Thanks for fixing

**Comment by hessenfarmer** [comment]
@Noordfrees 
I think we should have this as it fixes a bug introduced in a recent commit from me. Mea Culpa.

**Comment by Noordfrees** [comment]
Okay you can merge as soon as travis is green

**Comment by hessenfarmer** [comment]
Merged. Thanks for cleaning up my faults

**Pull request merged**
