### PR TITLE
Add terrain affinity to editor tooltips

### LINKED ISSUE #1967: Improve the help system for the editor
It does not seem to be possible to remove immovables in the map editor. This is kind-of frustrating, if one has accidentally put something into a wrong place.

Unless I have read the the editor tutorial poorly, the only solution is to restart from scratch, in which case this could be a documentation bug.

Forum discussion for trees/terrains help: https://wl.widelands.org/forum/topic/1870/

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-07-24T12:00:33Z
 * owner: kxq
 * the launchpad url was https://bugs.launchpad.net/bugs/1204482

### PR DESCRIPTION
**Pull request by gunchleoc**
* When placing terrains, show preferred trees
* When placing trees, show preferred terrains
* Get rid of obsolete "likes trees" workaround

Closes #1967

Notes:
* I left out the names, because there isn't enough space and I can't control the line breaks to make them clean
* For the trees, the tooltips are sometimes rendered upwards instead of downwards. That's https://github.com/widelands/widelands/issues/4180 and fixing it is out of scope for this branch.

### CODE REVIEW

**Comment by frankystone** [comment]
Nice :-)

One nit: Terrain images are not shown in a column. See red marking. This applies also to the tree-tooltip, but here it is not that noticeable.
editor_terrain_tooltips

**Comment by frankystone** [comment]
Maybe add a threshold of trees/terrains to which they are shown. E.g. Show only trees that have at least a chance to grow of 20%? Same for terrains.

I think it is not of interest if a tree on summer water has chance of 1,9%.

**Comment by gunchleoc** [comment]
> Terrain images are not shown in a column.

This is a limitation of our font renderer and can't be fixed in this branch. Showing only 1 column would make the tooltips too tall though.

> Maybe add a threshold of trees/terrains to which they are shown

Good idea, will do.

**Comment by frankystone** [comment]
Looks good now :-)

**Pull request merged**
