### PR TITLE
High resolution images of basic wares from blender models

### PR DESCRIPTION
**Pull request by bunnybot**
[tothxa](https://codeberg.org/tothxa)*[Mirrored from Codeberg](https://codeberg.org/wl/widelands/pulls/4576)*
*Created on Sun Nov 19 03:18:53 CET 2023 by [**Tóth András (tothxa)**](https://codeberg.org/tothxa)*

---

**Type of change**
New graphics

**Issue(s) closed**
Add hi-res images for many basic materials

**Possible regressions**
Bad looks, wrong hotspots

**Additional context**
Pitta, ration, snack, meal and blackroot are re-exported from @fraang's original blender models on opengameart. Cloth is re-exported from the model in the media repo. Marble and marble column are new models by me. All others are based on models (usually not the original ones) from the media repo, but needed new textures and various amount of adjustments and edits in blender. For the missing ones (e.g. fish, meat, water, wheat), I couldn't find any suitable source.

Some tools and military equipment still have blender models in the media repo (not all in usable state), but I'll do them in a follow-up PR. I'll try to do something for the ones without sources too, either hand-drawing in gimp or tracing in inkscape, based on the scaled up old images afterwards in yet another PR.

### CODE REVIEW

**Comment by frankystone** [comment]
@hessenfarmer : Maybe we can play this branch this evening to test #6230 ?

**Comment by hessenfarmer** [comment]
> @hessenfarmer : Maybe we can play this branch this evening to test #6230 ?

good idea

**Comment by hessenfarmer** [comment]
Ok I had a first look on the images.     
some thoughts:
1. can we make cloth and spidercloth distinguishable by color (just like the original menu icons) so make cloth just more yellow probably
2. As all our mining food is looking like sliced pitta with meat/fish, I think we should make the bread for all tribes using rations (i.e. all except amazons) look like pitta. 
3. quartz and diamond are looking a bit to similar. could you make them distinguishable more by shape an color. (perhaps make the quartz more white and diamond more blue make diamond look like a diamond (double triangle) and quartz an elliptic shape with both having 90 degrees changed major axis (i.e. diamond upright while quartz being horizontal)

**Comment by tothxa** [comment]
> 1. can we make cloth and spidercloth distinguishable by color (just like the original menu icons) so make cloth just more yellow probably

Cloth is always playercolour in the game, for all tribes, including spidercloth for Atlanteans. The old idle images were identical too. If we make the base colour of other tribes' cloth yellowish then that will interfere with the playercolour.

> 2. As all our mining food is looking like sliced pitta with meat/fish, I think we should make the bread for all tribes using rations (i.e. all except amazons) look like pitta.

Amazons do have rations. :) Actually I've just checked the bakery images, and loaves are visible for Atlanteans, Empire and Frisians. Actually my above question is answered (I should have checked before asking :) — honey bread is in loaves too.
So you either have consistency with the bakers (and th general character of the tribes), or with the miner foods. IMO the first one is much more important, while the latter one is just a minor one at most, as rations in themselves are already inconsistent with the ingredients. (and neither tribe has green vegetables as ingredient for either food :) So the shape of bread used for it is of least concern here. :)

> 3. quartz and diamond are looking a bit to similar. could you make them distinguishable more by shape an color. (perhaps make the quartz more white and diamond more blue make diamond look like a diamond (double triangle) and quartz an elliptic shape with both having 90 degrees changed major axis (i.e. diamond upright while quartz being horizontal)

Actually quartz was already supposed to be elliptic and diamond round, but I'll try to tweak the lighting of quartz to make it better visible. Also its colour to remove the bluish tint then. (I went for the colour of the old idle.png, but indeed, menu.png is mostly just gray.) But their colour is already much more different than before.

**Comment by hessenfarmer** [comment]
> > 1. can we make cloth and spidercloth distinguishable by color (just like the original menu icons) so make cloth just more yellow probably
> 
> Cloth is always playercolour in the game, for all tribes, including spidercloth for Atlanteans. The old idle images were identical too. If we make the base colour of other tribes' cloth yellowish then that will interfere with the playercolour.     

Ok so could you switch the colour of the menu image seoeratly just in case someone will define a tribe using both.

> 
> > 2. As all our mining food is looking like sliced pitta with meat/fish, I think we should make the bread for all tribes using rations (i.e. all except amazons) look like pitta.
> 
> Amazons do have rations. :) Actually I've just checked the bakery images, and loaves are visible for Atlanteans, Empire and Frisians. Actually my above question is answered (I should have checked before asking :) — honey bread is in loaves too. So you either have consistency with the bakers (and the general character of the tribes), or with the miner foods. IMO the first one is much more important, while the latter one is just a minor one at most, as rations in themselves are already inconsistent with the ingredients. (and neither tribe has green vegetables as ingredient for either food :) So the shape of bread used for it is of least concern here. :)      
    
Ok I did not think of the bakeries, so I agree to your argument here.    

>

**Comment by frankystone** [comment]
I have played empire this evening and all looks fine, imho, everything has much more contrast and is sharp. Marble looks a bit too edged for my taste, if feasible can the edges be made a bit broken off, so the edges are not that sharp?

**Comment by tothxa** [comment]
@frankystone I softened the marble block's edges.

That made me realise that I can actually do the same for log to give the bark some thickness. I've also noticed that the marble column was much darker than the block, so I fixed that too.

I replaced the Amazon bread with pitta, and actually changed the Frisian bread (I thought I'd done it, I don't know what I had messed up…) along with honey bread to loaf.

While testing Frisians, I've also realised that I should do scrap iron as well. (I could do mixed scrap too, but I'll actually propose to remove that as I'd already mentioned in the Amazon balancing topic in the forum.)

@hessenfarmer re cloth:
> Ok so could you switch the colour of the menu image seoeratly just in case someone will define a tribe using both.

Sorry, I don't understand this. I didn't change the menu images, so there spidercloth is bright white, while "plain" cloth (for all other tribes) is a bit yellow.

**Comment by hessenfarmer** [comment]
sorry my fault. I somehow got messed while comparing old with new. So this is ok from my side.

re Frisians. their ware fur was always a placeholder made from the cloth. However it would be nice to have a real image that looks like fur here. (basically a circle or an uprigth elliptic shape (the body) with four extensions in 4 directions (the legs) with a fur texture

**Comment by hessenfarmer** [comment]
from my side everything looks fine now. I really think that marble blocks are cut very cleanly on purpose and might look like this.  However I hav no strong feelings about this.   
thanks for the fur.

**Comment by hessenfarmer** [comment]
@bunnybot merge

**Review by hessenfarmer — APPROVED** [review]

**Pull request closed without merging**
