### PR TITLE
Fix clang to version 10

### PR DESCRIPTION
**Pull request by matthiakl**
Re #4598
One line screwed everything up...
This branch is behind master on purpose. Does this help to restore the correct format?

### CODE REVIEW

**Comment by Noordfrees** [comment]
Thanks for fixing!
I'm going to apply this fix to master in a way that deletes commit 99e2417ba83fd191e141d03c55db37dff429d0d0 from the history. This will cause merge errors to branches that merged master since then but we'd get those anyway.

**Comment by Noordfrees** [comment]
Applied in e5cd2012d95ec0552cf7b008039758bc5607a59e

**Comment by Noordfrees** [comment]
This seems not to have fixed it after all… 
2c363adeced44fe6943c1094ad4dbb21689e33c2

**Comment by matthiakl** [comment]
Strange...
It looks like only the main repository is affected. The formatting works fine in my fork:
https://github.com/matthiakl/widelands/runs/2633519595
but pull requests are reformatted:
https://github.com/matthiakl/widelands/actions/runs/861624961

**Comment by Noordfrees** [comment]
It seems like the action alternates randomly between the old and new clang-format versions, see e.g. #4862 3f0ce52 b4d0fce. Could explicitly uninstalling all pre-installed clang versions except v10 help perhaps?

**Comment by matthiakl** [comment]
> Could explicitly uninstalling all pre-installed clang versions except v10 help perhaps?

Seems to work. Something with `update-alternatives` is wrong. Previously there was no output about changing the auto mode. Now, there is:
```
update-alternatives: warning: alternative /usr/bin/clang++-11 (part of link group clang++) doesn't exist; removing from list of alternatives
update-alternatives: warning: /etc/alternatives/clang++ is dangling; it will be updated with best choice
update-alternatives: using /usr/bin/clang++-10 to provide /usr/bin/clang++ (clang++) in auto mode
update-alternatives: warning: alternative /usr/bin/clang-11 (part of link group clang) doesn't exist; removing from list of alternatives
update-alternatives: using /usr/bin/clang-10 to provide /usr/bin/clang (clang) in auto mode
update-alternatives: warning: /etc/alternatives/clang is dangling; it will be updated with best choice
update-alternatives: warning: alternative /usr/bin/clang-format-11 (part of link group clang-format) doesn't exist; removing from list of alternatives
update-alternatives: using /usr/bin/clang-format-10 to provide /usr/bin/clang-format (clang-format) in auto mode
update-alternatives: warning: /etc/alternatives/clang-format is dangling; it will be updated with best choice
```
I also added a safe check, to quit on wrong version.

Here is my last log: https://github.com/matthiakl/widelands/runs/2638530697?check_suite_focus=true#step:5:80

**Comment by Noordfrees** [comment]
LGTM, applied in 2bf3b30bfa440f91dd2be80ddcbf8efca870d185

**Comment by matthiakl** [comment]
Ok, hopefully this will last longer now...

**Comment by Noordfrees** [comment]
Seems to have worked :)

**Pull request closed without merging**
