### PR TITLE
Cleanup SDL headers

### PR DESCRIPTION
**Pull request by gunchleoc**
This is the final branch in the cleanup includes series.

- Only include SDL headers as needed
- Use regular expressions in `utils/build_deps.py` to match dependencies
  to external libraries, e.g. `USES_SDL2`

### CODE REVIEW

**Comment by gunchleoc** [comment]
The checks have gone green, so this is ready for review now.

**Comment by jmoerschbach** [comment]
Hi,

CI is all green, on my machine a clean rebuild went also flawless. Only warning I get is:
../src/map_io/map_players_view_packet.cc: In member function 'void Widelands::MapPlayersViewPacket::read(FileSystem&, Widelands::EditorGameBase&, bool, Widelands::MapObjectLoader&, const TribesLegacyLookupTable&, const WorldLegacyLookupTable&)':
../src/map_io/map_players_view_packet.cc:533:10: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type 'long unsigned int' [-Wformat=]
  533 |          "MapPlayersViewPacket::read: player %u: in "

Which was already fixed on master via  #3771

So I think this can go in after  master is once again merged into here :)

**Review by Noordfrees — APPROVED** [review]
Code LGTM. This can go in as soon as travis is green.

**Comment by Noordfrees** [comment]
Travis reports a compile error about some missing SDL include which needs to be fixed.

**Comment by Niektory** [comment]
7c3a5d9f0900cc6b2bb2019477a75e4d7f276992 will fix it.

**Comment by Noordfrees** [comment]
Thanks for the patch :)

I'll merge this branch as soon as travis is happy.

**Pull request merged**
