### PR TITLE
Fix Add-Ons Admin Menu Visibility

### PR DESCRIPTION
**Pull request by Noordfrees**
This fixes the bug that the visibility of the admin dropdown in the remote interaction window does not change when logging in or out.

### CODE REVIEW

**Comment by Noordfrees** [comment]
This is a one-liner change and has been without review for a whole month ;)

**Comment by klaus-halfmann** [comment]
> This is a one-liner change and has been without review for a whole month ;)

Can you tell me how I can become admin in this context ? :-)

**Review by klaus-halfmann — APPROVED** [review]
Code is ok for me , but I do not find that action menu?

**Comment by Noordfrees** [comment]
The dropdown is visible only for logged-in users who have been granted admin access to the server interfaces (add-ons and metaserver/lobby), or if you have a full local add-ons server testing setup. That is only a very small number of users :) 
grafik

**Pull request merged**
