### PR TITLE
Escape richtext in editor info tool

### PR DESCRIPTION
**Pull request by gunchleoc**

### CODE REVIEW

**Review by Noordfrees — APPROVED** [review]
LGTM, tested and working :)

**Comment by frankystone** [comment]
Is wl_map_info (used by the website for uploading maps) affected by this change?

**Comment by Noordfrees** [comment]
No, the change applies only to the text displayed in the editor info tool window.

**Comment by Noordfrees** [comment]
Travis failure is a strange GCC9 test suite issue that happens pretty often atm; the usual timeout on appveyor. Merging now.

**Pull request merged**
