### PR TITLE
Add pre-commit hook for clang-format

### PR DESCRIPTION
**Pull request by gunchleoc**
Re #3471

### CODE REVIEW

**Comment by gunchleoc** [comment]
Please don't forget to squash during the merge, because it contains test commits.

We will also need to add documentation.

**Comment by klaus-halfmann** [comment]
Change is all fine, only thing I do not understand: when how will install-githooks.sh be called and become effective?

And (unrelated) how can we force the merge, as some travis builds just timed out.

**Comment by stonerl** [comment]
The user has to execute the script manually.
 
Regarding the time-outs, I'm currently working on the Travis-CI integration in another branch.

Sat Sep 21 18:25:55 GMT+02:00 2019 Hasi50 <notifications@github.com>:

**Comment by gunchleoc** [comment]
Admins can merge everything, even if it's red. I'll go ahead and do so now. Thanks for the review!

I have added instructions directly to the master branch.

**Pull request merged**
