### PR TITLE
Fixes for mark/unmark button in training wheel options

### PR DESCRIPTION
**Pull request by gunchleoc**
My graphics are crashy today, so this is completely untested.

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
This fixes the mark/unmark state but not the jumping buttons

**Comment by gunchleoc** [comment]
Fixed now.

**Review by Noordfrees — COMMENTED** [review]
The width issue is fixed now, but now the button is initially labelled "Mark All" even if all checkboxes are marked initially

**Comment by gunchleoc** [comment]
*headdesk* Should be fixed now too.

**Review by Noordfrees — APPROVED** [review]

**Pull request merged**
