### PR TITLE
Install fixed version of 32bit glbinding

### LINKED ISSUE #6285: Workflow mingw build doesn't find `ninja` and C/C++ compiler
**Describe the bug**
Workflow builds are failing in mingw job with:
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**To reproduce**
See:
 - https://github.com/widelands/widelands/actions/runs/7372058568/job/20060435425
 - https://github.com/widelands/widelands/actions/runs/7371563696/job/20059372674?pr=6257
 - https://github.com/widelands/widelands/actions/runs/7371817137/job/20059878798?pr=6282

**Additional context**
First happened in https://github.com/widelands/widelands/actions/runs/7348943728/job/20010113598 but went away on re-running the job. But now it looks like all workflows are failing on this?

### PR DESCRIPTION
**Pull request by matthiakl**
**Issue(s) closed**
Fixes #6285 

**New behavior**
Install the last known version of glbindings for 32bit

**Additional context**
This step will become necessary for other 32bit packages in the future

### CODE REVIEW

**Comment by tothxa** [comment]
Also doing this in `install-dependencies.sh` will not play nice when #6257 is merged.

**Comment by matthiakl** [comment]
> Can't we use a whole fixed build environment?

You mean to use `pacman -U  https://repo.msys2.org/mingw/i686/mingw-w64-i686-*` for all packages with the currently available version?

> Also doing this in install-dependencies.sh will not play nice when https://github.com/widelands/widelands/pull/6257 is merged.

Trying to install the glbindings packages within the script is causing the error, because it is not longer available in the current repo. So there must be a change in the script.

**Comment by tothxa** [comment]
> > Can't we use a whole fixed build environment?
> 
> You mean to use `pacman -U https://repo.msys2.org/mingw/i686/mingw-w64-i686-*` for all packages with the currently available version?

I don't know pacman, nor msys, nor mingw... Does that mean specifying the version of each package one by one? That would be... suboptimal. Doesn't msys have actual releases or something? Or a specific commit of the package list that we can pin, and get versions from there?

> > Also doing this in install-dependencies.sh will not play nice when #6257 is merged.
> 
> Trying to install the glbindings packages within the script is causing the error, because it is not longer available in the current repo. So there must be a change in the script.

Actually this issue got me thinking about that script, whether we should move the actual package lists for each OS/distro into separate config files, at least for the ones we use in the workflows. But as long as they don't change often it's not a major problem. The problem here is the individual package version pinning, that is likely to need more changes soon.

**Comment by matthiakl** [comment]
> Does that mean specifying the version of each package one by one?

Yes.

> Doesn't msys have actual releases or something?

No, it works like other packaging systems on Linux distributions, there is a package index which lists all current versions, but you cannot load an older one.

> The problem here is the individual package version pinning, that is likely to need more changes soon.

We can extract the pinned versions for 32bit into a separate file, all other dependencies rarely change.

**Comment by tothxa** [comment]
> No, it works like other packaging systems on Linux distributions, there is a package index which lists all current versions, but you cannot load an older one.

Well, that sounds more like "appstores" as far as I'm concerned. Most GNU/linux distros have stable releases and archives of them.

OK, I've had a look at https://repo.msys2.org/mingw/i686/. So they do keep some older versions around, but it's not clear how long. Do you think they'll keep that repo itself when they stop supporting 32bit?

So I can't add much to the solution to this problem, so I can only summarise my whishlist, that you may ignore if you like:

 - The solution should ensure that 32bit mingw builds work in the workflow as long as possible with as little later maintenance as possible, while we can expect that upstream will keep dropping our dependencies.
 - It looks to me that we have to prepare for dropping 32bit mingw, so the "as long as possible" above means "preferably at least until WL v1.2" (whenever that may happen). So using ugly hacks may be OK if they're needed to eliminate maintenance burden.

**Review by hessenfarmer — APPROVED** [review]
seems to work and provides a template for a workaround

**Comment by hessenfarmer** [comment]
@bunnybot merge

**Pull request closed without merging**
