### PR TITLE
implement caret positioning via mouse

### LINKED ISSUE #4636: Move caret with mouse click in multi-line edit box
#4578 implemented it for single-line edit boxes, multi-line edit boxes were left out, but would be as useful.

### PR DESCRIPTION
**Pull request by jmoerschbach**
Closes  #4636

### CODE REVIEW

**Comment by Noordfrees** [comment]
By copy-pasting the following text into a multiline-editbox
```
öäASLFf,þ€¶^øvmsöjwasoödm.KNŋđðħ ŋđħÐŦŦŦŦ’  ª¥ÐÆẞªÐ›©‹›©‘‹ŊªĦŦªĦ
```
and then clicking around a lot and pressing backspace repeatedly I managed to trigger
```
widelands: ../src/ui_basic/multilineeditbox.cc:228: uint32_t UI::MultilineEditbox::Data::next_char(uint32_t): Assertion `cursor <= text.size()' failed.
```

**Comment by jmoerschbach** [comment]
Hmm, I cannot reproduce. What exactly did you do?
I tested with both multiline editboxes in mapoptions of editor

**Comment by Noordfrees** [comment]
Took me over ten minutes of typing until I managed to reproduce in gdb. It finally happened after using the numpad's Delete key:
```
widelands: ../src/ui_basic/multilineeditbox.cc:228: uint32_t UI::MultilineEditbox::Data::next_char(uint32_t): Assertion `cursor <= text.size()' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff6b03864 in __GI_abort () at abort.c:79
#2  0x00007ffff6b03749 in __assert_fail_base
    (fmt=0x7ffff6c8f458 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55555744c220 "cursor <= text.size()", file=0x55555744c0e0 "../src/ui_basic/multilineeditbox.cc", line=228, function=<optimised out>) at assert.c:92
#3  0x00007ffff6b15a96 in __GI___assert_fail
    (assertion=0x55555744c220 "cursor <= text.size()", file=0x55555744c0e0 "../src/ui_basic/multilineeditbox.cc", line=228, function=0x55555744c260 "uint32_t UI::MultilineEditbox::Data::next_char(uint32_t)")
    at assert.c:101
#4  0x00005555560aa23a in UI::MultilineEditbox::Data::next_char(unsigned int) (this=0x615000142100, cursor=110) at ../src/ui_basic/multilineeditbox.cc:228
#5  0x00005555560a9922 in UI::MultilineEditbox::Data::calculate_selection_boundaries(unsigned int&, unsigned int&) (this=0x615000142100, start=@0x7fffffff4220: 108, end=@0x7fffffff4230: 110)
    at ../src/ui_basic/multilineeditbox.cc:150
#6  0x00005555560a9a92 in UI::MultilineEditbox::Data::draw(RenderTarget&, bool) (this=0x615000142100, dst=..., with_caret=true) at ../src/ui_basic/multilineeditbox.cc:155
#7  0x00005555560aed55 in UI::MultilineEditbox::draw(RenderTarget&) (this=0x6110003b0a00, dst=...) at ../src/ui_basic/multilineeditbox.cc:640
#8  0x00005555560be581 in UI::Panel::do_draw_inner(RenderTarget&) (this=0x6110003b0a00, dst=...) at ../src/ui_basic/panel.cc:952
#9  0x00005555560befcf in UI::Panel::do_draw(RenderTarget&) (this=0x6110003b0a00, dst=...) at ../src/ui_basic/panel.cc:992
#10 0x00005555560be5cc in UI::Panel::do_draw_inner(RenderTarget&) (this=0x624001e84930, dst=...) at ../src/ui_basic/panel.cc:956
#11 0x00005555560befcf in UI::Panel::do_draw(RenderTarget&) (this=0x624001e84930, dst=...) at ../src/ui_basic/panel.cc:992
#12 0x00005555560be5cc in UI::Panel::do_draw_inner(RenderTarget&) (this=0x624001e84800, dst=...) at ../src/ui_basic/panel.cc:956
#13 0x00005555560befcf in UI::Panel::do_draw(RenderTarget&) (this=0x624001e84800, dst=...) at ../src/ui_basic/panel.cc:992
#14 0x00005555560be5cc in UI::Panel::do_draw_inner(RenderTarget&) (this=0x624001e842a0, dst=...) at ../src/ui_basic/panel.cc:956
#15 0x00005555560befcf in UI::Panel::do_draw(RenderTarget&) (this=0x624001e842a0, dst=...) at ../src/ui_basic/panel.cc:992
#16 0x00005555560be5cc in UI::Panel::do_draw_inner(RenderTarget&) (this=0x624001e84100, dst=...) at ../src/ui_basic/panel.cc:956
#17 0x00005555560befcf in UI::Panel::do_draw(RenderTarget&) (this=0x624001e84100, dst=...) at ../src/ui_basic/panel.cc:992
#18 0x00005555560be5cc in UI::Panel::do_draw_inner(RenderTarget&) (this=0x62500016d100, dst=...) at ../src/ui_basic/panel.cc:956
#19 0x00005555560befcf in UI::Panel::do_draw(RenderTarget&) (this=0x62500016d100, dst=...) at ../src/ui_basic/panel.cc:992
#20 0x00005555560b7bb1 in UI::Panel::do_redraw_now() (this=0x62500016d100) at ../src/ui_basic/panel.cc:187
#21 0x00005555560b820a in UI::Panel::do_run() (this=0x62500016d100) at ../src/ui_basic/panel.cc:257
#22 0x0000555555a8c388 in UI::Panel::run<UI::Panel::Returncodes>() (this=0x62500016d100) at ../src/ui_basic/panel.h:111
#23 0x0000555555b3d892 in EditorInteractive::run_editor(EditorInteractive::Init, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (init=EditorInteractive::Init::kLoadMapDirectly, filename="maps/My_Maps/Checkered Plain.wmf", script_to_run="") at ../src/editor/editorinteractive.cc:971
#24 0x0000555556151bfb in FsMenu::MainMenu::action(FsMenu::MenuTarget) (this=0x7fffffffbb00, t=FsMenu::MenuTarget::kEditorContinue) at ../src/ui_fsmenu/main.cc:901
#25 0x000055555614c883 in FsMenu::MainMenu::handle_key(bool, SDL_Keysym) (this=0x7fffffffbb00, down=true, code=...) at ../src/ui_fsmenu/main.cc:590
#26 0x00005555560c0a4b in UI::Panel::do_key(bool, SDL_Keysym) (this=0x7fffffffbb00, down=true, code=...) at ../src/ui_basic/panel.cc:1169
#27 0x00005555560c2066 in UI::Panel::ui_key(bool, SDL_Keysym) (down=true, code=...) at ../src/ui_basic/panel.cc:1393
#28 0x0000555555a64d68 in WLApplication::handle_input(InputCallback const*) (this=0x6120000001c0, cb=0x55555801e8e0 <UI::Panel::do_run()::input_callback>) at ../src/wlapplication.cc:687
#29 0x00005555560b80d2 in UI::Panel::do_run() (this=0x7fffffffbb00) at ../src/ui_basic/panel.cc:240
#30 0x0000555555a8af7a in UI::Panel::run<int>() (this=0x7fffffffbb00) at ../src/ui_basic/panel.h:111
#31 0x0000555555a61b54 in WLApplication::run() (this=0x6120000001c0) at ../src/wlapplication.cc:566
#32 0x0000555555a59e72 in main(int, char**) (argc=1, argv=0x7fffffffdde8) at ../src/main.cc:47
```

**Comment by jmoerschbach** [comment]
I can't reproduce on windows. However, I question this assert anyway. look at the code:
https://github.com/widelands/widelands/blob/57ceff16819dde2460fdb6845f49ea8cc85ff40e/src/ui_basic/multilineeditbox.cc#L226-L230

**Comment by Noordfrees** [comment]
Good point I guess it can be safely removed…

**Review by Noordfrees — APPROVED** [review]
LGTM now, working well :)

**Comment by jmoerschbach** [comment]
thx for the review :)

**Pull request merged**
