### PR TITLE
Make ProgressWindow respond to window resizing

### LINKED ISSUE #4303: Window not maximized when starting with an option
The window of widelands is not maximized when starting with an option, eg. `--editor`

**To Reproduce**
1. Make sure to set the resolution to Maximized
2. Close widelands
3. Start widelands on a command line with option `--editor`

The window position is top left and it is not maximized.

The same happens when starting a scenario through the command line.

Console output:
~~~~
This is Widelands Version 1.0~git283[472f910@master] (Debug)                                                                            
[...]
[00:00:00.127 real] DEBUG: Graphics: Try to set Videomode 1262x805                                                                      
[00:00:00.190 real] DEBUG: Graphics: OpenGL: Version "4.6.0 NVIDIA 455.23.04"                                                           
[...]
[00:00:00.217 real] DEBUG: **** GRAPHICS REPORT ****
[00:00:00.217 real] DEBUG: VIDEO DRIVER GLVND x11
[00:00:00.217 real] DEBUG: Display #0: 1920x1080 @ 60hz SDL_PIXELFORMAT_RGB888
[00:00:00.217 real] DEBUG: Display #1: 1680x1050 @ 60hz SDL_PIXELFORMAT_RGB888
~~~~

**Expected behavior**
Maximized should be considered when starting with an option.

**Version:**
 - OS: archlinux
 - Widelands Version: [472f910@master] (Debug)

### PR DESCRIPTION
**Pull request by Niektory**
Fix #4303

Note that it can still respond rather slowly due to infrequent updates.

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
Works, but there's a regression: In master, I can already press C/S/W/Space/U/L while the game is loading if I want to start with non-default display flags. This no longer seems to work with this branch.

**Comment by Niektory** [comment]
Umm, can't you just do it after loading? I see no easy way to make it buffer the keys again.

**Comment by Noordfrees** [comment]
How about shifting the code for the creation of InteractivePlayer and InteractiveSpectator (in game.cc, network/gamehost.cc, gameclient.cc, and wlapplication.cc) further up so they are created before the time-intensive loading tasks begin, so the ProgressWindow could forward the keypresses to the already existing IBase?

**Comment by Niektory** [comment]
OK, I found a way that's not *too* complicated. You're welcome. ;-)

**Review by Noordfrees — APPROVED** [review]
LGTM, tested and working :)

**Pull request merged**
