### PR TITLE
Set correct WorkerQueue Economy after economy split

### LINKED ISSUE #3938: Expedition builder doesn't arrive
See [the replay](https://github.com/widelands/widelands/files/4758016/expedition_builder_bug.zip):
- At 3:31:31 an expedition is started at the main port.
- At 3:34:55 the builder's icon is darkened (indicating he is coming).
- At 3:39:36 it's lightened again (as if he's missing).
- He never arrives, even after several hours when there are many builders sitting in warehouses.

Interestingly, when I reload [a save made while it was in this broken state](https://github.com/widelands/widelands/files/4758146/385.wgf.zip), the problem disappears: the builder arrives and the expedition can proceed. So saving and reloading fixes it.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: r24628[7747702@master] (Release)

I *always* run into bugs when playing this map. Maybe someday I'll get to finish it ^^;

### PR DESCRIPTION
**Pull request by Noordfrees**
Probably fixes #3938

### CODE REVIEW

**Comment by Niektory** [comment]
I started a new game with this fix and got a crash after ~3 hours (using a release build).
[replay_2020-06-11_crash.zip](https://github.com/widelands/widelands/files/4764437/replay_2020-06-11_crash.zip)
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==64798==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x55c99f88f327 bp 0x7fff43786ec0 sp 0x7fff43786640 T0)
==64798==The signal is caused by a READ memory access.
==64798==Hint: address points to the zero page.
    #0 0x55c99f88f327 in Widelands::ExpeditionBootstrap::get_waiting_workers_and_wares(Widelands::Game&, Widelands::TribeDescr const&, std::vector<Widelands::Worker*, std::allocator<Widelands::Worker*> >*, std::vector<Widelands::WareInstance*, std::allocator<Widelands::WareInstance*> >*) (/home/mnj/widelands/widelands+0x615327)
    #1 0x55c99f8a413d in Widelands::ShippingSchedule::start_expedition(Widelands::Game&, Widelands::Ship&, Widelands::PortDock&) (/home/mnj/widelands/widelands+0x62a13d)
    #2 0x55c99f7d8ef5 in Widelands::Ship::ship_update_transport(Widelands::Game&, Widelands::Bob::State&) (/home/mnj/widelands/widelands+0x55eef5)
    #3 0x55c99f7d942d in Widelands::Ship::ship_update(Widelands::Game&, Widelands::Bob::State&) (/home/mnj/widelands/widelands+0x55f42d)
    #4 0x55c99f799c02 in Widelands::Bob::do_act(Widelands::Game&) (/home/mnj/widelands/widelands+0x51fc02)
    #5 0x55c99f8c126c in Widelands::CmdQueue::run_queue(int, unsigned int&) (/home/mnj/widelands/widelands+0x64726c)
    #6 0x55c99f5ebc7e in Widelands::Game::think() (/home/mnj/widelands/widelands+0x371c7e)
    #7 0x55c99f6f35fa in InteractiveBase::think() (/home/mnj/widelands/widelands+0x4795fa)
    #8 0x55c99f70d792 in InteractivePlayer::think() (/home/mnj/widelands/widelands+0x493792)
    #9 0x55c99f699884 in UI::Panel::do_run() (/home/mnj/widelands/widelands+0x41f884)
    #10 0x55c99f5f2464 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/home/mnj/widelands/widelands+0x378464)
    #11 0x55c99f52e0a4 in WLApplication::new_game() (/home/mnj/widelands/widelands+0x2b40a4)
    #12 0x55c99f52e400 in WLApplication::mainmenu_singleplayer() (/home/mnj/widelands/widelands+0x2b4400)
    #13 0x55c99f52ea5f in WLApplication::mainmenu() (/home/mnj/widelands/widelands+0x2b4a5f)
    #14 0x55c99f52ee9d in WLApplication::run() (/home/mnj/widelands/widelands+0x2b4e9d)
    #15 0x55c99f4cc779 in main (/home/mnj/widelands/widelands+0x252779)
    #16 0x7f16c5b66001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #17 0x55c99f52588d in _start (/home/mnj/widelands/widelands+0x2ab88d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/mnj/widelands/widelands+0x615327) in Widelands::ExpeditionBootstrap::get_waiting_workers_and_wares(Widelands::Game&, Widelands::TribeDescr const&, std::vector<Widelands::Worker*, std::allocator<Widelands::Worker*> >*, std::vector<Widelands::WareInstance*, std::allocator<Widelands::WareInstance*> >*)
==64798==ABORTING
```
Watching the replay with a debug build triggers an assertion failure:
```
widelands: ../src/economy/shipping_schedule.cc:125: void Widelands::ShippingSchedule::ship_arrived(Widelands::Game&, Widelands::Ship&, Widelands::PortDock&): Assertion `scheduling_state.dock == &port' failed.

Thread 1 "widelands" received signal SIGABRT, Aborted.
0x00007ffff6588355 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6588355 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6571853 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff6571727 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007ffff6580936 in  () at /usr/lib/libc.so.6
#4  0x0000555557384868 in Widelands::ShippingSchedule::ship_arrived(Widelands::Game&, Widelands::Ship&, Widelands::PortDock&) (this=0x612000ae8f58, 
    game=..., ship=..., port=...) at ../src/economy/shipping_schedule.cc:125
#5  0x0000555557341d88 in Widelands::PortDock::ship_arrived(Widelands::Game&, Widelands::Ship&) (this=0x6100000bf440, game=..., ship=...)
    at ../src/economy/portdock.cc:341
#6  0x00005555570207d7 in Widelands::Ship::ship_update_transport(Widelands::Game&, Widelands::Bob::State&) (this=0x6120004a8b40, game=..., state=...)
    at ../src/logic/map_objects/tribes/ship.cc:316
#7  0x000055555701ffcf in Widelands::Ship::ship_update(Widelands::Game&, Widelands::Bob::State&) (this=0x6120004a8b40, game=..., state=...)
    at ../src/logic/map_objects/tribes/ship.cc:269
#8  0x0000555556f23e78 in Widelands::Bob::do_act(Widelands::Game&) (this=0x6120004a8b40, game=...) at ../src/logic/map_objects/bob.cc:190
#9  0x0000555556f23be0 in Widelands::Bob::act(Widelands::Game&, unsigned int) (this=0x6120004a8b40, game=..., data=4146) at ../src/logic/map_objects/bob.cc:176
#10 0x0000555556f6cac5 in Widelands::CmdAct::execute(Widelands::Game&) (this=0x603003ba2140, game=...) at ../src/logic/map_objects/map_object.cc:105
#11 0x000055555742d9d7 in Widelands::CmdQueue::run_queue(int, unsigned int&) (this=0x7fffffff92e8, interval=3885, game_time_var=@0x7fffffff8a38: 10505726)
    at ../src/logic/cmd_queue.cc:121
#12 0x00005555567aac85 in Widelands::Game::think() (this=0x7fffffff8a30) at ../src/logic/game.cc:592
#13 0x0000555556c164df in InteractiveBase::think() (this=0x62500098d100) at ../src/wui/interactive_base.cc:700
#14 0x0000555556a5b63c in UI::Panel::do_think() (this=0x62500098d100) at ../src/ui_basic/panel.cc:506
#15 0x0000555556a58b57 in UI::Panel::do_run() (this=0x62500098d100) at ../src/ui_basic/panel.cc:195
#16 0x000055555643b812 in UI::Panel::run<UI::Panel::Returncodes>() (this=0x62500098d100) at ../src/ui_basic/panel.h:100
#17 0x00005555567aa410 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    (this=0x7fffffff8a30, start_game_type=Widelands::Game::Loaded, script_to_run="", replay=true, prefix_for_replays="replay") at ../src/logic/game.cc:562
#18 0x0000555556427de1 in WLApplication::replay() (this=0x6120000001c0) at ../src/wlapplication.cc:1503
#19 0x00005555564227fd in WLApplication::mainmenu() (this=0x6120000001c0) at ../src/wlapplication.cc:1160
#20 0x0000555556412d34 in WLApplication::run() (this=0x6120000001c0) at ../src/wlapplication.cc:493
#21 0x000055555640e62e in main(int, char**) (argc=2, argv=0x7fffffffdf88) at ../src/main.cc:42
```

**Comment by Noordfrees** [comment]
Investigated this and found that this is actually a bug in master in the new scheduling algorithm, unrelated to this branch. Opened a PR to fix this: #3941

**Review by Niektory — APPROVED** [review]
LGTM, although I'm not very familiar with the code involved.

**Review by gunchleoc — APPROVED** [review]
Code LGTM :)

Let's have it and then look into the other bug.

**Pull request merged**
