### PR TITLE
Enhance production site help

### PR DESCRIPTION
**Pull request by gunchleoc**
* Add "creates" and "collects" sections to productionsites in the Encyclopedia
* Use created/collected info to add some purpose icons
* Add menu icons to rocks
* Make tree menu icons smaller
* Add regression tests for supporting/supported productionsites

Re https://github.com/widelands/widelands/issues/3989

### CODE REVIEW

**Comment by Noordfrees** [comment]
The Collect section looks a bit broken. For the frisian farm it says:
  Collects: [field] → [farm] Barley Field (Ripe)
  Creates: [farm] → [field] → [beekeepers house] Beekeeper's House
This should always give the name of the created immovable imho, and perhaps additionally the consuming building for created immovables.

**Comment by gunchleoc** [comment]
> The Collect section looks a bit broken. For the frisian farm it says:
> Collects: [field] → [farm] Barley Field (Ripe)
> Creates: [farm] → [field] → [beekeepers house] Beekeeper's House
> This should always give the name of the created immovable imho, and perhaps additionally the consuming building for created immovables.

How would this look for berry bushes though? Something like this OK?

> Long • List • Of • Many • Berry • Bushes from: Berry Farm

BTW We currently have the same pattern for trainingsites where the names of the weapons are not listed.

**Comment by Noordfrees** [comment]
Perhaps draw only the images of the immovables, producers and consumers; and put their names and the "from"/… strings into a tooltip?

**Comment by gunchleoc** [comment]
We can't do tooltips for individual richtext string elements. It would also make the text unreadable with eye trackers https://github.com/widelands/widelands/issues/3706

**Comment by gunchleoc** [comment]
Here are side-by-side screenshots of the 2 discussed variants - this branch vs. adding immovable names.

immovable_names

I think the added immovable names make it hard to see which other building I would need to place close to this one, which is the point of the information. It would look the same in the "Collects" section, I accidentally coded it in the "Creates" section.

**Comment by hessenfarmer** [comment]
Best would be a dirty hack to summarize the relevant property of the list of images. 
in the example above this could look like 
[Berry Farm] -> Berry Bushes (medium)
[images of the medium berry bushes]
-> [Beekepers House] Beekeper's House
No clue however how to do this

**Comment by gunchleoc** [comment]
> Best would be a dirty hack to summarize the relevant property of the list of images.
> in the example above this could look like
> [Berry Farm] -> Berry Bushes (medium)
> [images of the medium berry bushes]
> -> [Beekepers House] Beekeper's House
> No clue however how to do this

We might do this if we use attributes and make them translatable. That would require a bigger code change though that I don't want to go into for this branch.

I am also using the exact same pattern as we have for trainingsite weapons where we don't list the weapon names, so I don't think it's that important right now.

**Comment by hessenfarmer** [comment]
> 
> 
> > Best would be a dirty hack to summarize the relevant property of the list of images.
> > in the example above this could look like
> > [Berry Farm] -> Berry Bushes (medium)
> > [images of the medium berry bushes]
> > -> [Beekepers House] Beekeper's House
> > No clue however how to do this
> 
> We might do this if we use attributes and make them translatable. That would require a bigger code change though that I don't want to go into for this branch.
> 
> I am also using the exact same pattern as we have for trainingsite weapons where we don't list the weapon names, so I don't think it's that important right now.

Agreed. so the right screenshot with only the images would fit better.

**Comment by gunchleoc** [comment]
That's the current state of this branch then.

**Review by hessenfarmer — APPROVED** [review]
If @Noordfrees has no further objections this branch looks ok for me

**Comment by Noordfrees** [comment]
Let's have it then :)

**Pull request merged**
