### PR TITLE
Skip ca-cert update

### LINKED ISSUE #4838: Github Windows CI is broken
Currently the windows CI Buolds on github are broken.
The error is due to a failed attempt to upgrade ca_certificates while doing the MSYS2 upgrades.
Error message says fatal error - cygheap base mismatch detected   

no clue so far how to solve this

### PR DESCRIPTION
**Pull request by matthiakl**
Quick fix for #4838

### CODE REVIEW

**Comment by hessenfarmer** [comment]
In my own installation using the curl 7.76 binaries failed so I am curious whether it will work here (I am using still 7.75 in appveyor using 7.73 is also working). Also I am not sure whether curl will work without the cert update anyway. 
But it is worth a try at least.

**Comment by matthiakl** [comment]
I tested it in my fork, and at least the dependencies were successful and the build started.
As the current mingw curl version is 7.76.1, I also bumped our version,

**Comment by hessenfarmer** [comment]
> I tested it in my fork, and at least the dependencies were successful and the build started.  

Ok, lets wait for the result then.    

> As the current mingw curl version is 7.76.1, I also bumped our version,

that is right but in the 7.76.1 there are a lot more dependencies needed for linking which I didn't get to work. So i still use the libcurl.a from 7.75 which works fine.   
Appveyor still uses 7.73 and it works as well

**Comment by matthiakl** [comment]
> that is right but in the 7.76.1 there are a lot more dependencies needed for linking which I didn't get to work. 

Ok, let's skip this update for now and just get the runner working again.

**Review by hessenfarmer — APPROVED** [review]
It works so we should have it for now. 
For the libcurl we could bump the version to download to 7.75.0 to be not too much behind but it is not an urgent thing. As said Appveyor is still on 7.73.

**Pull request merged**
