### PR TITLE
Add libspeex

### PR DESCRIPTION
**Pull request by gunchleoc**
Innosetup in GitHub action is complaining about a missing dll. Let's see if this fixes it.

### CODE REVIEW

**Comment by Noordfrees** [comment]
AppVeyor also needs this DLL: https://ci.appveyor.com/project/widelands-dev/widelands/builds/34579093

**Comment by TinoM** [comment]
As far as i can see, Speex was removed as a dependency, so we do not need it any more. Just removing the entry from the innosetup file should be enough.
If you have a look at older builds, speex was just pulled in as a dependency automatically.

(Because we are using the pre compiled packages, we have to include more than just the ogg libs we are actually using..)

**Review by TinoM — APPROVED** [review]
tested locally: widelands.exe does no longer need the speex dll to start.

**Comment by TinoM** [comment]
With the only change left in the innosetup script, no travis or appveyor run needed.

**Pull request merged**
