### PR TITLE
Allow loading addons with unit replacements first

### LINKED ISSUE #5140: Unit replacement by addons doesn't work
**Describe the bug**
It is not possible to replace units by addons. Neither the `__replace_if_exists`, nor the `__skip_if_exists` attribute works.

**To Reproduce**
1. Install the following addon: [test_immovable_replace_wad.zip](https://github.com/widelands/widelands/files/7598811/test_immovable_replace_wad.zip)
2. Start a new game
3. Get fatal exception when conflicting original unit is registered

**Expected behavior**
Game should start with original `cornfield_ripe` and replaced `wheatfield_medium`.

**Stdout**
```
[00:00:09.186 real] ERROR: ##############################
[00:00:09.186 real] ERROR:   FATAL EXCEPTION: Error while loading tribe 'amazons': DescriptionManager::register_description: Attempt to register description
[00:00:09.186 real] ERROR:    name: 'cornfield_ripe'
[00:00:09.186 real] ERROR:    script: 'tribes/immovables/cornfield/ripe/init.lua'
[00:00:09.186 real] ERROR: but the object has already been registered to
[00:00:09.186 real] ERROR:    script: 'addons/test_immovable_replace.wad/corn_ripe/init.lua'
[00:00:09.186 real] ERROR: ##############################
```

**Version:**
 - Widelands Version: v1.0 as well as current master

**Additional context**
The constructor of `Descriptions` in `src/logic/map_objects/descriptions.cc` preloads world and tribe addons first, with the following comment:
```
// Immediately preload and register all add-on units. Better to do this
// very early than to risk crashes because it was done too late…
```
while the logic in `src/logic/map_objects/description_manager.cc` `register_description()` assumes that addons are loaded last.

Actually, this early loading could be problematic, because these addons are preloaded even before the startmenu is displayed, so if an addon causes crashes (I'm not sure if it's actually possible), it can only be disabled by manually editing `.widelands/config`. Here's the backtrace to first call of `register_description()` at program start:
```
#0  Widelands::DescriptionManager::register_description (this=0x555558403830, description_name="wheatfield_medium", 
    script_path="addons/test.wad/wheat_medium/init.lua", attributes=std::vector of length 3, capacity 4 = {...},
caller={...})
    at /mnt/hely/proba/src/widelands-tmp/src/logic/map_objects/description_manager.cc:117
#1  0x00005555561e098a in Widelands::DescriptionManager::register_directory (this=0x555558403830, 
    dirname="addons/test.wad/wheat_medium", filesystem=0x555556bf7020, caller={...})
    at /mnt/hely/proba/src/widelands-tmp/src/logic/map_objects/description_manager.cc:83
#2  0x00005555561e0469 in Widelands::DescriptionManager::register_directory (this=0x555558403830,
dirname="addons/test.wad", 
    filesystem=0x555556bf7020, caller={...})
    at /mnt/hely/proba/src/widelands-tmp/src/logic/map_objects/description_manager.cc:61
#3  0x0000555555d48738 in Widelands::Descriptions::Descriptions (this=0x5555584cd1b0, lua=0x555558455fe0, 
    addons=std::vector of length 2, capacity 2 = {...})
    at /mnt/hely/proba/src/widelands-tmp/src/logic/map_objects/descriptions.cc:102
#4  0x000055555580ad58 in Widelands::EditorGameBase::mutable_descriptions (this=0x555558487a10)
    at /mnt/hely/proba/src/widelands-tmp/src/logic/editor_game_base.cc:223
#5  0x000055555580ac50 in Widelands::EditorGameBase::descriptions (this=0x555558487a10)
    at /mnt/hely/proba/src/widelands-tmp/src/logic/editor_game_base.cc:213
#6  0x0000555555809ff0 in Widelands::EditorGameBase::EditorGameBase (this=0x555558487a10, lua_interface=0x555558455fe0)
    at /mnt/hely/proba/src/widelands-tmp/src/logic/editor_game_base.cc:87
#7  0x000055555581702e in Widelands::Game::Game (this=0x555558487a10)
    at /mnt/hely/proba/src/widelands-tmp/src/logic/game.cc:157
#8  0x00005555559ccb7e in FsMenu::MainMenu::create_safe_game (this=0x7fffffffb370, show_error=false)
    at /mnt/hely/proba/src/widelands-tmp/src/ui_fsmenu/main.cc:227
#9  0x00005555559cddf3 in FsMenu::MainMenu::set_labels (this=0x7fffffffb370)
    at /mnt/hely/proba/src/widelands-tmp/src/ui_fsmenu/main.cc:336
#10 0x00005555559cc516 in FsMenu::MainMenu::MainMenu (this=0x7fffffffb370, skip_init=false)
    at /mnt/hely/proba/src/widelands-tmp/src/ui_fsmenu/main.cc:219
#11 0x00005555555ee03b in WLApplication::run (this=0x555556bf6ef0)
    at /mnt/hely/proba/src/widelands-tmp/src/wlapplication.cc:813
#12 0x00005555555e859c in main (argc=1, argv=0x7fffffffe3e8) at /mnt/hely/proba/src/widelands-tmp/src/main.cc:47
```

### PR DESCRIPTION
**Pull request by tothxa**
Closes #5140

This fixes the problem in `register_description()`, but does not make addons be loaded last. If that is desired, then more involved changes are required.

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
LGTM, not tested yet.
The extra log output is not needed IMHO – it only tells the scripter that the game does what it has been told to do. The `log`s that already exist could be turned into `verb_log_...` as well btw.

**Comment by tothxa** [comment]
> The extra log output is not needed IMHO – it only tells the scripter that the game does what it has been told to do.

It is needed because of the reversed logic. If the addon has `__replace...`, the log will show skipped and vice versa, which is confusing.

> The `log`s that already exist could be turned into `verb_log_...` as well btw.

OK.

**Comment by tothxa** [comment]
> > The extra log output is not needed IMHO – it only tells the scripter that the game does what it has been told to do.
> 
> It is needed because of the reversed logic. If the addon has `__replace...`, the log will show skipped and vice versa, which is confusing.

How about a unified neutral one line message, like: `verb_log_dbg("%s: using '%s' instead of '%s'\n", name, path_A, path_B)`?

**Comment by Noordfrees** [comment]
+1
but prefer `verb_log_info` instead of `verb_log_dbg`

**Review by Noordfrees — APPROVED** [review]

**Pull request merged**
