### PR TITLE
Fix sigsev for XDG_DATA_DIRS

### LINKED ISSUE #3518: XDG caused SIGSEGV
As in #1073 running the game instantly creates a sigsegv with the following backtrace: 

```
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff75e5c4d in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.5
#2  0x00007ffff6ea7d05 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000555556766616 in FileSystem::get_xdgdatadirs[abi:cxx11]() ()
    at ../src/io/filesystem/filesystem.cc:392
#4  0x0000555556439fc4 in WLApplication::handle_commandline_parameters (this=0x6120000001c0)
    at ../src/wlapplication.cc:977
#5  0x000055555643364f in WLApplication::init_settings (this=0x6120000001c0)
    at ../src/wlapplication.cc:781
#6  0x000055555642db12 in WLApplication::WLApplication (this=0x6120000001c0, argc=1, argv=0x7fffffffe2b8)
    at ../src/wlapplication.cc:350
#7  0x000055555642d3ba in WLApplication::get (argc=1, argv=0x7fffffffe2b8) at ../src/wlapplication.cc:307
#8  0x000055555642b51a in main (argc=1, argv=0x7fffffffe2b8) at ../src/main.cc:42
```

### PR DESCRIPTION
**Pull request by gunchleoc**
Fixes https://github.com/widelands/widelands/issues/3518

### CODE REVIEW

**Comment by Niektory** [comment]
This line probably needs fixing too:
https://github.com/widelands/widelands/blob/master/src/io/filesystem/filesystem.cc#L285

**Comment by gunchleoc** [comment]
Done. Needs compiling & testing under Windows.

**Comment by jmoerschbach** [comment]
Hi,

sry, unable to compile on windows 10 with mingw. I think the repeated macro expansion is the problem (redeclaration of home_char):

###########################################################

-- SDL2_INCLUDE_DIR is C:/msys64/mingw64/include/SDL2
-- SDL2MAIN_LIBRARY is C:/msys64/mingw64/lib/libSDL2main.a
-- Not using AddressSanitizer.
-- Detected mingw32-w64
-- Version of Widelands Build is r24436[b88a669@3518-xdg-char-pointer](Debug)
-- Configured windows resource file
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/Jonas/widelands2/widelands/build
[0/1] Re-running CMake...
-- SDL2_INCLUDE_DIR is C:/msys64/mingw64/include/SDL2
-- SDL2MAIN_LIBRARY is C:/msys64/mingw64/lib/libSDL2main.a
-- Not using AddressSanitizer.
-- Detected mingw32-w64
-- Version of Widelands Build is r24436[b88a669@3518-xdg-char-pointer](Debug)
-- Configured windows resource file
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/Jonas/widelands2/widelands/build

...
...

FAILED: src/io/filesystem/CMakeFiles/io_filesystem.dir/filesystem.cc.obj
C:\msys64\mingw64\bin\c++.exe  -DMINGW_HAS_SECURE_API -DWIN32_LEAN_AND_MEAN -D__STDC_FORMAT_MACROS -D__USE_MINGW_ANSI_STDIO -I../src -Isrc -isystem C:/msys64/mingw64/include/SDL2 -g    -std=c++11 -std=gnu++11 -fext-numeric-literals  -g -DDEBUG -Wall -Wpedantic -Wdeprecated-declarations -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wformat-y2k -Winit-self -Winvalid-pch -Wlogical-op -Wmissing-include-dirs -Wno-undef -Wold-style-cast -Woverlength-strings -Wpacked -Wpointer-arith -Wsign-promo -Wsync-nand -Wtrampolines -Wundef -Wunused -Wunused-macros -Werror=format-security -Werror=return-type -Werror=shadow -Werror=uninitialized -MD -MT src/io/filesystem/CMakeFiles/io_filesystem.dir/filesystem.cc.obj -MF src\io\filesystem\CMakeFiles\io_filesystem.dir\filesystem.cc.obj.d -o src/io/filesystem/CMakeFiles/io_filesystem.dir/filesystem.cc.obj -c ../src/io/filesystem/filesystem.cc
../src/io/filesystem/filesystem.cc: In static member function 'static std::string FileSystem::get_homedir()':
../src/io/filesystem/filesystem.cc:285:20: error: redeclaration of 'const char* const home_char'
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: note: in definition of macro 'TRY_USE_AS_HOMEDIR'
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: note: 'const char* const home_char' previously declared here
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: note: in definition of macro 'TRY_USE_AS_HOMEDIR'
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: error: redeclaration of 'const char* const home_char'
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: note: in definition of macro 'TRY_USE_AS_HOMEDIR'
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: note: 'const char* const home_char' previously declared here
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: note: in definition of macro 'TRY_USE_AS_HOMEDIR'
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: error: redeclaration of 'const char* const home_char'
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: note: in definition of macro 'TRY_USE_AS_HOMEDIR'
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: note: 'const char* const home_char' previously declared here
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
../src/io/filesystem/filesystem.cc:285:20: note: in definition of macro 'TRY_USE_AS_HOMEDIR'
  285 |  char const* const home_char = getenv(name);                                                     \
      |                    ^~~~~~~~~
[154/406] Building CXX object src/graphic/text/CMakeFiles/graphic_text.dir/rt_render.cc.obj

**Comment by jmoerschbach** [comment]
Possible fix? (compiles and runs at least)

```C++
 #ifdef _WIN32
	// Trying to get it compatible to ALL windows versions...
	// Could anybody please hit the Megasoft devs for not keeping
	// their own "standards"?
	char const* home_char;
#define TRY_USE_AS_HOMEDIR(name)                                                                   
	home_char = getenv(name);                                                                       
	if (home_char != nullptr && *home_char != 0 && check_writeable_for_data(home_char))             
		return home_char;

	TRY_USE_AS_HOMEDIR("USERPROFILE")
	TRY_USE_AS_HOMEDIR("HOMEPATH")
	TRY_USE_AS_HOMEDIR("HOME")
	TRY_USE_AS_HOMEDIR("APPDATA")

	log("None of the directories was useable - falling back to \".\"\n");
#else 
```

**Comment by gunchleoc** [comment]
Thanks - I have pushed your patch.

**Comment by jmoerschbach** [comment]
Hi,

compiles and runs. However compiler says there are unnecessary semicolons 
``` C++
TRY_USE_AS_HOMEDIR("USERPROFILE");
TRY_USE_AS_HOMEDIR("HOMEPATH");
TRY_USE_AS_HOMEDIR("HOME");
TRY_USE_AS_HOMEDIR("APPDATA");
```

Anything specific I can test so this finally can go in?

**Comment by gunchleoc** [comment]
Just make sure that you're using the XDG setup and then start WIdelands to see if it still crashes.

I have removed the extra `;`, so we need to wait for the builds to ensure that it still compiles on WIndows.

**Comment by jmoerschbach** [comment]
./compile.sh -t -w -s -a

Creating a Debug build. Use -r to create a Release build.

Will build without AddressSanitizer.

Basic XDG Base Directory Specification will be used on Linux
if no existing $HOME/.widelands folder is found.
The widelands user data can be found in $XDG_DATA_HOME/widelands
and defaults to $HOME/.local/share/widelands.
The widelands user configuration can be found in $XDG_CONFIG_HOME/widelands
and defaults to $HOME/.config/widelands.
See https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
for more information.

compiles and runs fine so I think this can go in ;)

**Comment by gunchleoc** [comment]
Thanks for testing again!

**Pull request merged**
