### PR TITLE
WIP: Unify program parsers

### PR DESCRIPTION
**Pull request by gunchleoc**
This branch was reviewed on Launchpad (https://code.launchpad.net/~widelands-dev/widelands/unify-program-parsers/+merge/367936), but there was an issue on Ubuntu Trusty. I can't reproduce this any more, so let's see what Travis says.

Refactor program parsers
- Pull out common code into new class MapObjectProgram
- Fix ware demand checks so that they only affect the correct tribes
- Get rid of extraneous calls to EditorGameBase::postload()
- Small performance tweak for trainingsite programs
- Get rid of now empty helper library

### CODE REVIEW

**Comment by stonerl** [comment]
It hung on this test:
```
test/maps/expedition.wmf/scripting/test_check_transportation_works_two_ships.lua ... 

  Running Widelands ... 
```
But only on `DEBUG: Ubuntu 14.04 with clang 5` I restarted it to see if it was a fluke.

**Comment by gunchleoc** [comment]
It went green now, but I'm rerunning it to make sure we don't have an intermittent bug here.

**Comment by gunchleoc** [comment]
After a few runs of the configuration, it hung again; this time on

```
test/maps/expedition.wmf/scripting/test_cancel_when_port_space_was_reached_one_ship.lua ... 
  Running Widelands ... done.
  Loading savegame: reached_port_space ...
```

So, there's something that needs fixing.

**Comment by gunchleoc** [comment]
After a few complete runs of the test suite on my local VM, Widelands froze on test/maps/expedition.wmf/scripting/test_cancel_when_port_space_was_reached_two_ships.lua ... 

So, I'm closing this PR unmerged.

```
This is Widelands Version unofficial-git-cc63ea7 (Debug)
Adding home directory: /tmp/widelands_regression_testxbZZqZ
Set home directory: /tmp/widelands_regression_testxbZZqZ
Set configuration file: /tmp/widelands_regression_testxbZZqZ/config
[] config:0: RealFSImpl::load: could not open file for reading: /tmp/widelands_regression_testxbZZqZ/config
Realpath: /home/cuideigin/sources/widelands/data
Adding directory: /home/cuideigin/sources/widelands/data
Adding directory: /home/cuideigin/sources/widelands
selected language: en_US
using locale en_US.utf-8
Graphics: Try to set Videomode 800x600
Graphics: OpenGL: Version "3.0 Mesa 11.2.0"
Graphics: SDL_GL_RED_SIZE is 8
Graphics: SDL_GL_GREEN_SIZE is 8
Graphics: SDL_GL_BLUE_SIZE is 8
Graphics: SDL_GL_ALPHA_SIZE is 0
Graphics: SDL_GL_BUFFER_SIZE is 24
Graphics: SDL_GL_DOUBLEBUFFER is 1
Graphics: SDL_GL_DEPTH_SIZE is 32
Graphics: SDL_GL_STENCIL_SIZE is 0
Graphics: SDL_GL_ACCUM_RED_SIZE is 0
Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0
Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0
Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0
Graphics: SDL_GL_STEREO is 0
Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
Graphics: SDL_GL_ACCELERATED_VISUAL is 1
Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
Graphics: SDL_GL_CONTEXT_FLAGS is 0
Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
Graphics: OpenGL: Double buffering enabled
Graphics: OpenGL: Max texture size: 8192
Graphics: OpenGL: ShadingLanguage: "1.30"
**** GRAPHICS REPORT ****
 VIDEO DRIVER x11
 pixel fmt 370546692
 size 800 600
**** END GRAPHICS REPORT ****
Style Manager: Reading style templates took 30ms
Initializing economy serial
┏━ Running Lua for world:
┃    Resources: 0ms
┃    Terrains: 7ms
┃    Immovables: 181ms
┃    Critters: 106ms
┗━ took: 294ms
Loading the world took 303ms
┏━ Running Lua for tribes:
┃    Ships: 32ms
┃    Wares: 52ms
┃    Immovables: 111ms
┃    Workers: 1152ms
┃    Warehouses: 41ms
┃    Productionsites: 311ms
┃    Trainingsites: 24ms
┃    Militarysites: 39ms
┃    Partially finished buildings: 2ms
┃    Tribe infos: 34ms
┗━ took: 1798ms
Loading the tribes took 1799ms
Reading Elemental Data ... took 0ms
 Reading Player Names And Tribe Data ... took 0ms
 Reading Port Spaces Data ... took 0ms
 Reading Heights Data ... took 0ms
 Reading Terrain Data ... took 1ms
 Reading Map Objects ... took 0ms
 Reading Player Start Position Data ... took 0ms
 Reading Resources Data ... took 1ms
 Reading Map Version Data ... took 0ms
 Reading Allowed Worker Types Data ... took 0ms
 Reading Allowed Building Types Data ... took 0ms
 Reading Node Ownership Data ... took 0ms
 Reading Exploration Data ... took 0ms
 Reading Flag Data ... took 0ms
 Reading Road Data ... took 0ms
 Reading Building Data ... took 0ms
 Reading Flagdata Data ... took 0ms
 Reading Roaddata Data ... took 0ms
 Reading Buildingdata Data ... took 0ms
 Second and third phase loading Map Objects ... took 1ms
 Reading Players View Data ... MapPlayersViewPacket::read: WARNING: Could not open "player/1/view/unseen_times_1" for reading. Assuming that the game is from an old version without player point of view. Will give player 1 knowledge of unseen nodes, edges and triangles (but not resources).took 0ms
 Reading Player Message Data ... took 0ms
 Reading Wincondition Data ... took 0ms
 Reading Objective Data ... took 0ms
 Reading Scripting Data ... took 0ms
 Reading map images ... took 0ms
 WidelandsMapLoader::load_map_complete() for 'expedition' took 52ms
Writing Elemental Data ... took 1ms
 Writing Player Names And Tribe Data ... took 0ms
 Writing Port Spaces Data ... took 0ms
 Writing Heights Data ... took 0ms
 Writing Terrain Data ... took 1ms
 Writing Player Start Position Data ... took 0ms
 Writing Player Message Data ... took 1ms
 Writing Resources Data ... took 0ms
 Writing Map Version ... took 0ms
 Writing Allowed Worker Types Data ... took 0ms
 Writing Allowed Building Types Data ... took 1ms
 Writing Flag Data ... took 0ms
 Writing Road Data ... took 0ms
 Writing Building Data ... took 0ms
 Writing Map Objects ... took 0ms
 Writing Wincondition Data ... took 0ms
 Writing Node Ownership Data ... took 1ms
 Writing Exploration Data ... took 0ms
 Writing Players Unseen Data ... took 1ms
 Writing Scripting Data ... took 3ms
 Writing Objective Data ... took 0ms
 Writing map images ... took 0ms
 MapSaver::save() for 'expedition' took 10ms
atlanteans trainingsites: We have used up 40% on 1 sites, there are 1 without
atlanteans trainingsites: Assigning 60% to each of the remaining 1 sites
barbarians trainingsites: We have used up 25% on 1 sites, there are 1 without
barbarians trainingsites: Assigning 75% to each of the remaining 1 sites
empire trainingsites: We have used up 35% on 2 sites, there are 1 without
empire trainingsites: Assigning 65% to each of the remaining 1 sites
frisians trainingsites: We have used up 40% on 1 sites, there are 1 without
frisians trainingsites: Assigning 60% to each of the remaining 1 sites
[sync] Reset
Trying to run: map:scripting/init.lua: Forcing flag at (8, 19)
Message: adding warehouse for player 1 at (8, 18)
Forcing flag at (16, 17)
Message: adding warehouse for player 1 at (16, 16)
MO(4,barbarians_port): Setting up port dock fields
MO(4,barbarians_port): Found 1 fields for the dock
Forcing flag at (5, 21)
Forcing flag at (4, 11)
Forcing flag at (7, 21)
Forcing flag at (10, 19)
Forcing flag at (8, 19)
Forcing flag at (10, 19)
Clearing for road at (9, 19)
Forcing flag at (10, 19)
Forcing flag at (12, 19)
Clearing for road at (11, 19)
Forcing flag at (12, 19)
Forcing flag at (14, 19)
Clearing for road at (13, 19)
Forcing flag at (14, 19)
Forcing flag at (16, 17)
Clearing for road at (15, 19)
Clearing for road at (16, 18)
Forcing flag at (7, 21)
Forcing flag at (8, 19)
Clearing for road at (8, 20)
done
Trying to run: test/maps/expedition.wmf/scripting/test_cancel_when_port_space_was_reached_two_ships.lua: MO(31,barbarians_ship): New ship: Fulla
MO(33,barbarians_ship): New ship: Volf
done
MO(6,fleet): Fleet::act
MO(3,flag): Flag::call_carrier(35): Tell building to fetch this ware
MO(41,barbarians_builder): [transfer]: starting task [movepath] and setting location to road 19
MO(3,flag): Flag::call_carrier(57): Tell building to fetch this ware
MO(91,barbarians_carrier): [fetchfromflag]: return to building
MO(92,barbarians_carrier): [fetchfromflag]: return to building
MO(91,barbarians_carrier): [fetchfromflag]: back home
MO(57,gold): cancel_moving
MO(41,barbarians_builder): [transfer]: starting task [movepath] and setting location to road 22
MO(92,barbarians_carrier): [fetchfromflag]: back home
MO(35,gold): cancel_moving
MO(38,log): cancel_moving
MO(41,barbarians_builder): [transfer]: starting task [movepath] and setting location to road 25
MO(71,barbarians_carrier): [dropoff]: flag is overloaded
MO(74,barbarians_carrier): [dropoff]: flag is overloaded
MO(41,barbarians_builder): [transfer]: starting task [movepath] and setting location to road 27
MO(77,barbarians_carrier): [dropoff]: flag is overloaded
MO(71,barbarians_carrier): [waitforcapacity]: Wake up: flag capacity.
MO(83,barbarians_carrier): [dropoff]: flag is overloaded
MO(86,barbarians_carrier): [dropoff]: flag is overloaded
MO(89,barbarians_carrier): [dropoff]: flag is overloaded
MO(71,barbarians_carrier): [dropoff]: flag is overloaded
MO(60,log): cancel_moving
MO(74,barbarians_carrier): [waitforcapacity]: Wake up: flag capacity.
MO(77,barbarians_carrier): [waitforcapacity]: Wake up: flag capacity.
MO(83,barbarians_carrier): [waitforcapacity]: Wake up: flag capacity.
MO(86,barbarians_carrier): [waitforcapacity]: Wake up: flag capacity.
MO(42,reed): cancel_moving
MO(89,barbarians_carrier): [waitforcapacity]: Wake up: flag capacity.
MO(71,barbarians_carrier): [waitforcapacity]: Wake up: flag capacity.
MO(45,log): cancel_moving
MO(48,iron): cancel_moving
MO(51,grout): cancel_moving
MO(54,granite): cancel_moving
MO(63,reed): cancel_moving
MO(66,iron): cancel_moving
MO(78,reed): cancel_moving
MO(72,granite): cancel_moving
MO(75,granite): cancel_moving
MO(98,blackwood): cancel_moving
MO(81,granite): cancel_moving
MO(84,reed): cancel_moving
MO(87,granite): cancel_moving
MO(69,grout): cancel_moving
MO(116,log): cancel_moving
MO(158,log): cancel_moving
MO(169,log): cancel_moving
MO(176,log): cancel_moving
MO(180,blackwood): cancel_moving
MO(183,log): cancel_moving
MO(196,log): cancel_moving
MO(211,blackwood): cancel_moving
MO(6,fleet): Fleet::act
MO(33,barbarians_ship): set_destination / sending to portdock 5 (carrying 0 items)
MO(33,barbarians_ship): ship_update: Go to dock 5
MO(33,barbarians_ship): ship_update: Arrived at dock 5
MO(33,barbarians_ship): set_destination / none
MO(6,fleet): Fleet::act
MO(212,log): cancel_moving
Script requests save to: reached_port_space
Gamesave: save requested: reached_port_space
Game: Writing Preload Data ... took 6ms
Game: Writing Game Class Data ... took 0ms
Game: Writing Player Info ... took 1ms
Game: Writing Map Data!
Writing Elemental Data ... took 0ms
 Writing Player Names And Tribe Data ... took 0ms
 Writing Port Spaces Data ... took 0ms
 Writing Heights Data ... took 1ms
 Writing Terrain Data ... took 1ms
 Writing Player Start Position Data ... took 0ms
 Writing Player Message Data ... took 1ms
 Writing Resources Data ... took 0ms
 Writing Map Version ... took 0ms
 Writing Allowed Worker Types Data ... took 0ms
 Writing Allowed Building Types Data ... took 1ms
 Writing Flag Data ... took 1ms
 Writing Road Data ... took 0ms
 Writing Building Data ... took 0ms
 Writing Map Objects ... took 0ms
 Writing Wincondition Data ... took 0ms
 Writing Flagdata Data ... took 1ms
 Writing Roaddata Data ... took 0ms
 Writing Buildingdata Data ... took 0ms
 Writing Node Ownership Data ... took 1ms
 Writing Exploration Data ... took 1ms
 Writing Players Unseen Data ... took 1ms
 Writing Scripting Data ... took 26ms
 Writing Objective Data ... took 0ms
 Writing map images ... took 0ms
 MapSaver::save() for 'expedition' took 37ms
Game: Writing Map Data took 37ms
Game: Writing Player Economies Info ... took 0ms
Game: Writing ai persistent data ... took 0ms
Game: Writing Command Queue Data ... took 295ms
Game: Writing Interactive Player Data ... took 0ms
GameSaver::save() took 339ms
SaveHandler::save_game() took 339ms
Autosave: save took 339 ms
Clicking button 'cancel_expedition'
Clicking button 'ok'
Closing window 'building_action_confirm'
Closing window 'shipwindow'
MO(6,fleet): Fleet::act
MO(33,barbarians_ship): set_destination / sending to portdock 5 (carrying 22 items)
MO(33,barbarians_ship): ship_update: Go to dock 5
MO(243,log): cancel_moving
MO(218,blackwood): cancel_moving
MO(219,blackwood): cancel_moving
MO(220,blackwood): cancel_moving
MO(221,gold): cancel_moving
MO(222,gold): cancel_moving
MO(223,granite): cancel_moving
MO(224,granite): cancel_moving
MO(225,granite): cancel_moving
MO(226,granite): cancel_moving
MO(227,granite): cancel_moving
MO(228,grout): cancel_moving
MO(229,grout): cancel_moving
MO(230,iron): cancel_moving
MO(231,iron): cancel_moving
MO(232,log): cancel_moving
MO(233,log): cancel_moving
MO(234,log): cancel_moving
MO(235,reed): cancel_moving
MO(236,reed): cancel_moving
MO(237,reed): cancel_moving
MO(238,reed): cancel_moving
MO(33,barbarians_ship): set_destination / none
MO(253,log): cancel_moving
MO(260,log): cancel_moving
MO(256,log): cancel_moving
MO(265,blackwood): cancel_moving
MO(258,log): cancel_moving
Clicking button 'dismantle'
Clicking button 'ok'
Closing window 'building_action_confirm'
Closing window 'building_window'
MO(17,barbarians_wood_hardener): barbarians_lumberjack leaving
MO(41,barbarians_builder): [transfer]: starting task [movepath] and setting location to road 27
MO(18,barbarians_lumberjack): [gowarehouse]: Got transfer
MO(18,barbarians_lumberjack): [transfer]: starting task [movepath] and setting location to road 19
MO(41,barbarians_builder): [transfer]: starting task [movepath] and setting location to road 25
MO(41,barbarians_builder): [transfer]: starting task [movepath] and setting location to road 22
MO(271,log): cancel_moving
```

**Pull request closed without merging**
