### PR TITLE
Rework Travis

### LINKED ISSUE #3926: Travis should test gcc/clang 10 on 20.04
Travis should also run the tests on Ubuntu Focal (20.04) with GCC-10 and clang-10.

### PR DESCRIPTION
**Pull request by gunchleoc**
* Drop MacOS 10.14
* Switch on cache
* Build with gcc10
* Replace gcc 4.8 with gcc5 as minimum requirement
* Skip translations in build stage
* No longer allow failure for includes

I tried building MacOS with GCC in GitHub actions, but there's a problem with boost https://github.com/gunchleoc/widelands/runs/989811816?check_suite_focus=true. We could try again when somebody fixes installing the current boost version for GCC. This one might do it: https://github.com/Homebrew/homebrew-core/pull/59257

Closes #3926

### CODE REVIEW

**Comment by hessenfarmer** [comment]
#3926 is related

**Comment by gunchleoc** [comment]
Thanks for the issue link :)

I haven't found Clang10 on the Ubuntu package search, so I haven't tried this yet.

The Gcc10 job has failed with a CMake issue. I'll wait for the CMake branches before I continue work on this one - maybe it will resolve itself.

**Comment by gunchleoc** [comment]
This is finally green & ready for review.

**Review by hessenfarmer — APPROVED** [review]
No idea what to review here.
I think it should be good to go if it is green

**Comment by gunchleoc** [comment]
If you want to review it some more, you could have a look at the Travis build page to see if you like the new build order and labelling. I'll be fine with just merging though when it goes green.

**Comment by hessenfarmer** [comment]
merged as it was green

**Pull request merged**
